### ISSUE TITLE
やりたいことを共有する場

### ISSUE THREAD

**Issue by treby** [imas/hackathon#1]
皆様の温度感を知りたいので、気軽に書き込んでください :)
まとまってきたら、READMEに落とすか、あるいはどなたか更新いただけますと！

**Comment by treby** [comment]
- アイマスカラオケ
- イベントのビジュアル方面、絵師さんにお願いしたい。

**Comment by hsugita** [comment]
* 会場に等身大POPを置く(持ってる人いるのか？)

**Comment by hsugita** [comment]
やりたいこととは違うんですが、当日の流れはざっくりこんな感じですかね。
* 昼過ぎ開始、アイマス関係のBGM・映像を流しつつ各自もくもくする
* 夕方にもくもく終了、成果物のLT大会
* その後希望者で懇親会、余興的にLT大会(こっちは単なるアイドルのプロモーションでもOK)
  * LT大会はひとつにまとめてもいいかも

**Comment by treby** [comment]
ミリフェスに行ってきました。

- イラストは[ふぶきさん](https://twitter.com/fbk86)に描いていただけそう
- 青ブーさんから等身大ポップちょろっとお借りできないだろうか

**Comment by treby** [comment]
会議イベントページを作りました
http://twipla.jp/events/209574

**Comment by treby** [comment]
将来的には、slackを作ってもいいかも？

**Comment by hsugita** [comment]
* ステッカー作りたい

一応、ロゴデザインをお願い出来る方の心当たりはあります。

**Comment by treby** [comment]
会場候補：CWさま(日程により)

**Comment by hsugita** [comment]
> 一応、ロゴデザインをお願い出来る方の心当たりはあります。

心当たりの方に打診したところ、大変前向きなお返事を頂けたので、作って頂けそうです。

**Comment by treby** [comment]
議論の場をhttps://github.com/imas/hackathon/issues/4 に移しましょう！
