### ISSUE TITLE
アイマスハッカソン2018 in 京都

### ISSUE THREAD

**Issue by bode-mmk** [imas/hackathon#102]
### 場所
- 株式会社はてな様 京都オフィス セミナールーム
- 京都府京都市中京区高宮町御池ビル 8F

### おひづけ
 - 2018/ 11/24 (土)

### 目標参加人数
- 20人

### 参加費
- 500円 

## 暫定的なタイムテーブル

|時刻|内容
|:-:|:-:|
|9:30|会場入り(スタッフ)|
|10:00|受付開始|
|10:30|開幕 - 挨拶等 - 終わり次第自己紹介 |
|11:00|開発開始、アイディアソン|
|12:00|昼食|
|18:00|開発終了・乾杯 / 生放送開始|
|18:30|成果発表・LT|
|20:00|終幕|
|～20:30|片付け・完全撤収|

### 今回はハッカソンなのじゃ

**Comment by bode-mmk** [comment]
### いるもの(当日に使いそうなもの)
- 文房具
- 厚紙

随時追加

**Comment by crssnky** [comment]
前回までのアイマス食  
```
ドーナツ,うろうP自作レモンタルト,メローイエロー、もやし、カリカリ梅、カロリーメイト、フライドポテト、サクマ式ドロップス、わたあめ、焼きマシュマロ、アップルパイ、きのこ山、…たけのこの里、プチシュー、ミックスナッツ。
```

**Comment by crssnky** [comment]
今日出た→  
唐揚げ、たい焼き、たこ焼き

**Comment by adachi-tsukasa** [comment]
ref: https://github.com/imas/hackathon/pull/103

**Comment by oden** [comment]
小梅

**Comment by YutaGoto** [comment]
## 直前ミーティングの内容

### connpass

https://imas.connpass.com/event/105789/

### 当日のタイムテーブル

司会: bode, cromisa

- 参加者全員が自己紹介をするかどうか
  - 今の調子の参加人数であれば全員が自己紹介してもよさそう(@yutagoto)
- 成果発表やプロデューサLTの管理方法
  - システム(im@squreなど)を作ってやるのが難しければ、当日Slackで聞く(@yutagoto)
- 進行のスライドを作る

### 備品

担当: .ごっち, momen

- ペンと付箋紙は @yutagoto が持っていきます。
- 名札入れ
- プロジェクタ、変換アダプタ
  - はてな社にありそう(@yutagoto)
- 

### 配信・BGM

担当: kiridaruma

### 食べ物・飲み物

担当: oniipon

### 打ち上げ

### イラスト

アナゴP ありがとうございます！

**Comment by crssnky** [comment]
ドリンク
- コーラ1.5L 6本  
株式会社ドーナツ様より

**Comment by oniipon** [comment]
ドミノ・ピザ（持ち帰りキャンペーン適用）
ざっくり
- ピザ1枚L(3500) * 6 = 21000 / 2 = 10500円

*厳密には半額では無く同一会計の安い方が無料
例: 4000円のピザと3500円のピザ頼んだら後者が無料になる*

**Comment by crssnky** [comment]
消耗品
- 紙コップ
- 紙皿
- お手拭き
- ティッシュ的なやつ

**Comment by oniipon** [comment]
- ピザ 10500（帰りのみタクシー？ 1000円ぐらい？）@oniipon
- 飲み物 5000 @bode-mmk @urou 
- 消耗品 2500 @bode-mmk @urou 
  - 紙コップ
  - 紙皿
  - お手拭き
  - ティッシュ的なやつ
  - 文房具

**Comment by YutaGoto** [comment]
# 当日の動き

2018/11/24(Sat) @ 株式会社はてな様

| 時刻        | 内容                          | スタッフ                                                     | 参加者                                                       | その他                   |
| ----------- | ----------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------ |
| 9:30        | スタッフ集合                  | 会場設営をする/受付を準備する                                | 事故らないように向かう                                       |                          |
| 10:00       | 受付開始                      | 受付をする(Gotch, momen, urou)/参加者誘導する/BGMを流す(kiridaruma)/スライドのテストをする | 事故らないように到着する                                     | 名刺入れ、ペン           |
| 10:30       | 開幕                          | 司会(bode, croMisa)/遅刻参加者対応(Gotch)                    |                                                              |                          |
|             | iM@Studyの紹介/会場紹介など   |                                                              |                                                              |                          |
|             | スタッフ紹介                  | 30秒ずつくらい                                               |                                                              |                          |
|             | 参加者自己紹介                |                                                              | 30秒ずつくらい(担当、普段使っている技術、ハッカソン/アイディアソンの予定) |                          |
| 11:00       | アイディアソン/ハッカソン開始 | ファシリテータを置きたい                                     | アイディアが決まっていたら開発を進める                       | ペン、付箋               |
| 12:00頃     | 昼食                          | 順番に行く                                                   |                                                              |                          |
|             |                               | 配信テストをする(kiridaruma)                                 |                                                              |                          |
|             |                               | 飲み物やピザを受け取りに行く(oniipon他)/配置換えをする       |                                                              |                          |
| 17:30頃まで |                               | 成果発表やプロデューサLTを募る/発表順を決める                | 参加する場合はSlackの #hackathon2018kyoto にポストする       |                          |
| 18:00       | 乾杯/懇親会1                  | 配信する(kiridaruma)/                                        | 飲食する                                                     | お手拭き、紙皿、台拭き   |
| 18:30       | 成果発表/PLT                  | 進行(bode, croMisa)/配信(kiridaruma)                         | 発表をする                                                   | ディスプレイ変換アダプタ |
| 20:00       | 終了                          | 片付けを始める                                               | 退出する                                                     |                          |
| 20:30       | 完全撤収                      |                                                              |                                                              |                          |
|             |                               |                                                              |                                                              |                          |
|             |                               |                                                              |                                                              |                          |
|             |                               |                                                              |                                                              |                          |
|             |                               |                                                              |                                                              |                          |

どこかのタイミングでスポンサー紹介をする

**Comment by YutaGoto** [comment]
キックオフの議事録
https://github.com/imas/hackathon/blob/master/plannings/20181021.md

直前の議事録
https://github.com/imas/hackathon/blob/master/plannings/20181117.md

**Comment by adachi-tsukasa** [comment]
スポンサー紹介は成果発表の直前かなと！
forlwellの担当の方はいらっしゃらないので、私がさくっと動画流しっちゃいます。

それとは別にチラシ（カラーコピー）を人数分配ります！
（カラーコピー代はIM@Study持ち）
