### ISSUE TITLE
アイマスハッカソン2018 in 京都 振り返り

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#109]
## 概要

- https://github.com/imas/hackathon/issues/102
- https://imas.connpass.com/event/105789/
- https://togetter.com/li/1291980
- https://youtu.be/C2MmK0OTuCI

## 参加者

- 参加登録(最終): 13人
- 参加人数: 12人

## 進め方

KPT形式です。KPTの要素意外にも気になった点があれば書き留めてください！

## テンプレ

```
# Keep
- 

# Problem
- 

# Try
- 

# その他
- 

```

**Comment by YutaGoto** [comment]
# Keep
- 終始和気あいあいとした雰囲気でした
- BGMが神がかっていました
- 配信があると会場に居なくても盛り上げられるのでよかったです
- LTしない人からも短いながらも成果発表があってよかったです
- 率先してきっかけを作りにいけた

# Problem
- 集客難しい。スタッフの方が多い状態になってしまった。
  - 他のイベントともかぶってしまったのもあります
- LTが長引いて、終了時刻を過ぎてしまいました。

# Try
- 配信を見ている人からも質問があれば質問を受けてみたいと思いました
- 他のイベントの様子を見つつ開催日時を検討していきたいです。
- (関東/関西以外の)第3の街での開催待機

# その他
- タイムコントロールはどうするのが正しかったのか。。
  - 5分予定が熱くなって10分になってしまう問題

**Comment by kiridaruma** [comment]
お疲れ様でしたー
楽しかったですね

## Keep
- BGMが好評みたいで良かったです。
  - 割と雑に流してただけですけど、TwitterやSlackで反応があって嬉しかった。
- 発表や会話が活発で、とてもいい雰囲気だったなぁと思います。
  - もくもく中も適度に会話があって、発表もワイワイ出来て楽しかった。

## Problem
- 配信での音響周りが悪かった
  - 次はマイクやオーディオインターフェースとか持ち込んでもいいかも
  - OBSだとその辺柔軟にできるので、OBSを使っての配信はやはり正解だった。
- もうちょっと人を集めたかった...
  - 告知をもっと凝ったらよかった...? (でも、東京開催会は告知打つ前に枠埋まってるし...)
  - 単に関西圏のアイマスエンジニアが少ないだけ...?
  - それとも、他イベントとの被り？(ナゴド1週間前、vimconf、frontend-conf等...)

## Try
- 次も機会があるなら関わって行きたいし、(機会を)作っていきたい！

**Comment by oniipon** [comment]
お疲れ様でしたー
とても楽しかったです
# Keep
- 初参加だったが馴染みやすい空気だった
  - 初参加でスタッフでしたが皆さんありがとうございました！！
- BGMがよかった
- 食べ物の量はいい感じだった（12人でドミノピザL6枚）
# Problem
- 参加人数が少ない（スタッフの方が多かった）
  - 他イベとの被りや3連休ど真ん中だった事が原因…？
- 人数少ないとは言えアイデアソンはやるべきだった？
  - やらないならやらないで告知するべきだった
    - この辺(アイデアソンやるかやらないか)も直前MTGで決めておくべきだった
  - 公開されているタイムスケジュールと異なるので混乱するかも
# Try
- slackで騒いでたけどもうちょっとハッシュタグ付きでtwitterでも騒いでみる（盛り上がってる感大事）
- 開催時期の調整

# その他
打ち上げ参加したかった…

**Comment by akira9146** [comment]
# Keep
- 音響が良かった
- 食べ物の量がちょうどよかった
- LTしない人からも成果発表があった
- 盛り上がりながらもくもくできた 

# Problem
- 参加人数が少なかった
- 開発前にアイデア共有をしたかった
- バグったまま発表を迎えてしまった

# Try
- Twitterでも実況してみる
- スタッフに回ってみる
- 困ったら素直に頼る

# その他
- 東京ではちゃんと動いて、さらに進化したバージョンをお見せしたいです

**Comment by treby** [comment]
お疲れ様でした。

# Keep
- 京都の町並み良いですね
- みんななかよくで良いと思いました

# Problem
- 告知のやり方は改善できそう！
- 新しい方が入りやすい環境にできると良さそう

# Try
- 名古屋開催

# その他
- 紅葉の季節の龍安寺、良かった

**Comment by Mochimagro** [comment]
今回のハッカソンでかなりの成長ができました。感謝です。

# Keep
- 今までに無い6時間ぶっ続け開発の集中力。
- 目的あっての開発は迷い無くできて良き。
- 思わぬところで就活安泰チャンス
- 自分の技術を中心にLTできて良かった。今後もがむばる。
- 作業するには最高の会話量。無音というわけでも無くうるさいわけでも無い最高の音声バランスだったから辛くもないし適度に気も緩めれた。
  - この最高環境を売りにしても良きかも。

# Problem
- もっと配信とかで外部の人を視聴してもらいたい。
  - 宣伝力を高めるしか無い？
  - インタラクティブ的に見て分かるようにもするべき(技術者では無いP向けにも)？
- LT等のスライドが配信からは明るすぎて見えなかった。
  - 画面キャプチャでの配信(東京のEngineerTalkみたいに)した方が良い？
  - 視覚情報が一番インプットできる。

# Try
- ゲームの進捗速度を上げよう。
- 関西でも小規模のもくもく会を開いて欲しい(他力本願)
- 生配信での集客を狙うなら連休ではない土日を狙うべき(連休だと公式や同人のやる確率高)
- とりあえず僕の編集能力を上げてだな･･･。

# その他
- LTのプレゼン制作が一番時間かかったかも。
  - 成果発表以外は別日に作っても良いかも。
- 別途プレゼン動画を上げてみようかな。

**Comment by urou** [comment]
皆さん、お疲れ様でした。

# Keep
- ピザの量がちょうどよい感じだった
- 会話や笑いが適度にあり、和気あいあいとした雰囲気でよかった
- 曲のつなぎ方が神！！！！！！
- 一言でも良いので成果発表は今後も続けていくべきだと思った

# Problem
- 参加者が少なくスタッフのほうが多い状態となってしまった
    - イベント被りが多かった
    - 季節がら体調不良による欠席も多かった
    - 告知をしっかりやってみるのもいいかもしれない
- 直前ミーティングでもう少し細かく当日の動きをイメージすべきだった
    - 結果、一部に不安要素が残ったまま当日を迎えることになったので。。。
- スタッフがスタッフ集合時間に間に合ってない人が複数(ごめんなさい)

# Try
- 前日に思いつきで実施することになった曲のリクエスト募集が思いのほか好評だったっぽいので、次回開催時もやるなら事前準備をしてやってみたい
- 日程をうまいこと調整して関西開催の参加人数を増やす！
- (うまいこと出来たかは別として)LT発表できたので次は…

# その他
- スタッフとして3回目の参加でしたが、今回は慣れからくる油断がどこかにあったかもしれない・・・
- 京都観光もできたし満足です。
- 名古屋もスタッフとしてお手伝いできたらうれしいです！

**Comment by bode-mmk** [comment]
遅くなりました！
僕の我儘にお付き合いいただきありがとうございました :bowing_man: 

## Keep
- BGMがとてもGoodでした！！
- 関西独特の雰囲気で楽しめたんじゃないでしょうか
- 関西のスタッフが充実してきた（きりだるまさん、おにいぽんさん :+1: )
- 関西の需要がある限り開催していきたいですね

## Problem
- 宣伝の仕方や集客の仕方 スケジュールの決定の仕方
- ぼでー、もっと頑張って

## Try
- 自分で自分の立てた関西のmotivationを思い出す
- 身内に甘えすぎず、新しい会場を開拓する
- 新しい試みをやる 失敗を恐れず普遍的にならない
