### ISSUE TITLE
アイマスハッカソン2018メシスレ

### ISSUE THREAD

**Issue by hamaco** [imas/hackathon#112]
そろそろちゃんとご飯考えないとねってことでスレをとりあえず立てる。
参加者40人+スタッフ9人で50人弱分あればいいのかな? まあその後懇親会があるしそこまでガッツリじゃなくてもよさそう。

https://imas-db.jp/calendar/birthdays によると前後の誕生日のキャラ・声優さんは以下の通りっぽい。

```
12/20 - 寺島拓篤(天ヶ瀬冬馬役)  (1983年生まれ, 34歳)
12/20 - 高橋未奈美(馬場このみ役)  (1990年生まれ, 27歳)
12/21 - 大河タケル
12/21 - ルゥ・ティン(塩見周子役)  (1993年生まれ, 24歳)
12/22 - 安済知佳(青羽美咲役)
12/23 - 原田彩楓(三船美優役)  (1997年生まれ, 20歳)
12/23 - 米内佑希(U149プロデューサー役)  (1989年生まれ, 28歳)
12/24 - 萩原雪歩
12/24 - イヴ・サンタクロース
12/24 - 信玄誠司
12/24 - のぐちゆり(及川雫役)  (1992年生まれ, 25歳)
12/25 - 柊志乃
12/25 - 望月聖
12/25 - 愛美(ジュリア役)  (1991年生まれ, 26歳)
12/25 - 野村香菜子(二階堂千鶴役)  (1989年生まれ, 28歳)
12/25 - 洲崎綾(新田美波役)  (1986年生まれ, 31歳)
12/25 - 大崎甘奈
12/25 - 大崎甜花
```

**Comment by hamaco** [comment]
思いついた(クソ）ネタは雪歩の焼肉好きとイヴ・サンタク「ロース」で焼肉だけどまあ会場で食べるものじゃないのでアウト。

ちなみに会場でもいけるcromisa氏オススメの焼肉: https://amazon.co.jp/dp/B00VWCAZC8/

**Comment by hamaco** [comment]
### After20 日本酒シリーズ

* 1杯目 わかるわ
    * [雪の茅舎 山廃純米 1.8Ｌ](https://www.amazon.co.jp/dp/B004RSXYKY) 2,800円
* 2杯目 わかるわ
    * [赤武 純米](http://www.jizakeyasan.com/item/s041-1/) 1,500円
* 3杯目 わかるわ
    * [今田酒造 海風土](https://item.rakuten.co.jp/enjoy-sake/10001222/?iasid=07rpp_10095___e1-jp9wy6e9-30-1832d267-6fe6-464e-abf8-ea90a5841e64) 1,500円
* 4杯目 三船美優さん当日が中の人の誕生日?
    * [雨後の月 スパークリングアジア 微紅330ml](https://www.yamatoya-e.com/SHOP/aiha025a.html) 600円
* 8杯目 高垣 x きらりで名前的にもよさげ?
    * [大吟醸生原酒　喜楽里（きらり）](http://www.nakao.ecnet.jp/nakaohp_029.htm) 3,000円
* 11杯目 楓&志乃
    * [小江戸 鏡山 ワイン酵母仕込み](https://www.jizake.com/html/Sake3060.html) 3,000円
    * [ワイン酵母仕込み純米酒 ARROZ](http://rikishi.co.jp/item/arroz/) 1,500円
* 12杯目 早苗さん
    * [越の誉　大吟醸生酒](http://homare.ir.shopserve.jp/SHOP/81.html) 1,500円
* 14杯目 わかるわ でも夏限定で売ってなさそう
    * [貴 夏純米 発泡にごり(https://www.kagataya.net/shopdetail/000000001643/) 1,500円
* 19杯目 楓さん
    * [吟望天青 純米酒 1800ml](https://www.yajima-jizake.co.jp/products/detail.php?product_id=3158) 2,700円

4杯目の雨後の月と8杯目の喜楽里にあと1本くらい追加すればいいんじゃなかろうか。 3本だと多いか?

**Comment by hamaco** [comment]
信玄誠司のキャッチコピーが「スマイル&ピース！元・自衛官の得意料理はハンバーグ！？」らしいのでハンバーグか…。

**Comment by hamaco** [comment]
##  ケータリング

ピザ適当に頼んであとは Engineer Talks みたいにオードブル足せばいいのでは( ˘ω˘)ｽﾔｧ…

ハンバーグと唐揚げがありそうなやつ
https://www.quickdelistyle.com/allplate/

あとはアイドルっぽさある「花ざかり」とかそういう系考えたけど特に思いつかなかったのでまた明日。

**Comment by hamaco** [comment]
### 打ち上げ

treby氏がconnpassページ作ってくれるはずなのでそれで人数なんとなく分かったらもうちょい考える。
あとはmomenニキがなにをしたいか次第。ウェイウェイ。

**Comment by adachi-tsukasa** [comment]
おお！あざす！！
打ち上げの新しいことは特に考えてないです！
LT大会を打ち上げでって話もコントローラブルじゃないなあと思っているので、
いつもどおりの打ち上げで考えていただければ

**Comment by treby** [comment]
https://imas.connpass.com/event/110943/ 出した

**Comment by treby** [comment]
[打ち上げ]

https://www.spacemarket.com/event_types/party/areas/Roppongi?page=1&startedAt=2018-12-23&startedTime=20%3A00&endedTime=23%3A00&minCapacity=30&priceType=HOURLY&geocode=35.6641222%2C139.729426%2C2223.7m
memo こういう箱でも良いのかしらね

**Comment by hamaco** [comment]
Engineer Talks が56人でピザ10枚+おかずって感じだったから、45人くらいとしてちょっと減らしてピザ8枚+↑の大皿3-4つくらいでいいのかなー?

お酒はカクヤスで多少余っても打ち上げに持ち込めるからビール・チューハイ合わせて80本くらい? +ソフドリ?
てか打ち上げの飲食どうやって持ち込もう。時間指定ピンポイントでしづらいよね。

**Comment by hamaco** [comment]
日本酒は池袋で買えそうなAfter20 1杯目のやつ(同一ではない)とアイマスっぽい5人娘とあともうちょっと見てから( ˘ω˘)ｽﾔｧ
ワイン…。 よく分からない…( ˘ω˘)ｽﾔｧ

**Comment by hamaco** [comment]
まだ注文もなにもしてないけど明日行けないし超テキトーに計算した。

### メシ

ピザ 2,000 * 8 = 16,000円
おかず 4,000 * 3 = 12,000円
だと少ないかな? メシの量がよく分からん…( ˘ω˘)ｽﾔｧ

### 酒

ビール 5,400 * 2ケース(48本) = 10,800円
酎ハイ系 110 * 30本 = 3,300円くらい
ソフドリは昼からずっと何本か出してるでしょ? 1,500円くらいなのかな?
日本酒ワイン 3本で6,500円予定

テキトー計算で28,000 + 23,000くらい? あとはもめんニキの財政次第でお酒を削っていく( ˘ω˘)ｽﾔｧ…

**Comment by treby** [comment]
[貸切＆パーティ ＧＥＮＫＩ 六本木](https://r.gnavi.co.jp/9vz63hky0000/)

打ち上げの場所ここにしました。
21:00〜飲み放題2時間の軽食3品付き@ 3,500円
貸し切り＆プロジェクターある＆歌える(らしい)

持ち込みよいかどうかとかも聞こう。

**Comment by treby** [comment]
イメージ感(案)

- 学生： 1,000
- 社会人(〜新卒3年目)： 3,000
- 社会人： 4,000

大人力とIM@Study予算と相談の上でFix

**Comment by treby** [comment]
```
# ドリンク
## カクヤス一択
http://www.kakuyasu.co.jp/

# オードブル系
## レガラート
http://www.regalato.jp/index.html
### 注文
9,800円（+送料1,500円）から
### 支払い方法
現金/請求書
### メモ
- 単品オードブル
- からあげ安いしオススメ
- チーズのピンチョスは微妙

# 主食系
## Sand Wich's
http://sandwich-s.com/
### 注文
9,000円〜（送料なし）
### 支払い方法
現金/請求書
### メモ
- いつもパーティーサンドを利用してます

# ほか（利用したことない）
## ケータリングスタイル
http://www.catering-style.com/
## デリズ
http://delis.co.jp/index.php
##

# ひとり1500円くらい予算ある時
## シェフコレ
http://www.chef-colle.com/
```

```
# 注意
最終的な注文は@mizuhoさんにしてもらうこと
（例）カクヤスであればカートに入れた状態で引き継ぐor作成した見積書pdfなどを共有
- 代引きの場合は@yechigoさん承認後こちらで注文 → @mizuhoさんに必要な金額を伝えてお金をもらう

## ドリンク
- カクヤス
http://www.kakuyasu.co.jp/
    - 数量は過去の同規模のイベントでの注文履歴を参考に
    - 冷えた状態で届けてくれる「冷やし指定」を忘れずに

## フード
- 萬作
http://mansaku-delivery.com/shoplist_index/
    - 価格・味ともにまあまあ
    - からあげは安い。出すと喜ばれる
 
- レガラート
http://www.regalato.jp/index.html
    - とにかく安いので品数を多くしたい場合に　味は...

- Sand Wich's
http://sandwich-s.com/
    - サンドウィッチ類
    - 味微妙

- デリズ
https://delis.co.jp/index.php

- ケータリングスタイル
http://www.catering-style.com/
```

らしいにょん

**Comment by treby** [comment]
- 懇親会周り：基本Repro持ちなので、trebyで精算します。
- イベント雑費：後日になるかもですが、IM@Studyで精算します。

打ち上げ今のところ:

- 参加費回収分 …… 71,000 (26名)
- 支払い予定分 …… 3,500 * 26 = 91,000
- (後で多少変動見込み)

差分はIM@Study宛で精算します。

**Comment by treby** [comment]
- 懇親会：基本精算済み(hamaco, treby)
  - Pizza: 18,792円(代引き)
  - 惣菜: 11,880円 (代引き)
  - ビール: 13,662円 (クレカ)
  - その他酒: 当初6,000円くらいって言ってたけどテキトーに買ってしまったので余っただけでいいよ。足りない分は僕が払ってもいい。
- 打ち上げ
  - 回収金額: 71,000(事前) + (3,000 * 7)(追加) = 92,000円
  - 支払い金額: 115,500円(＠ 3,500)
  - 差額: 23,500円 -> これをどこかで精算
