### ISSUE TITLE
IM@S Engineer Talks 2019

### ISSUE THREAD

**Issue by adachi-tsukasa** [imas/hackathon#126]
# 開催概要（随時アップデート）

- 日時: 2019/07/06 (Sat) 11:00〜18:00 19時完全撤収
- 場所: Speee Launge 六本木
- 人数: 前回60/65人,前々回51/53人
- セッション枠：
  - Ut Video Codec Suite 高速化の11年 umezawasさん(45min)
  - データサイエンスアイドル「小日向美穂」と考える「つながり」 takemikamiさん(30min)
  - 小鳥さんとKotlinを勉強できるサイトを100%Kotlinで作る nishikori saburohさん(30min)
- LT枠：WIP&別でまとめる

- スタッフ
  - fusagiko(司会、名札)
  - kataoka,gotch(LT調整、飲食/懇親会)
  - deflis, treby(配信)
  - hamaco(人集め、大変なとこ、受付/LT進行)
  - hamu, nakahiko(その他)
  - momen(連絡/広報)

**Comment by adachi-tsukasa** [comment]
とりあえずキックオフのめも

fusagiko(司会、名札)
kataoka,gotch(LT調整、飲食/懇親会)
deflis, treby(配信)
hamaco(人集め,大変なとこ, 受付/LT進行)
hamu(その他)
momen(連絡/広報)

**Comment by YutaGoto** [comment]
connpassヘッダー画像 
![IM@S-Engineer-Talks_2019_660-270](https://user-images.githubusercontent.com/12590762/57085210-b131c000-6d36-11e9-91ad-7d37655fb671.jpg)

**Comment by katao** [comment]
アイマス飯
```
・ぷちシュー
・マシュマロ
・フリーズドライのりんご/いちご
・たべっ子どうぶつ/おっとっと
・おにぎりせんべい
・フライドポテト(Uber eats)
・ドーナツ
```

**Comment by YutaGoto** [comment]
LT: 5分 * 15人くらい

**Comment by adachi-tsukasa** [comment]
タイムテーブル仮ぎめしました！！

11:00 スタッフ入り
12:00 開場
12:20 開始・諸注意
12:30〜 発表+質疑
12:30〜13:10 セッション枠1（仮、時間も仮）
13:20〜13:50 セッション枠2（仮、時間も仮）
14:00〜14:30 セッション枠3（仮、時間も仮）
14:30〜15:00 LT準備
15:00 乾杯
歓談・名刺交換
15:30〜16:10 LT 第一部
16:30〜17:10 LT 第二部
18:00 クロージング・閉会・撤収準備
19:00 完全撤収

**Comment by adachi-tsukasa** [comment]
groovesさんスポンサー打診中
（connpassイベントページ公開したときに、groovesさんのスポンサー申し込めるリンク出てくるようになってた）

**Comment by adachi-tsukasa** [comment]
ref #132

**Comment by adachi-tsukasa** [comment]
@YutaGoto @katao 
以下、せりーぬさんより
```
イベントだとピザ、寿司、サンドイッチのときは普通に出前館、
ちょっとパーティーフードみたいなのがいい時はこういったところです！↓
https://www.chef-colle.com/regalato/660-sandwich-finger/
https://www.partytimes.co.jp/item/ptc-0002.html
https://www.chef-colle.com/aji-ichi/finger15/
```

**Comment by adachi-tsukasa** [comment]
```
# スタッフタイムテーブル
11:00 
	会場入り、会場設営開始
12:00 
	受付開始（たぶん前倒して受付開始しそう）
12:20 イベント開始
	司会進行、配信開始
12:30 1部開始
	セッションコントロール
14:30 セッション終了〜乾杯
	配信一時停止、飲食到着、会場設営しなおし？椅子を片付けるとか
15:00 乾杯
	配信開始
15:15 - 17:30  LT第一部,第二部
	LTコントロール
17:30 閉会の挨拶
	配信終了
18:00 片付け・撤収
	名札回収
19:00 完全撤収
```

**Comment by adachi-tsukasa** [comment]
momen当日持ち物

- [ ] 名札入れ
- [ ] forkwellチラシ
- [ ] （あれば）アイマスハッカソンステッカー
- [ ] まゆ

**Comment by katao** [comment]
14:00〜14:40に
もえぎていケータリング 鶏唐とポテト盛合せ
4～5人前 ¥4,000 * 5 が来ます。

**Comment by YutaGoto** [comment]
07/06　   １４時－１５時にお届け！ 
カクヤスが来ます。
おさけ/ソフトドリンク/プラスチックコップ合わせて15,498円(クレカ決済 済み)
