### ISSUE TITLE
アイマス Advent Calendar

### ISSUE THREAD

**Issue by treby** [imas/hackathon#13]
あったら書きますか？ ＞ みなさま

@hsugita @hamaco @knit-subaruP @katao

**Comment by hsugita** [comment]
Advent Calenar作るのは面白そうなので賛成です。
もしやるのなら、1,2枠埋めるぐらいの気持ちはあります。

**Comment by hamaco** [comment]
まかせろーバリバリー。

**Comment by treby** [comment]
良いものを見つけた。ここに書いていきましょう(ハッカソンのステマとかしながら)
[アイドルマスター Advent Calendar 2016](http://www.adventar.org/calendars/1418)

**Comment by treby** [comment]
@hamaco さんの参戦が待たれる……！

**Comment by hamaco** [comment]
やっと落ち着いたのでまったり登録した。

**Comment by kaibasira** [comment]
@treby さんにinvite頂いたのでそのままjoinしました
関西シンデレラ勢ですが当日は現地に向かいたいなど思っています。
何か当方で手伝えることがあれば教えてください。よろしくお願いします。

//新規issue立てるほどでも無いと思ったのでこちらに...... github使い慣れてなくてすみません、

**Comment by treby** [comment]
よろしくお願いします！

**Comment by hamaco** [comment]
わーい！ミリマス勢以外の勢力が現れたぞー:tada:
よろしくお願いしまっす！！

**Comment by hsugita** [comment]
アドベントカレンダー始まったから閉じようかなーと思ったけど、openしとけば誰かの目に留まって書いてくれるかもだし、期間終了まで閉じないでおきましょうか。

**Comment by hsugita** [comment]
最終日なのでもう閉じますねー
