### ISSUE TITLE
IM@S Engineer Talks 2019 振り返り

### ISSUE THREAD

**Issue by adachi-tsukasa** [imas/hackathon#133]
# 概要

- #96 の振り返り
- https://imas.connpass.com/event/90996/
- 参加者
  - 参加登録者数(最終)：63人
  - 参加者数：60人 (出席率 95%)

# 進め方

KPT形式でお願いします。他に何か気になることがあれば書いてください。

**Comment by adachi-tsukasa** [comment]
お疲れ様でした！！！

# Keep

- 2回目のEngineerTalks開催！ひとえに皆様のおかげです…！
- はがきサイズ名札入れ。中身持ち帰る方多いし、これは継続したい。やよいちゃんも可愛かった。
- アイマス的飲食導入。飲食スライド良かったと思います！
- YoutubeLive。deflisさんだけでほぼ回せた？？
- 公式の懇親会を開催しないこと。非公式ではtrebyさんあざす!

# Problem

- connpassイベントページで参加登録時のアンケート忘れ。アンケートからLT登録流入をなくしてしまった。
- 受付担当（私）小銭忘れ。直前に500円玉10枚作りました。
- 最初にトイレ等会場案内の説明がなかった。
- Speeeさんのスライドがないことを想定していなかった。事前にせりーぬさんに聞くべきだった。
- Groovesさん動画は事前にチェックすべきだった。
- 飲食少ないと感じたタイミングですぐ動くべきだった。
- ごっちさん、かたおかさんに負荷掛かりすぎてた感。LT調整と飲食は係を分ける。

# Try

- 飲食スポンサー欲しい。非公式の寿司じゃないけど、盛り上がれるサムシングがもう少し飲食に欲しい。
- 参加費積極的キャッシュレス。
- こんな話し聞きたい。こんな人に話しをして欲しい。をいい感じにコンテンツに落とし込みたい。

**Comment by deflis** [comment]
# Keep

* 大きなトラブル無しで終わった
* 配信もなんとかそつなく回りました
  * 自分かフサギコさんがいれば回る状態にはなったかな？
  * やっぱりケーブルの長さが課題。事前に気づいてギリギリで買ったのでなんとかなった。
* イラスト可愛いのでカバーアートは継続してほしい
* 全体的にコンテンツが良かった。

# Problem

* ノウハウ伝授失敗。
* 配信席の場所をはじめから決める。
* BGMの流し方を別途考えておくべきだった。
  * YouTube側にBGM流すと権利者削除が怖いので、次回は対策したい…。
* 配信周りからあまり動けなかったので、プレゼン以外の話が聞けてなかった。

# Try

* ゆーむPみたいな濃い話を増やせたら面白そう。
* キャッシュレス化、パスマーケットとか使ってみる？

**Comment by treby** [comment]
# Keep

- 発表者に対して会の終了後に発表資料を載せるように促したのは良かった
- イベント自体の盛り上がり方は安定してきた感じがあって良いですね。
- 役割をシャッフルしていくこと
  - イベントの参加者と同じくらいスタッフの参加体験を良くしていきたい
- 参加者名札を作っていくのは良いですね 👍 

# Problem

- 配信に関して私空気ｗ(雰囲気見る役)
- イベント体験としてデグレっているところがあった
    - 参加登録時のアンケート、オープニングスライドの内容、飲食の量など

# Try

- デグレ防止施策
  - 認識していても開催頻度的に忘れるのでドキュメント化してはどうでしょう
  - 全体的にGitHubリポジトリをもっと活用していきたいですね。
- もっとカジュアルに開いていくのはありですね
  - もくもく分科会、各タイトル分科会など
- 地方での開催を支援してく方向

**Comment by YutaGoto** [comment]
飲み物を運んだせいで右腕が筋肉痛になりましたｗ

## Keep

- 名札やつは続けていきたい。
- アイマス関連のみものの紹介あってよかった。
  - ソフトドリンクの部もあるのも :+1:
- YouTube Live。概ね問題ないように見えましたありがとうございます。
- のみものの量はなぜかジャストであった。
  - ログ残します。はい

## Problem

- connpassの参加者登録はスタッフ/一般の他にLTで人数区切ってよいかなと。
  - ハッカソンのときは その2つでよいかと思うけど。
- 会場の使われ方的な話。
- 



## Try

- 勝手にSAKEスポンサーしてくれる参加者は事前にconnpassかフォームかでまとめたい。
  - SAKEとかのスポンサー参加者は参加費無料でもよいのでは。。？
- 地方開催(関東/関西以外のところ)もしたいなぁ。。
- もくもくスタイルもしたいなぁ。。。

**Comment by takayamaki** [comment]
## keep
- 名札は好評だったので良かった
- 配信担当の役割は完全に2重化できたといって良い
  - 一部機材貸しただけ
  - trebyさんが書いている通り、3重化はまだ
- 主な参加者層が普段触っているよりもっと下の層の話をUtVideoを題材に話してもらえたのは良かった
  - どうしてもWebサービスやスマートフォンのネイティブアプリ辺りに偏りがちなので
- 飲食紹介スライドは良かった
- 初めて来ましたという人が今回もそこそこいたので良かった

## Problem
- 司会スライドおよび喋る内容、流れの練り不足
  - ミリ6th福岡からのUNI-ON@IRイベント爆走からの体調不良で役割を果たせたとは少々言いづらい
- 食べ物足りなかった
  - 昼頃だから～という理由で少なめになっていた記憶があるが減らす必要なかったかも
  - 予算が許したなら…
- LT大会前の準備中、当初参加者の手で折りたたみ椅子を仕舞わせてしまったことで時間がかかり、椅子を持った人の列ができてしまった
  - 途中から僕が入り、とりあえず受け取ることで列解消をした
  - 全て受け取り終わった後にかたおかさんと僕の二人で積んだ
- 貸したHDMIキャプチャユニットでHDMI音声が取れない問題のワークアラウンドを伝えるのを忘れていた
  - カスタム音声デバイスの使用にチェックを入れて明示的に指定しないと音声が取れない
  - たぶんOBSのバグ

## Try
- 配信方法もいいかげんドキュメントにまとめる
  - 二重化できたのは結局deflisさんも誘う前から経験があったからなので…

## YouTube Live
- 同時視聴者数最大27人
- 平均視聴時間22分9秒
- 中央値が知りたい…

## その他
- これ含め公私色々予定を詰め込み過ぎて疲れ気味なので今年下旬はちょっと抑えたい…

**Comment by katao** [comment]
Keep
・とりあえず開催できた。
・全体的にLTのLVが高かった。(技術的にも面白さでも)
・Speeeさんのなれてる感
・毎度出席率高い(95%)
・「お酒持ってきていいよ」は結果良かった。

Problem
・ご飯少なかった。。。
・仕方ないけどニコ生とかぶった。
・参加者に感想アンケートやってない？
・LTが前倒し前倒しになりすぎた。
(残りの時間を考えて少し伸ばしたり、質問ある人？をやってもよかったかも)

Try
・アイマス飯のノウハウはためたい。
・個人の飯・酒スポンサーはちゃんと管理して、オープニングスライドに「Food Sponsor ◯◯P」とか？
・毎回使うOPスライド・EDスライド・司会のカンペとかはあってもいいのかも。
・公式Twitterアカウント作り実況は可能？

**Comment by takanakahiko** [comment]
遅れてすみません！
私自身は当日に参加できませんでしたが一応書きます．

## Keep
- 遠隔でも Twitter や Youtube Live で盛り上がりが伝わってきてよかった．
- 次回から参加したいとの連絡を受けたので反響は良かったと思う

## Problem
- (私自身のミスですが) 他のイベントと被って当日参加できなかった
- 仕方ないけど公式のニコ生と被った
- 他の人のKPT見るに，デグレっている部分が多いみたい

## Try
- 運営していくにあたってのドキュメントとかがあると良さそう(配信マニュアル等)

**Comment by hamup8** [comment]
遅くなってすみません...！

## Keep
- 手の回ってないところに入ってすっと手伝えたのは良かった。
- お酒の持ち寄り良かった。
- 名札よき。イベント感が上がりますね。
- 幅広いレイヤーのLTがあって良かった。

## Problem
- 打ち合わせ含め当日以外ほとんど調整・準備に関われなかった...。（自分の問題）
- LTやるときはやっぱりドラもしくは代用となるものを用意しておくべきだった。（今回は時間が余っていたので問題なかったが。）
- 名刺持参の人も名札にペンで名前書いて使用しているケースがあった。（Problemなのかという感じだが）  
名刺利用もOKだよーの旨貼り紙しておいた方がスムーズだったかも。

## Try
- 次回参加時はコミット率を高めていく。

**Comment by deflis** [comment]
# Try
* TwitterとYouTubeのコメントを表示する画面をどこかに作りたい

**Comment by adachi-tsukasa** [comment]
ref: #137
