### ISSUE TITLE
アイマスもくもく会 in 関東 について考える

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#134]
ひとまず立てるだけたてるの巻

**Comment by YutaGoto** [comment]
セルフブレスト

- Slackの #mokumoku をちゃんと活用し始めたい
- エンジニアだけではなく、デザイナさんやライターさん(imasbook含む)も参加してほしい
- 会場いいとこないかなぁ

**Comment by kiridaruma** [comment]
大阪でもくもく会+LT会みたいなのを秋〜冬(今年中)に考えてたりします
(研究室が後援してくれそうなので、自分の学校でやろうかなと構想中です)

**Comment by subroh0508** [comment]
関東 + 参加者上限20人とかなら、iOSDCの作戦会議の時みたくHey社のエントランスと会議室は貸せると思いますー！

(エントランス: 10人/会議室: 10人 + 6人 + 4人)

**Comment by YutaGoto** [comment]
20人30人来るとゆるふわもくもく会制御がむずくなるので、Max 10人かなーとは思ってます。
力をいれすぎずにやっていきたい（プリッカソン的発想）

**Comment by YutaGoto** [comment]
MoneyForwardさん人事の方に相談したところ、平日夜且つ誰かが立会(or 参加)すれば可能です 🙆 とのことでした！社にアイマスPエンジニアがいなかったとしても他の会社につなぐことも可能ですといってくださり圧倒的感謝。。！

大々的な準備(ごはんとかかっちりとしたタイムテーブルとか)いらないはずなので、
8月下旬か9月上旬中旬に一回 会を開いて感覚掴んでいきたいところです。。

**Comment by adachi-tsukasa** [comment]
おお！！すばら！！

**Comment by YutaGoto** [comment]
mokumokuリポジトリを作ってこのあとはそこで管理しようかなーと思います〜〜

**Comment by subroh0508** [comment]
マネフォ本社、JR田町駅降りてすぐですねー 👀 (ガチ競合だけど普通に行ってみたい)

https://goo.gl/maps/kSTdNBNrxihcNhJ38

**Comment by YutaGoto** [comment]
https://github.com/imas/mokmoku

作ったので詳しい計画とかはmokumokuリポジトリでやります！みなさんありがとうございます！！
