### ISSUE TITLE
アイマスハッカソン in 大阪 2nd-mix

### ISSUE THREAD

**Issue by kiridaruma** [imas/hackathon#136]
細かいことは今後追って追記/編集していきます

## 概要(決定事項)
日時: 12/7 10:00〜20:00
会場: さくらインターネットさん

## やることリスト(今後決めないといけないこと)
- キックオフ会
  - 日時(9月末〜10月真ん中で調整さんで調整中)
  - 会場

**Comment by crssnky** [comment]
最初のMTG  
https://docs.google.com/document/d/1NuQA8J8p_qkZDN7ux-LnVbarpyUlImv1MeOfHpSfbIk/edit#heading=h.hjjmgucf33es

**Comment by crssnky** [comment]
直前のMTG  
https://docs.google.com/document/d/1Csdkwykus4C_GnaxtTsqeeB3iXd8DvWVBvUZtZ7Pqyo/edit#heading=h.rpo6d8w73wof

**Comment by crssnky** [comment]
# 夜の予定
### ピザ
Lサイズ：3枚

### ドーナツ
ドーナツをテキトーに15個

### ドリンク
ビールを6個
甘いお酒を4個
ジュースを2本
お茶を2本

### 備品
皿
お手拭き

**Comment by crssnky** [comment]
クワトロ・シェフズ プレミアムセレクション
1.ブラックアンガスビーフ&ガーリック 2.スモークサーモン バジルマヨ 3.ブラックアンガスビーフ&リッチグレービーソース 4.スモークサーモン&北海道カマンベールチーズの組み合わせ。

クワトロ・チーズンロール
1.マルゲリータ 2.ドミノ・デラックス 3.シーフード・スペシャル(トマトソース) 4.ガーリック・マスターの組み合わせ。※ずわい蟹は殻や中骨が入っている場合がございます。

マルゲリータ
バジルとチェリートマトの酸味が抜群の取り合わせ。バジルの甘くて爽やかな香りが決め手です。
