### ISSUE TITLE
アイマスハッカソン2019  LT タイムテーブル

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#142]
https://github.com/imas/hackathon/issues/140

# LTをするPリスト

成果発表・プロデューサーLTは18:00 - 20:00まで

一人あたり5分。

成果発表、LTタイムテーブル(1チーム5分)

| 時間        | 東京                        | 大阪                                             |
| ----------- | --------------------------- | ------------------------------------------------ |
| 17:40-17:50 |                             | スポンサー さくらインターネットさん アシラスさん |
| 17:50-18:10 | スポンサー BearTailさん     |                                                  |
| 18:10-18:25 | 全員の成果発表(1人30秒程度) |                                                  |
| 18:25-18:30 |                             | 全員の成果発表(1人30秒程度)                      |
| 18:30-18:35 |                             | kiridaruma                                       |
| 18:36       |                             | 導線P                                            |
| 18:42       |                             | croMisa                                          |
| 18:48       |                             | oniipon                                          |
| 18:54       |                             | 大阪だれか                                       |
| 19:00-19:10 | 休憩                        | 休憩                                             |
| 19:10       | かばにゃす                  |                                                  |
| 19:16       | mh35                        |                                                  |
| 19:22       | Ak_hina                     |                                                  |
| 19:28       | ただただし                  |                                                  |
| 19:34       | カタヲ                      |                                                  |
| 19:40       | .ごっち                     |                                                  |
| 19:46       | がんばりマッキントッシュ    |                                                  |

## 東京

| 時刻 | P          | タイトル(仮)                                            |
| ---- | ---------- | ------------------------------------------------------- |
|      | ak_hina    | 統計的に見るTHE@TER CHALLENGE!!!                        |
|      | mh35       | コンベンションセンターを作ってみた ～技書博本内容概略～ |
|      | かばにゃす | 283プロの確定申告まとめ                                 |

## 大阪

| 時刻 | P          | タイトル(仮)                   |
| ---- | ---------- | ------------------------------ |
|      | kiridaruma | 研究室でアイマスを浸透させたい |
|      | 導線P      | (未定)                         |

**Comment by YutaGoto** [comment]
当日LTする表明テンプレ(締め切りは当日17時 or 枠が埋まり次第)

## 会場

東京・大阪

## チーム名／プロデューサー名

例) チーム佐久間家

## タイトル

例) KVBつくった

```
## 会場

東京・大阪

## チーム名／プロデューサー名

## タイトル

```

**Comment by tdtds** [comment]
## 会場

東京

## チーム名／プロデューサー名

ただただし

## タイトル

Webラジオを聴こうぜ

**Comment by crssnky** [comment]
## 会場

大阪

## プロデューサー名

croMisa

## タイトル

UE4でアイマス楽曲を盛り上げてけ☆

**Comment by oniipon** [comment]
## 会場
大阪

## チーム名／プロデューサー名
おにいぽん

## タイトル
デレ7thで大阪に来るPチャンにオススメしたい大阪

**Comment by YutaGoto** [comment]
## 会場

東京

## チーム名／プロデューサー名

.ごっち

## タイトル

みりした！ (今日の成果)

**Comment by kagemiku** [comment]
## 会場

東京

## チーム名／プロデューサー名
がんばりマッキントッシュ

## タイトル
S(min)ING! (Metalでない)

**Comment by katao** [comment]
## 会場

東京

## チーム名／プロデューサー名

カタヲ

## タイトル

ユニットが覚えられないおじさん

**Comment by maraigue** [comment]
## 会場

大阪

## チーム名／プロデューサー名

導線

## タイトル

シンデレラガール総選挙の「50位圏内の難しさ」はいかほどか？

**Comment by YutaGoto** [comment]
みなさんありがとうございました。
