### ISSUE TITLE
アイマスハッカソン in 大阪 2nd-mix 振り返り

### ISSUE THREAD

**Issue by crssnky** [imas/hackathon#144]
# 概要
- #136 の振り返り
- https://imas.connpass.com/event/154962/
- 参加者
  - 登録者:12名
  - 登録参加者:10名
  - 非登録参加者:2名(?正確に覚えてない?)

# KPT
- いつものやつです
- "その他"なこともあれば、書いてください!

# テンプレート
```
# Keep
- 

# Problem
- 

# Try
- 

# その他
-
``

**Comment by oniipon** [comment]
お疲れさまでした！！
# Keep
- 東西同時開催出来た
- LTタイムテーブル作成もグダらずに出来た（ごっちさんありがとうございます！！）
- スタッフより参加者の方が多かった
- hey社スポンサー

# Problem
- 配信周り大分グダった
 - きりだるまさんが東京へ行くので配信周り強い人がいない…
- 関西でもランチマップ用意してもよかったかも
- やはり参加者が少ない
 - 技術系コミュニティで宣伝する？
- ピザの注文グダった（おのれドミノ）
- ハッカソン初の人達へのフォローが甘かった

# Try
- 東西同時でやるならもうちょい事前に配信周りの確認するかビデオ会議システムある会場さんを探す？

# その他
-

**Comment by kiridaruma** [comment]
# Keep
- 広がるアイマスエンジニアの輪！
  - 東西同時開催！
  - 課題はともかく、新たな試みができた
- とりあえず開催できた
  - いやホント無事できてよかった

# Problem
- 配信周り
  - まぁ仕方ないところが多分にある
  - 次回があるなら頑張りたい

# Try
- もっといろんな人が参加できるような集まりにしたいですね
- (個人)最初の挨拶はもっとかっちりやっても良かった(いくつか注意事項が抜けてた)

# その他

自分は来年から東京行きますけど、大阪よろしくおねがいしますね

**Comment by crssnky** [comment]
立てて放置
# Keep
- 初の東西同時開催！
- しかも互いのLTが見える！
- 関東のスタッフ・参加者が居なくても成り立つ！
- 豪華な飲食物！
- 綺麗で駅近な会場！

# Problem
- LTは見える、声は聞こえない
- 飲食の分量が豪華過ぎた
- ハッカソン自体初参加者が多く、ファシリテーター力(りょく)が足りなかった
  - そもそもスタッフでばかり参加してて一般参加って何するんだろう...?

# Try
- ファシリテーター力(りょく)
- 集客力
- 飯スタッフ力(りょく)

# その他
- 名古屋はおいおい考えます

**Comment by nano913** [comment]
おつかれさまですのなちょです。
ぎりぎりですみません！
初心者なりの意見になります！

# Keep
- 初参加でしたが、色々な方のLTを見ることができて良い刺激になりました楽しかったです！
-ハッカソン自体初めてで何をすればいいのか全く分からなかったので、最初にアイデアソン皆さんとできたのが良かったです！
-ごはんおいしかったしあわせ………！！！
- 会場が豪華！！！
- お昼ごはん食べに行くにもどう行けばいいかどこに何があるわからなかったのでみんなで行こうって感じになって助かりました！

# Problem
- 場所迷子(恐らく私のproblem)
- 結構web系の方が多いように感じたので、もっといろんな人が参加できるようにできたら良いのかな？と思いました！(宣伝が足りなかった…！)

# Try
- もっと人を増やせたら良いなと思います！
- そもそも主催者問題があるので、まずは主催しませう…！

# その他
-

**Comment by maraigue** [comment]
導線です。お疲れ様でした。

# Keep
- アイデアソンにある程度の人数が入っていた（少なすぎると大変だろうということで）
- アイデアソンで、思い当たることがある人がちゃんと話すようにしていたのがよかった
- グッズや、アイマス的にネタになる飲食物などを用意したことは、初めて来た方々にとって雰囲気をよくすることにもなっていると思う
- 懇親会については、今回はスポンサー（アシラス様）が付いてくださったが、それがない場合を想定して動いておけたのはよかった
- 成果発表LTはやはり盛り上がる

# Problem
- 集客はなかなか難しい
- 今回はいつも以上にLTパートが長く、懇親会でなかなか他の方と話せなかった
- 当日、自分はあまりスタッフらしい仕事をしてなかった
  - 仕事の量が少なくて済んだともいえるのかもしれないが（もし仕事はあった、という状況だったのでしたらすみません・・・）

# Try
- アイデアソンでなかなか話せない（慣れてないというのが大きそう）方々をどう促していくか
- （LTではない）一言成果発表においても、1～2枚程度のスライドを作ってもらうとよいかもしれない。聞き逃して何なのか分からなくなってしまいそうなこともあったので

# その他
- さくらインターネット様、今回も会場提供ありがとうございます

**Comment by crssnky** [comment]
# KPT
## oniipon
- 東西良かった
- LTタイムテーブルごっちさんに任せた(ブレイン1つ)が良かった
- 12人も集まった！
  - ふみをさん、園児さん
- スポンサー良かったでしょ、次回もやってくれるんじゃない？
- 配信難しい
  - きりだるまさん、東京行っちゃうと大阪のスタッフが...
- 関西ランチマップほしい
- もうちょい参加者ほしい
  - ほかのコミュニティで宣伝が必要かな
- ドミノ・ピザなんで注文できんのや！
- ハッカソン初参加へのフォロー
- 配信はもっと事前に試すか、配信できる会場探しが必要かな
  - 同時開催であれば、次は向上したい

## kiridaruma
- 東西同時開催！
  - 課題はともかく、一歩進められた！
- 開催できてよかった！
- 配信周りはもうどうしようも無いのかなぁ...
  - 今回は手探りだったので、これを踏まえて次は考えていきたい
- 「積極的でない人」が多い
  - 「つよい」・「積極的」は関西から出て関東の方に行ってしまう...?
  - 関西らしさをもうちょい出したかった
- 関西の人でももっといろんなひとが参加できるような集まりにしたい
- 最初の挨拶とかはかっちりやった方が良かった
- EngineerTalk形式を大阪か同時開催でしたい
- 配信は何が原因？
  - 帯域は良い
  - レイテンシが大きい
  - 向こうでなにかがごっちゃになってたらしい
  - deflisさんにも話を聞かないと
  - 音声に関しては、マイク→スピーカー→空気→マイクってのが駄目
  - 直接電気的に音声を取らないと上手く行かない
  - 映像はキャプチャ課金したおかげで無事だった

## cromisa
- 名古屋は4月かなぁ
  - 来月の新年会でちょっと空気みてる
- 飯難しい
  - 加蓮多い
  - 日本酒×2は人数に比べて豪華過ぎた
  - アルコールウェルカムな人が思ったより居なかった

## dousen
- アイデアソンにけっこう人が集まってよかった
  - 発言もしやすかったと思う
- グッズやアイマス食が取り寄せられて、話のネタになった
- 懇親会も無い想定もあったので良かった
- LTってやっぱ盛り上がるね
- 集客難しい
- 懇親会っていつも話せない
  - (みんな同意)
  - 昼休みと乾杯前くらい
- 意外と仕事がなく、スタッフらしいことはそんなしてない
  - そもそも仕事がない
- 慣れてない勢を誘導するなにか
- 一言発表って忘れてしまう
  - 1枚資料書いてもらうと良いんじゃない？
  - mokumoku会の各自書いてもらうやつをとりあえずで残しておく
    - 人数が多いとごちゃごちゃにならない？
      - なにか良いものが出るまでの仮運用
    - SlackにLT前に書く？
      - 時間が経つと見返せない...

## nonacho
- 初参加の身として、いろいろ発表が見れたり、会の雰囲気が掴めてよかった
- 初ハッカソンの身として、何すれば分からなかったけどアイデアソンがあってよかった
- 会場が良き
- 昼食に困る気がしてたけど、詳しい人先頭に団体で行けてよかった
- 会場まで難しくて大阪が怖い！
- Web系の人が多く、もっといろんな分野の人に来てほしい！
  - 学生も意外と多い
- 主催...どうするかはさておき、次もやっていきたい

## 人少ない問題
- oniipon「他のハッカソンの手伝いしてても思う」
  - 「アイデアソンは意外とくるんだけどね」
  - 「学生に限定すると人が来たりする」
    - dousen「名古屋もそう」
  - kiridaruma「エンジニアも多い、オタクも多い、でもその組み合わせは...」
    - 「情シス的な人は多いんだろうけども、『ハック』って好きなんか？」
  - oniipon「けっきょく地道に宣伝ですかね」
  
## これからの大阪
- oniipon「大阪でもLT大会したい！」
  - 「時期が来たらやる...よ」

## まとめ
- kiridaruma「配信も集客もすぐに解決案は出ないな」
- 「これを気に関西アイマスエンジニア勢を盛り上げよう」
- oniipon・kiridaruma「mokumoku会...アクセス...」

## 収支報告
- oniipon「飲食はうちが持ちます(スポンサー)」
  - 「参加費分は絵を書いてもらったアナゴPへ」
  - 「使わなかった備品類はメモをシェアします」
    - 「前回分(うろうP)に追加でゴミ袋・お手拭きくらい」
