### ISSUE TITLE
アイマスハッカソン2019関東の振り返り

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#145]
# 概要

https://github.com/imas/hackathon/issues/140 の振り返り
https://imas.connpass.com/event/151789/
いつもどおりKPT形式で進めます。

|                | 出席者 | 申込者 | キャンセル |
| -------------- | ------ | ------ | ---------- |
| 合計           | 21人   | 23人   | 6人        |
| プロデューサー | 14人   | 16人   | 6人        |
| スタッフ       | 7人    | 7人    | 0人        |

# テンプレ

```
# Keep

- 

# Problem

- 

# Try

-

```

**Comment by katao** [comment]
# Keep

- 同時開催
- 同時開催で企業のLTがLVに届く
- 参加率が高い 19/24(79%)
- 何も言わなくてもLT資料が各自上げてくれる。

# Problem

- 配信関係協力できなかった
- TLワチャワチャした
- アンケート送るのが遅い(打ち上げ後だと深夜になる)
- スタッフが少ないと会場の原状復帰に時間がかかる。

# Try

- TL事前に時間や接続の確認をする
- アンケートはslackのリマインドを仕込むor締めの挨拶前に送って、挨拶でアナウンスしてもらう。
- 会場の原状復帰に協力or早期退出のお願いをする

**Comment by YutaGoto** [comment]
# Keep

- 同時開催 :clap:
- LTの募集の方法は良かった :octocat: https://github.com/imas/hackathon/issues/142
- 参加者全員がそれなりに成果が出せてよかった
- 資料やブログが自発的に上がってきて分来がとてもよい

# Problem

- 12月ということもあり、イベントが重なった。
- 12月ということもあり、会社さんの会場探しも難しそうであった。
- LTのタイムキープできずにすみません。。
- 同時開催ということもあり、参加者がどうしてもどちらかの会場に偏ってしまう
  - SPARQLに詳しい人がほぼ関西も含める
- 来年もアイマスですよ！アイマス〜！をやり忘れた

# Try

- 例年12月にやっているけど、そもそも12月じゃなくてもよいのでは。。

**Comment by subroh0508** [comment]
会場の監督者だったのでこっそり書きます_φ(･_･

## Keep
- 同時開催 🎉 
  - 関東も例年と比べ少なめだったので、同時開催の意義がより出た感じがする
- 参加者が会場に収まってよかった
  - 初めて20人以上呼んだが、致命的な破綻はなかった気がする
  - 会議室x4を集中部屋x3、モブプロできる部屋x1でイイ感じに使ってもらえた？
- ランチの案内マップ用意できた
- 感想ブログ書いてくれた人がそこそこいて嬉しい

## Problem
- ランチの案内マップ、土曜定休の場所も含めてしまい迷子を発生させてしまった(ごめんなさい)
- 配信関連をもう少し念入りに打ち合わせできるとよかった
  - リモート商談で使っている有線回線が実はあったりしたので…
- 初めての方とあまり会話できなかった
- SPARQL有識者偏る問題
  - きりだるまさんが4月から東京なので、少し改善される…？
  - 同時開催なのでオンライン相談コーナーとかできたらよいかもしれない(もくもく会のLV参加方式を参考に)

## Try
- 初めての方には最初の方から積極的にアタックしてくよう心がけたい
- 終了後アンケートで会場についてどうだったか(アクセスや設備、等身大パネルの飾り付け等)を集計できると会場スポンサー的にはめちゃありがたい
- 週刊IM@Studyの執筆支援コーナーを入れたい！

**Comment by hamup8** [comment]
# Keep
- 同時開催🎉
- 名札🎉
- 枠の増減があったり（当日キャンセルなど）して読みづらいところがあったが、ある程度妥当な量の注文ができて良かった。（飲み物系は多少余ったけどこれは仕方ないと思う...持って帰ってもらったりしたので結果全部消費できた）

# Problem
- アイマスみあるお酒をあまりアピールできなかった。（皆飲んでくれたのでちゃんとはけたが...。）
- カードで前払いしたと勘違いしているものがあった。実は現金払いだった...ごっちさんにご迷惑おかけました...:bow:
- 初めての人とあんまりコミュニケーション取れなかった。

# Try
- 初参加の方とは歓談の時間等を使って積極的にコミュニケーション取る。
- ごっちさんの言う通り12月はイベント立て込みがち...状況によっては12月に絞らずもっと広い期間ターゲットにおいてもいいかもしれません。
