### ISSUE TITLE
IM@S ENGINEERS ON@IR!!!! 2020

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#160]
書くだけ書くスタイル

# 草案

- 日時
  - 2020/09 or 2020/10 の土曜日 日中(昨年と同様)
- 場所
  - 発表者P: Discord画面共有?
  - 聴衆者P: YouTubeLiveを見る?
- セッション枠: 確保する？
- LT枠
  - LTだけでもよさそうな気がする

**Comment by crssnky** [comment]
Google Meet
- 2020/5/1～2020/9/30で無償化
- 連続時間:24時間
- 同時接続:100人

**Comment by YutaGoto** [comment]
Meetつよい。。

Meet 最大100人同時接続はいろいろつらそうなので、発表者と進行以外はYoutube視聴がよさそうな気がします。
無償化の期間を考えると9月中にやってしまったほうがよさそうです。

**Comment by crssnky** [comment]
ふと思いついたのが、この前のSideMやミリオンのライブ予定日生放送の形式。
基本的には、司会者・発表者・配信者の3名のみを部屋に入れて、発表者を順次入れ替える形式。
観客は全員配信を見て、チャットやTwitterのテキスト形式で反応することで、発表しない人とも差が無くなるのかなと思います。ボイスで反応できる人がいると、テキスト側は不利なので積極的に反応しにくい(主観)と思ってます。
ただ、司会者の技量が試されますね…

**Comment by crssnky** [comment]
UE4公式の勉強会とかでは、質疑応答ツールにこれが使われてます
https://www.sli.do/jp

**Comment by YutaGoto** [comment]
# 概要

- 日時
  - 2020/09/26(土曜日) 13:00 - 18:00(仮)
- 場所
  - 発表者P: GoogleMeets
    - 20分枠: 最大3人
    - 5分枠: それなり
  - 聴衆者P: YouTubeLiveで見る



## イベントタイムテーブル(仮)

| 時刻  | 内容               |      |
| ----- | ------------------ | ---- |
| 13:00 | はじまり、OPトーク |      |
| 13:20 | 20分枠1            |      |
| 13:40 | 質疑応答           |      |
| 13:50 | 20分枠2            |      |
| 14:10 | 質疑応答           |      |
| 14:20 | 20分枠3            |      |
| 14:40 | 質疑応答           |      |
| 14:50 | 休憩               |      |
| 15:10 | 5分枠 * 18人?      |      |
| 17:40 | クロージングトーク |      |

## 発表者P

Connpassで募る？

発表内容や希望枠(5分 or 20分)を予め運営に共有しておく

## 視聴者P

Connpassに申し込まなくてもいい

基本Twitterハッシュタグ `#imastudy` で盛り上げる

配信(音が小さいなど)についてはSlackでフィードバックをもらう?

質疑は `sli.do`を使う?

## 配信

YouTube Liveを使いたい

**Meetの画面共有 -> OBSとかのソフト -> YouTube**

`#imastudy` のツイート内容を配信に載せられたらもりあがっている感が出せそう

## 運営のしごと

- 司会進行
- 配信
- 発表者対応
- タイムキーパー

**Comment by subroh0508** [comment]
参考になるかわからないですが、土曜日開催の↓のオンラインLTイベントは発表者をDiscordチャンネルに集める + 当日の発表を4ブロックに分けて、ブロック開始前に対象者集めておく方式とってます。

当日は(方法はわからないものの)視聴者の質問も受け付けるみたいなので、上手くやっていたら参考になる気がします 🤔 

https://twipla.jp/events/447758

**Comment by subroh0508** [comment]
ハッシュタグツイートを拾う形式だと、Comment Screenが圧倒的優秀ソフトです(ニコマス感出て良い気がする？)

https://commentscreen.jp/

**Comment by subroh0508** [comment]
参考: cluster使った勉強会

- cluster内コメントとTwitterハッシュタグを流す機能あり
   - YouTubeに流す時はカメラから外せば、「clusterにいる人だけ」見える状態にもできる
- 光る棒！！！

https://www.youtube.com/watch?reload=9&v=nPtMBXDqDaA&feature=youtu.be

clusterは画面共有ができない(PDFをアップロードするしかない)のがちょっとつらいかも

画面共有できるclusterっぽいVR系サービスだと、MozillaのHubsとか

https://hubs.mozilla.com/#/

**Comment by YutaGoto** [comment]
いままでのイベントも含めて場の雰囲気あってこそイベントがいい感じになっていたと思っています。
光る棒含めて聴取者はいろいろエモートして雰囲気盛り上げたほうがいいような気がしてきたので、近々clusterを触ってみる。。
