### ISSUE TITLE
IM@S ENGINEERS ON@IR!!!! 2020 振り返り

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#164]
# 概要

#160 の振り返りです。
https://imas.connpass.com/event/186165/

# テンプレ

```md
## Keep

- 

## Problem

- 

## Try

- 

```

**Comment by YutaGoto** [comment]
## Keep

- 大きなトラブルもなく進めることができた。
- 会場が劇場
- cluster内ではオフラインに似た発表の反応が見られてよかった。
- オンラインでの発表では堂々とサブディスプレイに発表原稿を置きながら発表ができるのがよかった（発表者目線） 
- 本編の前にエモートの練習があったのはよかった。
- youtube liveカメラ係おつかれさまでした！

## Problem

- マイクの音量チェックがわりとむずかしい。
- clusterでの視聴がもうちょっといてほしかった。
- LT応募が少な目だった。。

## Try

- 話す人がそれぞれ他の人に聞こえているかどうかの確認が必要そう。
- オフライン用、オンライン用の運用ノウハウをまとめていったほうがよさそう。

**Comment by subroh0508** [comment]
もう一週間経ってしまった…＞＜

## Keep

- 配信機材や登壇者の発表環境に起因する大きなトラブルなく終われてよかった
  - 急遽早坂さん(=YouTube Live配信係)になったけど、意外となんとかなった
  - ラップトップ2台 + 安定した回線があればどうにかなる
- てづくりのげきじょう！ @crssnky さんに多大なる感謝 🙏 
  - 突発の劇場ツアーできてよかった
- 劇場内でサイリウム振ってもらえるのとてもよい(登壇者は実質アイドル 😎 )
- バーチャル肉体が増えた
- SpatialChatの懇談会も3グループぐらいに分散できてイイ感じだった気がする
  - 二次会のシャニマスコミュ鑑賞会で死んだ 😇 

## Problem

- 配信担当事前にきっかり決めておくべきだった(午前中割と焦ってた)
- エモートの効果音が少し大きかったとの声あり
- エモートやYouTube Liveのコメントが拾えなくて一方通行になりがちだった
  - 運営と登壇の二刀流しているとなかなかつらい
- 懇親会、初めての方のフォローができなかった
  - 対応してくださった方々ありがとうございました 🙏 

## Try

- (次回もオンラインなら)配信ノウハウの引き継ぎをしっかりやる
- 進行役の人が適宜コメントを拾えると双方向性が増してよさそう
- ハッカソンのノリで初めてのLTを支援する時間を取ったりすると、新しい人のLTを増やせるかも…？
  - オンラインLT、喋る人固定されがちな印象なので意識的に組み込む意味がオフライン以上にありそう
- アバター作成講座したい
  - 劇場をアイドルちゃんで埋めたい！！！
- ハッカソンもオンラインでできそうならやってみたい 👀

**Comment by treby** [comment]
[ブログはこちら](https://treby.hatenablog.com/entry/2020/09/27/170000)

## Keep

- 祝・オンライン開催。みなさまありがとうございますmm
- 近未来感出ていて良かった
- Cluster、ガヤ感出せて良かった
- 初参加の方にきてもらえて良かった(発表・懇親会)
- タイムスケジュール上もほぼばっちり
    - cromisaさんのステージ内覧会ができたのは良かった

## Problem

- ガヤSEの音量が声をうわがいていたらしい？
    - 配信みてケアしてあげられるとよかったのかな
- 途中から旗振りを私の方でやってしまう形になってしまった……

## Try

- オンラインやる際は音声品質について気にして上げられると良さそうです。
- LT応募を増やしたり(一本釣りやリハ会などで)、SNSを盛り上げたり(全体アナウンスで告知したり、言及を拾ったり)する工夫はできそうですね。

**Comment by crssnky** [comment]
副業がすごい感じになってしまったので遅くなりました。

## Keep
- 初オンライン
  - 実は参加登録してない人も劇場に来場してた
- 手づくりの~武道館~劇場～♪
-ファイル形式に制限はあれど、現実と変わらないイベント
- 懇親会も、突発LTとかもできて自由度が高い
  - 別グループをチラッと聞きにいけるのは現実よりも容易

## Problem
- 自環境では発表と撮影を両立できないことが直前に分かってしまった
  - 早坂さん(@subroh0508 )に感謝します:bow:
- 会場作りに夢中で、資料作りが雑になってしまった
- 会場参加者全員に勝手にゲスト権限付与してたけど、スタッフ+αくらいしか話してなかった

## Try
- 会場のクオリティアップ
- 来場者を増やす
- LT参加者を増やす

**Comment by hamaco** [comment]
忘れてた！

## Keep

- オンラインで無事開催！
- 劇場での開催！
- 意外と懇親会はよい感じにバラけてた気がする
  - その場に静かにしていててもあんまり気にならないので個人的にはやりやすかったかも
  - お酒零したりとか掃除とかそういうのないのも気楽で良いね

## Problem

- オンラインで地理的な問題なくなったわりには参加者少なかったのかなーって
- 顔が見えないからどういう感じかいまいち分からず話しづらさある
  - ぐだってしまったので慣れとかが必要そう
- 移動がめんどくさいのでClusterワープ機能欲しい…w
- YouTube Live がどうだったのか殆ど見れてない

## Try

- 参加者（登壇者）もうちょっと増やしたかったなー
- もうちょっとオンライン開催に慣れていきたい気持ち
