### ISSUE TITLE
アイマスハッカソン 2020 ONLINE

### ISSUE THREAD

**Issue by subroh0508** [imas/hackathon#165]
たててしまった

**Comment by subroh0508** [comment]
時期: 12月後半説

**Comment by subroh0508** [comment]
### スケジュール感
- キックオフ、10月29日〜11月8日
- commpassページ、1ヶ月前公開(11月15日〜25日くらい)

### 会場
- ハッカソン: Spatial Chat or Discord
- LT会: cluster
  - 無理に移動せず、ハッカソン会場のままでもよい？
- 懇親会: Spatial Chat or Discord

### 必要なモノ
- 作業用BGM

**Comment by crssnky** [comment]
キックオフ議事録
https://docs.google.com/document/d/1apZSAtVYcQhA7h_jO1mY9LNkQQzdFtHJBrZuF5I1GWI/edit?usp=sharing
