### ISSUE TITLE
アイマスハッカソン 2020 ONLINE 振り返り

### ISSUE THREAD

**Issue by oniipon** [imas/hackathon#166]
アイマスハッカソン 2020 ONLINE

#165 のふりかえり

テンプレ
```
## Keep

- 

## Problem

- 

## Try

- 
```

**Comment by oniipon** [comment]
https://miro.com/app/board/o9J_kgHORyI=/

アイデアソンで使った何か

**Comment by oniipon** [comment]
## Keep
- １か月前ぐらいに1stMTGしたけどなんとか開催出来たよかった
- オンラインだといつもより作業時間めっちゃ取れるし朝ギリギリまで寝れる素敵
- 配信周りでぐだる事がほぼ無かった(39 cromisaSAN)
- Miroでアイデアソンすると後で参照出来てべんり
- 自己紹介ボードでの自己紹介簡略化

## Problem
- NeWorkやっぱりまだver1になってない事もあり結構不安定なとこ多い
 - 今後に期待したい所存
 - 次やるならDiscordとかの別アプリ使ってみてもいいかも
 - [こんなの](https://www.gamespark.jp/article/2020/05/06/98849.html) もあったり（映像共有が出来ないという発表時の致命的な問題もありますが）
- アイデアソンがグダらない知見欲しい
- オンラインだとコミュニケーション難しい

## Try
- いつも以上にコミュニケーション難しいので初めましての人向けのフォローを頑張りたい所存

**Comment by crssnky** [comment]
## Keep
- EngineerT@lk onlineから続けて開催できて良き
- スタッフ数が少なくてもなんとかなるのはオンラインの良さ
- Miroが残るので、アイデアソンの結果がうやむやにならない
  - 次回開催でも、`> 続きから`ができる


## Problem
- やはりオンラインはコミュニケーションが取りにくい
  - 未だに出社勢としては勝手が分からない...
- 発表者と配信者は、やはり兼ねることはできない
  - 配信では、自分の音声が乗っていなかった(ウィンドウキャプチャなので)
  - あとで気付いたのはOBS側でマイクを拾えば良かったということ  
→そうなると、ボイスチャットはできなくなる...?
- 全員に一言発表をしてもらうのを忘れた

## Try
- オンライン時の進行テンプレートが確立されると良いな
  - こればっかりは開催を繰り返すしかない
- 自己紹介、GitHubのhackathonリポジトリに残してもらう？
  - 我々も更新してないでしょ

**Comment by YutaGoto** [comment]
みなさまおつかれさまでした

## Keep

- オンラインなので朝比較的ゆっくりできる
- オンラインなので忘れ物がない！
- DJぴにゃ枠よき。
- 大型のもくもく会感。
- ハッシュタグ実況はそれなり。
- youtubeの視聴者数もそれなり？

## Problem

- ハッカソン中のコミュニケーションはどうしてもムズカシイところがある。。
  - 雑談が生まれにくい。。
  - imasparqlの質問とかはあったのかな。。？

## Try

- DJぴにゃを毎月のもくもく会に招待したい。
- 配信マニュアル()

**Comment by subroh0508** [comment]
拙い旗振りでしたが、ありがとうございました…！

## Keep
- 1ヶ月前の急な準備でもそこまで慌てることなく開催できた
  - 会場確保や飲食費の精算が発生しないのお手軽
- オンライン、一切の移動がないのやっぱりよいですね
- 当日のドタキャンゼロだった気がする
- 急遽DJぴにゃを召喚したけど割と好評だった
  - アイディアソンの後、あまりにも無音だったので…
- アイディアソンがいつも以上に場のアイスブレイクになっていた気がする
- NeWorkのオフライン感、すごくよかったと思う
- LT発表者めっちゃいて嬉しかった 🥰
- 懇親会だけ参加がオフラインよりもしやすかった説(みかみんさんしかいなかったけど)

## Problem
- 1人マイク周りが最後まで解決できなかった方が出てしまった
  - 交流会の時間だけでもSpatialChatやDiscordに流す準備をしてもよかったかも
- NeWork、テキストチャットが欲しい
  - LT会中もスペースとチャットが一体になっていたらもう少しコメントが盛り上がったのでは…？
- croMisaさん(配信者)のLTがサイレントになってしまった
- ハッカソン中やっぱり静か
  - ほぼ全員カメラOFFだったので、NeWorkの良さを活かしきれなかったようにも思う
  - 関東はオフラインでも静かなので、アイディアソンと交流会で話せればこのままでもよい説
- 司会進行不慣れすぎて一言成果発表を飛ばしてしまった
  - 他にも色々飛ばしてる気がしていて不安

## Try
- DJぴにゃ音質向上委員会
- 次回同じフォーマットでやるならDiscordを試してみたい

**Comment by subroh0508** [comment]
### 振り返りMTGで出た話

- アイマス感の不足、名刺交換とかグッズ並べたりとかCD配ったりとか
  - エンジニア抜きのアイマス(ライブ会場？)感がない
- LT発表中、ガヤOKであればちゃんと伝えた方が良さそう
- ハッシュタグを司会で告知する
- Discord、BGM用botが作れるってよ 👀
