### ISSUE TITLE
自己発信の場について

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#19]
> Issueの目的

1. 自己紹介の方法について役割・指針を定める

2. 自己紹介の告知・誘導の仕組み化(一般化)

3. 運用について 仕様が定まる

> このIssueのClose条件

- 目的(1)～(3)を満たす事

>  自己発信の場を設ける目的

- 新しく参加される方々が、既にある輪に自然に参入し易いようにする

> 既にあるアプローチ

1. GitHub - producers配下へ自己紹介ファイルをpull requestする

- Wiki  - プロデューサ自己紹介について (https://github.com/imas/hackathon/wiki/%E3%83%97%E3%83%AD%E3%83%87%E3%83%A5%E3%83%BC%E3%82%B5%E3%83%BC%E8%87%AA%E5%B7%B1%E7%B4%B9%E4%BB%8B%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

- 役割・指針
(Slackに登録していないけれど検討されている方に)外から見える情報を提供する
ハッカソン当日に参加者のバックグラウンド情報へアクセスしやすいようにまとめておく

- メリット
自己紹介によるコントリビュート体験が可能
リポジトリをWatchしていれば、Pull Requestが来た際に見逃さずに済む(新しい自己紹介を見逃さない)
マージボタンを押す楽しみ

- デメリット
fork/cloneしPull Request、margeまでの手間が多少かかる
GitHubアカウント必須

- 補足
Wikiに書くのもありかもしれないという意見があった

2.  Slack - #self-introductionチャネルに自己紹介を書き込む

- 役割・指針
他チャンネルの会話を割り切って自己発信するのは気が引けるので、ラフに自己発信出来る場を提供する
自己発信したあと、気軽に他チャンネルへ会話参入出来るように
カジュアルな自己紹介によって、Slack上での会話のきっかけを生む

- メリット
Slackにさえ参加すれば、前の人に倣い自己紹介をフリーに投げれる
Reactionによって気軽に自己紹介文に対してメンション出来る
フランクにやることでコミュニケーションが発生しやすい

- デメリット
まず自己紹介をいきなり投稿して良いものか迷ってしまうかもしれない
過去の自己紹介は流れていく
一定のテンプレートが無いため、人によっては書きにくいかもしれない

- アプローチ
自己紹介は一定量溜まったらどこかにログとして残す？
自己紹介を書きやすいように、Slack新規参加時Slack-Botなどでガイドメンションを飛ばす？

>  さらなるアプローチ案

- Scrapboxの利用 
 (https://scrapbox.io/product)

**Comment by kaibasira** [comment]
自分なりに現在の状況まとめてみました
Slackでの議論も残しておきたい、等あったので
planning直下か、planning/self_introductionなど設けて
上記をベースにindexを設け、ログ残し等やっていきたい等思っていますがどうでしょう？

後纏め方などマサカリ飛ばしてくださいm(__)m

**Comment by treby** [comment]
ありがとうございます！

Issueの目的としては、(課題意識としての)仕組みとしてもっと仲良くなれると良いよねから始まり、(その解決法としての)自己紹介があり、解決法の具体的なやり方について決めているという認識です :)という話を先日 @hamaco さんとしていて、じゃあPull Requestにしてみまっかーとか言いながらちゃんと運用していないすみませんmmm

自己紹介が重複していることについてですが

- Pull Request：(Slackに登録していないけれど検討されている方に)外から見える情報を提供する
- Slack：フランクにやることでコミュニケーションが発生しやすい

という住み分けがあるのかな、と考えています。

このあたりはきちんと指針はあったほうが良いと思っているので、仕組み化してふんわり告知・誘導していければと(そもそも私がPull Request送っていない問題ｗ)

ドキュメンテーション(Wiki)についてはきっと @gomao9 さんが書いてくださるはず……！

**Comment by hsugita** [comment]
背景は置いておいて、現在の運用を眺めていると、

-  `producers/`配下へのプルリク
    - コントリビューション体験
    - ハッカソン当日に参加者のバックグラウンド情報へアクセスしやすいようにまとめておく
- `#self-introduction`チャンネル
  - カジュアルな自己紹介
  - Slack上での会話のきっかけ

という役割を果たしてるかなと思いました。

**Comment by hsugita** [comment]
> ドキュメンテーション(Wiki)についてはきっと @hsugita さんが書いてくださるはず……！

どうまとめたらいいかイメージがふんわりしてるけど頑張る〜

**Comment by kaibasira** [comment]
@treby さんのコメントを受け、Issueの目的とClose条件を改めて加筆しました！
意識が違っていたら教えてください！

また役割・指針については@trebyさん、@hsugitaさんの頂いたコメントから抜粋し加筆しました。
(コメントの修正履歴って残らないんですね...... Slackのログを残したい件もあるので、やっぱりコメント.md何処かに残させてくださいm(_ _)m)

現時点で気になったのは、

- バックグラウンドへのアクセスはプルリク限定とするのか？(GitHub以外の選択肢は無し？GitHub必須？)

という事と、後は

- 告知・誘導についての手法

でしょうか。
特にSlackだと#self-introductionで会話が発生してタイミングを失う場合もあると思うので、
何か有効な誘導手法は無いかと考えています。
こちらから声をかけていくのもありかもしれないですが......何か案ありませんでしょうか？

**Comment by treby** [comment]
[IMHO] GitHubは登録していただいて良いかな、と！

告知誘導は、イベント登録されている方向けに打てれば良いのかなと個人的にはおもてます。自己紹介しなければならないとするよりは、自己紹介したいと思っている方が躊躇してしまう材料をなるべく少なくしたいなぁという所存っす。

もちろん、話しやすいように心遣いできるのは素敵なことだと思います:)

**Comment by kaibasira** [comment]
GitHubへの登録のきっかけにもなる、というステップがあるみたいな感じですね
自分も、そういった機会があるのは素敵だと思うので、先の自分の疑問に関しては、プルリク限定とする　との結論でfixしましょうか

自己紹介の意識については@trebyさんと同意見です。
なんだか自分の纏め方がmustな方向へと動いちゃってましたね...スミマセン

すると運用についても現状ではもう定まってきているような感じかもですね　後は
> 自己紹介したいと思っている方が躊躇してしまう材料

について潰せていけたら、というような感じでしょうか

**Comment by treby** [comment]
👍

**Comment by treby** [comment]
Slackの `#self-introduction` channelのdescriptionに入れて、closeします
