### ISSUE TITLE
2/25 アイマスエンジニアMeetup in OSAKA

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#35]
## テーマ
- アイマスエンジニア Meetup!! in OSAKA
## 目的
- 関東だけじゃなくて関西にもアイマスエンジニアは居るはずだ！いや、居るんだ！だから同僚の皆で集まってみようぜ！
- アイマスエンジニアなれど普段から何もやってねーし何かきっかけ欲しいわ.....あ、Meetupあるんや？行こ
- みたいなラフさを目指し、まずはアイマスエンジニアの輪を関西で作ってみることを目指す
### 日時
- 2月25日(土)
- 16:00～19:00 (3時間)
### 場所
- 株式会社ユニクエスト・オンライン様 4F
- URL(http://www.uqo.jp/)
  - 大阪府大阪市西区靱本町1-6-3 
  - 地下鉄御堂筋線「本町」駅　徒歩5分
  - 地下鉄四ツ橋線「肥後橋」駅　徒歩7分
  - 地下鉄御堂筋線「淀屋橋」駅　徒歩9分
### 目標参加人数
- 15人
### 参加費
- 500円
## 暫定的なタイムテーブル

| 時刻 | 内容 | 
| :-: | --- |
| 14:30 | 会場入り・準備開始 (スタッフ) |
| 15:30 | 受付開始 | 
| 16:00 | オープニング/挨拶・ユニクエスト・オンライン様会社案内 |
| 16:15 | 自己紹介 ( １人2～3分程度) |
| 17:00 | アイディアソン開始 |
| 17:50 | アイディアソンシェア・ラフディスカッション |
| 18:00 | 懇親会 / 愛を叫ぶLT |
| 19:00 | クロージング |
| ～20:00 | 片付け・原状復帰後完全撤収 | 
- 自己紹介の加減で時間前後は考えられる。自己紹介時刻が早まれば懇親会の時間を増やす
- 一番最後集合写真撮ろうぜ

**Comment by kaibasira** [comment]
## 会場情報
### 確認事項
- **スリッパ必須**
  - 予備のスリッパ、簡単な下駄箱等あったほうがよさげ
- 電源 - 割と無い
  - Task - 自分の手持ちの電源タップを確認、会場お貸し頂ける人と相談 ( 電源元までちょっと遠い)
  - 長めの延長タップが必要か？(10m以上のもの)
- Wi-fi環境 - OK
- プロジェクター - OK
  - HDMI、VGA
- 音響 - OK
  - ミキサまであるので今回は機材全く必要なし
- 机は移動可能
- 飲食物持ち込み可能
  - 宅配等を行う場合は直接会場の4Fに届けてもらい受け取れる
  - 同会場にある自動販売機は使用不可っぽい？　最終確認する
- ポスターなどの飾り付け - OK
- 会場への行き方
  - Task - 別途作成必要あり 但しビル自体がユニクエスト・オンライン様のもので看板もあるのでわかりやすい
  - 案内板等も置いて良い＆簡単な立て看板借りれるのでビル内で迷うことはなさそう
- 会場内での写真撮影等 - OK
- コール - 騒ぎすぎない程度にOK 
- ゴミ袋は別途自分たちで用意して、帰りは直接ゴミ捨て場に捨てに行く
### TODO
- [ ] 手持ちの電源タップor当日用意できそうなタップ確認 (～2/3)
- [ ] connpassの案内にスリッパ必須である旨記述する (connpassページ作成時)
- [ ] 会場への行き方ページを作る (～2/15)
- [ ] 自動販売機の使用可否確認 ( ～当日)
- [ ] ゴミ袋の用意 (当日)
- [ ] 予備のスリッパ、(できれば簡易靴箱)の用意 (当日)

**Comment by kaibasira** [comment]
## イベント内容情報
### 当日の企画内容
- アイディアソンの流れについて
  - グループごとに何かテーマがあったほうがやりやすいかな？
  - しかしジャンルも年齢層も違う中、アイマスという共通カテゴリだけをというのもあり
  - ぼでーは一応全グループに様子を見てちょっかいをかけにいく
  - (アイディアソンの発想はごまおさんとの相談の中で生まれました Thanks !!)
- 懇親会について
  - 食べ物、飲み物　何にしよう？　やっぱりピザかな？
  - アイディアソン中にラフにつまむものとして各テーブルに駄菓子などあっても良さげ
  - Task - コップ、お皿、お手拭き、必要なアイテムを確認する
  - Task - 食べ物手配の段取りを考えておく
- 愛を叫ぶLT
  - 完全に担当アイドルの布教活動の場を提供する
  - 懇親会として立食しながらサイリウム振ってツッコミ入れてもらうのもありなのでは？
  - 懇親会のためのテーブル移動は参加者に手伝ってもらおう
### 当日までの企画・宣伝・告知
- 今回会場で流す曲のリクエストを試験的にTwitter・Slackで募集してみる
  - Twitterは#imas_hack　Slackは#requestチャンネルを作ろうかな
  - (このアイディアはゆたさんから頂きました。Thanks !!)
- 今回会場で飾り付けたいポスター等を試験的に募集してみる
  - こちらは直接リプを頂く方が良いのかも #imas_hackで持って行きます宣言してもらうのもアリ
- ニコ生配信は今回は無し
- ちひろさんカンパBOXを作る
  - 懇親会の食費に主に充てさせて頂く......
  - お金の流れが分かるように収支表を作る
  - Want - お金管理する人が欲しい......
- カメラマンが欲しい
  - 思い当たる人脈にアタック中　最悪まぁ普通にやってる途中にスマホで撮れば良いか
  - Task - 一応カメラNGな人を確認する
### ノベルティ
- アナゴP(https://twitter.com/anagoP_ims) に依頼　今回はA4のクリアファイル
  - ～2/8 入稿案提出頂く・随時修正等依頼
  - ～2/10 最終決定案入稿、2/14までの製造可能連絡を想定
  - ～2/14 製造可能連絡取れ次第connpassページやTwitterでもデザイン等を宣伝
  - ～2/22(遅くても) ぼでー宅に商品到着・現物による宣伝
- ごまおニキ(https://twitter.com/gomao9) がクローゼットP(https://twitter.com/closetz) に依頼したロゴステッカーを今回も配布

**Comment by kaibasira** [comment]
## ぼでーTask
- [ ] 会場の確約
- [ ] Issue立てる
- [ ] connpassでの告知内容草案を#planningにて相談 ( ～2/3)
- [ ] connpassにて告知 ( ～2/5)
- [ ] スタッフをもう2人ぐらい引っ張ってくる (～2/18)
- [ ] しっかり栄養を取って筋トレして寝てツッコミ力を上げていく

**Comment by adachi-tsukasa** [comment]
@kaibasira 
>カメラマンが欲しい
>思い当たる人脈にアタック中　最悪まぁ普通にやってる途中にスマホで撮れば良いか

カメラできますよー。アタックだめだったらお声がけくださいまし。

**Comment by kaibasira** [comment]
@adachi-tsukasa 
うおー！こうなったらもうお願いしたい所存......
このままお願いしてもよろしいでごぜーますか？

**Comment by klcatha** [comment]
### 悲報
> ニコ生配信は今回は無し

**Comment by adachi-tsukasa** [comment]
@kaibasira 
おっけーです！
他に人手不足なところあれば、ぶち込んじゃってください！

**Comment by kaibasira** [comment]
@klcatha 
ハッカソンほどハッキリとしたResultが大量に無いので微妙かなぁ、と
LTがたくさん集まれば会場の雰囲気を...というので配信はありかもしれませんが...

@adachi-tsukasa 
ありがとうございます！
そしたら食べ物の手配等(恐らく宅配ピザになると思われるので受取など)もついでにお願いしたい所...！

**Comment by treby** [comment]
受付開始はいつごろされる予定ですか？

**Comment by kaibasira** [comment]
@treby 
当日の受付であれば15:30開始の予定です！

**Comment by treby** [comment]
すみません、伝え方が拙かったです。connpassは使わない感じ？
あと私も雑用手伝えますよ:)

**Comment by kaibasira** [comment]
@treby 
connpass告知・受付行います！遅くても2/5までには！
なんと...それはありがたい。。。
それじゃあ受付とかお願いしようかしら

**Comment by klcatha** [comment]
@kaibasira 
ただ愛を叫ぶLTを個人的に見たかっただけなので無くて全然いいっすよ
slackで東京から盛り上げますよ！

**Comment by kaibasira** [comment]
## 食事通話MTG
- Agenda (※ぼでーが思ってる事を並べただけ)

### 参加者
- ぼでー
- もめん

### 目的
- Meetup当日の飲食物の決定
- 飲食物の手配の方法をやんわり決定する

### 飲食物をどうするか
- 飲み物
  - 受付開始の時点から最後のクロージングの時点まで提供するのが良いのではないか
  - ペットボトル等をテーブル毎に置き、適当に回してもらうイメージ
  - 2L単位で提供、提供分の控えは別テーブルで置いておき、なくなれば誰かもしくはスタッフが補填
  - 何本ぐらいしようか？ (募集してから当日何人集まりそうかを見てからでも良さげ)
  - 買い出しはいついこうか？
  - お酒はどうする？ (懇親会の時に人によってはあったほうがいいかもしれないね)
- 食べ物
  - ポテチ・チョコレートなどのアソートは最初から机にあってもよさそう (ラフさを提供できるかも...？)
  - 一応補填分は用意しておくが、基本的に机にある分でいいのではないか？ (思ったよりみんな食べないのでは？
  - どんなものを？ (手が汚れない物が良さそうだな 小分けされてるもの...... カントリーマアムとか)
- 懇親会の食事はやっぱりピザ？
  - 宅配可能なので一番濃厚
  - 宅配のタイミング？
- アイディアソンシェアから懇親会開始までの段取り
  - 立食形式を目指したいので、参加者に椅子はのけてもらう
  - 食事を机に並べるのはスタッフ(もめんさん中心に)がやる
  - 乾杯の音頭を取ってスタートの明確化
  - 机こそ分かれているが、立ち歩いたりなどでラフに交流してもらう
  - LTを並行するのでそこら辺どうするか

**Comment by crssnky** [comment]
参加表明させていただきました〜。
来週から春休み入るので、ちょっと面倒な雑務もできる範囲でお手伝いできます！

**Comment by kaibasira** [comment]
@crssnky 
うおー！ありがとうございますありがとうございます......
何かお手伝い頂きたい事があれば、ご厚意に甘えてご連絡さしあげますね！

**Comment by kaibasira** [comment]
2/19 (開催6日前)に参加者向けに打った案内の内容)
```
	アイマスエンジニアMeetup in OSAKA当日について

こんばんは！

この度は『アイマスエンジニアMeetup in OSAKA』にご参加登録いただきありがとうございます！
あっという間に当日まで1週間を切ってしまいました。時間が経つ早さを感じてしまいます……
と、それはさておき、当日の注意点について、事前にいくつかご案内させていただきます！

◎当日会場の持ち物について

当日会場は”スリッパ必須！”となっております。
お手数ですが出来る限りスリッパをご持参頂くようご協力をお願いしますm(__)m　　
また当日、会場設営・懇親会等の実費として500円の参加費用のお支払をお願いいたします。

サイリウム、UO、などなど光る棒が当日あっても盛り上がるかもしれません！
P名刺をお持ちの方はP名刺も持ってきちゃってくだせー！

また、当日ささやかな飾り付け等を行っております！
ポスターやフィギュア等、会場に飾って自慢してやんよ！って方は是非是非ご持参ください！

◎LTについて

参加アンケートでLTご参加希望の方を何人か頂いています！
当日は予告どおり１人あたり7分程度でのLTを想定しております！
また、当日スライド等を使用するためのプロジェクターの用意がありますので、ご使用の方は当日お申し付けください！
(接続端子はHDMI,VGAとなっております)

LTのタイトルについては、決まり次第ぼでー(@bode_mmk : https://twitter.com/bode_mmk)にメンションを飛ばして頂けるとありがたいです！
自分の担当アイドルへの愛を思い思いに叫んじゃってください！
(もちろんタイトルは当日発表でもOKです！)

◎IM@Studyのコミュニティへの参加

主催グループであるIM@StudyとしてSlackを立てております！
是非気楽にご参加ください！

https://imas-hack.herokuapp.com/

また、企画内容や経緯等はオープンにgithubで共有しております。
https://github.com/imas/hackathon

自己紹介のページを集約する試みもやっておりますので、githubアカウントをお持ちの方は以下を参考に是非ご登録ください。
https://github.com/imas/hackathon/wiki/%E3%83%97%E3%83%AD%E3%83%87%E3%83%A5%E3%83%BC%E3%82%B5%E3%83%BC%E8%87%AA%E5%B7%B1%E7%B4%B9%E4%BB%8B%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

◎最後に……

最後になりましたが、参加登録本当にありがとうございます！
主催の私も初の試みですので運営・進行等、拙い点があるかもしれません……
しかし、当日は精一杯皆様に楽しんでもらえるよう尽力いたしますので、何卒よろしくお願いします！

ご不明な点などございましたら、お気軽にご相談ください！
当日、皆様とお会い出来ることを楽しみにしております！
```

**Comment by kaibasira** [comment]
2/26(開催後1日後)に送った内容
```
	アイマスエンジニアMeetup in OSAKAにご参加いただきありがとうございました！

この度は
「アイマスエンジニアMeetup in OSAKA」にご参加頂き誠にありがとうございました！

今回参加率100%として誰一人欠席になること無く当日ご参加頂けたこと、本当に感謝と感動しかありません！
遠方からいらした方々も、お近くの方々も、ありがとうございました！

さて、終了後ですがご協力頂きたい事が１つ……
今回のイベントに関してアンケートを実施しております。次回イベント開催への参考にしたいと思いますのでご協力の方お願いいたします！
https://goo.gl/forms/R7Qfw3jPwVVVgQTy1

アイディアソンで得られた知見、当日アイマスエンジニア同士の交流で見出した可能性、
皆様の今後の”アイマスへの貢献(Contribute)”のきっかけとして頂ければ幸いでございます！

これに懲りず、またアイマスエンジニア向けのイベントを開催していきたいと思っておりますので、機会があればよろしくお願いします！

```

**Comment by kaibasira** [comment]
振り返りを立てたのでこちらはCloseします
