### ISSUE TITLE
第2回会議に向けてやること

### ISSUE THREAD

**Issue by hsugita** [imas/hackathon#4]
第2回会議に向けてやっておくべきことをまとめておきます。

### Close条件
* [ ] 第2回企画会議で話す内容がまとまっている
* [ ] 会議で諸々決めるために必要な情報が揃っている
  * 各自のスケジュールとかアイマス公式のスケジュールとか
* [ ] 会議のアジェンダ的なものができている(Markdownのテキストを想定)
  * このissueそのものがアジェンダでもいいかも

### タスクリスト
* 決めること
  * [ ] ハッカソン会場に必要な条件を固める #5 
  * [ ] 第2回企画会議日程・会場を決める #6
  * [ ] ハッカソン日程を決めるために必要な材料を準備しておく
  * [ ] 当日必要なもの
  * [ ] 当日のスケジュールを決める
  * [ ] 告知・参加募集の段取りをする
* やりたいこと、懸念など
  * [ ] ロゴ・ステッカーつくる #7
  * [ ] 絵師さんを巻き込む #8 
  * [ ] 等身大POPを会場に置く
  * [ ] 765AS・シンデレラ・SideM方面のPへのアピール
  * [ ] LT配信したい
  * [ ] 非エンジニアが端から見ていて楽しそうなイベントにしたい
  * [ ] 会場をアイマス空間にしたい
  * [ ] 参加者の意識合わせをしておきたい（みんなが楽しめるように）

**Comment by hsugita** [comment]
> 会議のアジェンダ的なものができている(Markdownのテキストを想定)

わざわざ作らなくても、このissueをアジェンダにすればそれで事足りるような気もします。
第2回会議後にはひとつのドキュメントとしてまとまっていたほうがいいと思うけども。

**Comment by hsugita** [comment]
@treby @hamaco 
気が向いたらでいいですが、「タスクリスト」の中から1つでも2つでも良いので選んでissue立ててくださると助かります。(1人で全部issue立てるのはしんどいことが分かった)

**Comment by treby** [comment]
旗振りありがとうございます！個人的には最初からすべてをissue化する必要ないと思っています。
そもそも、全てが全て分量があるとは思っておらず、ものによっては決めの問題のところもあるかもしれません。

例えば、決めることリストの必要なものやスケジュールは @hsugita さんがバシッと決めちゃって、それらの叩き台の上で詰めていった方が建設的になるかな、と思っています:) 
逆に材料の準備や告知の段取りなど、ごまおさんお一人で厳しいところがありましたら、それぞれ噛み砕いた上でタスクを振るのは全然ありだと思います。

と、私は思うのですが、いかがでしょうか @hsugita @hamaco

**Comment by hsugita** [comment]
@treby 自分でも若干大げさすぎる感はしてるので、まずは私の頭のなかにあることを全部書きだしてから、検討すべきものだけissue化のほうが良さそうですね。

**Comment by hamaco** [comment]
やりたいことの方はほんわかしまくってるからとりあえず Issue にしちゃっといてもいいと思いますが、決めることの方はまあ @treby さんの言う通りでいいかなーって。

**Comment by hsugita** [comment]
@hamaco さんの意見も受けて、決めることは私の方でまとめてから皆さんに投げる形、
やりたいことのほうはissue化して具体的な形にしてからやりたい人の担当タスクにする形にするのがいいかなと思いました。

**Comment by hsugita** [comment]
必要なことは #9 に書いてWikiにもまとめましたのでこちらは閉じます。
