### ISSUE TITLE
dots.グループのコミュニティ名を決める

### ISSUE THREAD

**Issue by pastelInc** [imas/hackathon#40]
**目的**

勉強会イベントの情報集約サイト[dots.](https://eventdots.jp/)上にイベントを掲載してより広く取り組みを知ってもらいたい!
dots.上にイベントを掲載するとカレンダーや開催場所から検索することができます。

**やるべきこと**

dots.の上にはグループと言うものがありコミュニティを登録します。
グループはイベントをdots.上に掲載できるのでconnpassで作成したイベントをそのグループでdots.上に掲載します。
グループの登録にはグループ名とURLの末尾が必要ですが名前をあとで変更できるかわからないため
皆さんの意見を広く募ろうと思います!

<img width="777" alt="2017-02-21 19 28 22" src="https://cloud.githubusercontent.com/assets/5408269/23163037/362dc1d0-f874-11e6-96d6-9f419a89ccdd.png">

**期限**

特に決めていません
[2/25のイベント](https://imas.connpass.com/event/50353/)がまだ空いているので宣伝効果を高めるためにも間に合えば間に合わせたいです

**Comment by pastelInc** [comment]
現在の候補はconnpassに合わせるという案があります

**グループ名**
IM@Study

**グループURL**
imas

他にいい名前やこれがいいというものは積極的に教えてください!!
ちなみにdots.のグループ一覧は[こちら](https://eventdots.jp/community)から参照できます

**Comment by treby** [comment]
ありがとうございます。
名前については、 https://github.com/imas/hackathon/issues/40#issuecomment-281318294 ++です(そもそも私が横槍を入れたのでしたね、、、)。

元々、dotsに掲載できないかなというところから始まったと記憶していますが、dotsにコミュニティ作ることは、こちらもメンテをしていく必要があるという感じでしょうか。

dotsはconnpassと立ち位置が被っているので、作った後にちゃんと運用回るかな、というところが心配です。（個人的にあまりdotsを利用していないというのが大きいかもしれません；結構ご覧になられるものなのでしょうか）

どなたかに回していただける、あるいは自動で回る仕組みであれば安心です :)

**Comment by gomao9** [comment]
issueの趣旨と外れてしまうのですが、trebyさんのコメントを見て思ったことを書いておきます。

今回の話は、下記のような流れと思います。

1. dotsはconnpassのイベントを（自動で？）収集して掲載してる
2. 今回の大阪ミートアップは掲載されていない
3. 掲載依頼できるみたいだから依頼してみよう
4. dots運営「自分でコミュニティを作って登録してね」
5. じゃあコミュニティを作ろう

その流れでdotのサイトの説明を読んでみましたが、下記の疑問が生まれました。

- dotコミュニティを作って、イベント掲載するとき、
  - conpassのイベントへの誘導ページとして作成できるのか？
  - dotsのイベントとして新しく作成することしかできないのか？

前者なら手間はあまりかからないと思いますが、もし後者の場合、connpassとdotsで二重管理になって大変そうだなーと感じます。
（文面を読んだ限りでは後者のような気がしました）

**Comment by pastelInc** [comment]
確かにdotsはconnpass上で収集したイベントに対しては誘導してくれていますが、どうやらグループを作成してイベントを公開するとconnpassとは別に管理しないといけないようですね 😭 
(グループ一覧からそれぞれのグループが公開しているイベントページを見てみました)

もともとdots.上でconnpassから自動でイベントが収集されていないことが問題だと思い。
Slack上で頂いたメッセージをもとに[よくある質問](https://eventdots.jp/faq)の*イベントを掲載してほしい*に従って問い合わせを行いました。
そしてその際の回答が以下のとおりです。

```txt
いつもご利用ありがとうございます。 dots.運営事務局です。
この度は、イベント登録についてお問い合わせ頂きありがとうございます。

下記エントリーページよりコミュニティを作成頂けますと、
dots.サイト上にイベント掲載が可能となりました。
是非ご登録頂き、今後ご活用頂けますと幸いでございます。

　「 https://eventdots.jp/community_entry 」
※利用料は無料です。
※利用規約にもございます通り、イベント内容によっては掲載が
できないものもございます。ご了承くださいませ。
※システムの仕様上、同コミュニティ名で複数登録することが出来兼ねます。
既にご登録がある場合は名称をご変更ください。

ご不明点あればお気軽にお問い合わせくださいませ。
今後とも何卒、宜しくお願いいたします。
```

よくある質問にも書かれていますがどうやらこれはこちらの期待に沿っていただけなかったようです

>※掲載においては、イベント内容がテクノロジーに関連しているかどうかが基準となります。
※申込ページが使用API（ATND/connpass/Doorkeeper）で取得できないページの場合、別途ご相談が必要となります。
※いただいたご要望にお応えできないこともありますのでご了承ください。

私がdots.利用でATND/connpass/Doorkeeperをまたいでイベントを見つけていたので、掲載したいと思い
言い出したのですが、これは @treby @gomao9 のお二人がおっしゃっているように管理上の問題からグループの作成はやめておいたほうが良さそうですね。

そしてdots.にも掲載してくれないということであれば掲載は諦めたほうが良さそうです。

[アイマスハッカソン振り返り 170107 - dots.［ドッツ］](https://eventdots.jp/event/609434)

こちらのイベントがdots.に掲載されているので何をもとに収集しているのかダメ元で再度問い合わせをしてみようと思います。その結果いかんによってcloseするか決めようと思います 😢

**Comment by kaibasira** [comment]
私個人もdotsを利用したことが無く、あくまで触りだけ理解した意見で言ってしまうのですが

> connpassとは別に管理しないといけない

が濃厚なのであれば、現時点では無理してdotsコミュニティを作成する必要もないように思えてきました。
今回の大阪Meetupの為にコミュティ作成を依頼した私が言うのも非常に申し訳ないのですが、
一旦見送り、別issueとして(あるいはこのissueにoverrideする形で)
- dots. グループの作成
として、運用方法など少し練ってからコミュティを作る形でも良いように思います。

もちろんconnpassでのイベントを自動で収集出来る目処が立てば一番良いのですが、
我々の活動とイベントの特性上

> ※掲載においては、イベント内容がテクノロジーに関連しているかどうかが基準となります。

というのに抵触すると判断されかねないので、自動での収集に100%期待するのは少ししんどいと思います。

私個人としては、イベントを広く知ってもらいたい・広く展開したい　というのがありますので、
dots.でコミュティを作成する事で、今後dots. にもイベントを掲載できる可能性があるのならば、コミュニティ作成には賛成です。

**Comment by Shinogasa** [comment]
私はほぼdots.でTech系イベントの情報を見つけております．
dots.見る -> 面白そうなイベント見つける -> ATND/connpass/Doorkeeperに飛んで参加登録
という流れで使用していますのでdots.に掲載していただけるとありがたいです．
キーワード検索だけでなくタグ付けもあって結構いろいろな人の目につくのではないかとも思います．
個人的にATNDやconnpassは検索がいまいちなのでイベントが見つけにくいなーと．

dots.のコミュニティがどんな感じなのかは使ってみないとわからないと思うので，
とりあえず作ってみるのもありなのではないでしょうか．
他のコミュニティをちょっと見た感じイベントの告知だけしかしていないコミュニティもあるので，
connpasssで作成したイベントを乗っける程度の運用ならそこまで手間にはならないのかなと．



名前は現状の
> グループ名
> IM@Study
> 
> グループURL
> imas

で良いのではないかと思いますが，
個人的にはハッシュタグの imas_hack が好きなので iM@S Hack もいいなあとか思ってます．

**Comment by adachi-tsukasa** [comment]
> 個人的にATNDやconnpassは検索がいまいちなのでイベントが見つけにくいなーと．

そうなんですよね、前までは使っていたんですが如何せん、使いにくくて😢 

二番煎じ感ありますがこれを機に乗り換える、二重管理する等々考えても良いかもしれませんね。
ただそういった決定タスクは大事だと思うので、今週末に間に合わせるよう急ぐ必要はないかと。

**Comment by pastelInc** [comment]
dots運営からの回答をいただきました
dotsへの掲載方法がわかりましたので共有しておきます

>お問い合わせ頂きました件についてですが、
外部サイト（ATND/connpass/Doorkeeper/Peatix）から取得したイベントの
掲載基準は、原則、「テクノロジーに関連する内容かどうか」となっております。
基本的には、運営するコミュニティに依るのではなく、イベントページ単体での掲載判断を
おこなっているため、本文から「テクノロジー関連のイベントである」と容易に
推測できないイベントに関しましては、掲載不可となる場合もございます。
（例外として、競合他社様が運営するイベントに関してはこの限りではありません。）
また、掲載可否のフィルタリングは、システムと運営事務局の目で二重におこなっておりますが、
確認のタイミングや状況によっては想定外に掲載されてしまう場合もございます。
「掲載されていること」「掲載されていないこと」の違和感を感じることがありましたら、
ぜひ、ご一報いただけますと幸いでございます。
＜補足＞
「システム的なフィルタリング」は、dots.が登録している「タグ」に合致するキーワードが
イベントページ本文に含まれているかどうか、が基本となります。
このため、別サイトに詳細を記載している場合などは、掲載不可となる確率が高くなります。

よくよく見直してみるとconnpassのページに技術的なワードがあまり盛り込まれて内容に見受けられます。
まずはconnpassのページを編集してdots運営が管理しているタグ情報に引っかかるようにワードを盛り込んでみてはどうでしょうか。

**Comment by treby** [comment]
なるほど、ありがとうございます。

> まずはconnpassのページを編集してdots運営が管理しているタグ情報に引っかかるよう

エンジニアの勉強会を標榜しているのにそれらしい技術の中身がないというのは結構私自身も感じていたことですｗ一方で懇親会などでみなさんと話した感覚として、特定の技術に寄らないようにってのはなんとなくあるんですよね。

これは個人の意見ですが、たまたまエンジニアという副業をしていた人が集まって、新たな刺激を受けるところが面白いのかなと考えています。

私自身は普段Webエンジニアとして特にアプリケーションから上を担当にしていますが、ミドルウェアから下の方の話や、アプリの話、さらにそのくくりに限定されない話が聞けるのはアイマスという枠があってからのことかなと思っています。そして、何の話が聞けるかはその時々の参加者の方によるという……

現状はdotsさんの意向に無理に合わせるというよりは、テーマとして適切であれば盛り込んで行く形が自然かなぁと考えます。例えばアイマスの中でもbot特集とかやるならそのタグを盛り込むことになるでしょうし、Webサービス特集をやるなら具体的なフレームワーク名が入ることになるイメージです。

**Comment by treby** [comment]
これからやるイベントにもよりますが、[先般のイベント](https://eventdots.jp/event/619171) のように内容によってはdots側で捕捉してもらえることも分かったので、こちらはcloseで良いかなと考えています。いかがでしょうか？ @pastelInc

**Comment by pastelInc** [comment]
@treby dotsに掲載はおまかせしてもうアクションはいらないみたいですね。
closeします。ご協力いただいた皆様ありがとうございました :bow:
