### ISSUE TITLE
アイマスエンジニアMeetup in OSAKAの振り返り

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#42]
### 目的
- [アイマスエンジニアMeetup in OSAKA](https://imas.connpass.com/event/50353/)の開催について振り返る

### 対象メンバー
- (主催) @kaibasira
- @adachi-tsukasa 
- @treby 
- @gomao9 

### 手法
- KPT形式でまとめてください
  - Keep
  - Problem
  - TRY

### Reference
- https://github.com/imas/hackathon/issues/35

**Comment by kaibasira** [comment]
# Keep
- 「きっかけを提供する場」としてのラフさは出せたのではないか
  - アイディアソンとしてならば敷居が低いし、しかしながら知見が全く無いかといえばそうでもなさそう
  - 結果的に良いバランスで場を提供することが出来たのではないか？
  - 愛をぶつけ合う場、を提供できてハッカソンとはまた違う雰囲気を作り出すことが出来た
  - 今回は「アイドルを愛でる」を主体にした愛を叫ぶLTをしてもらえたように思えた
- 会場はおしゃれで綺麗だった　という感想が多く受けられた
  - 今後も継続して付き合っていけそうなのでまた次回も使わせてもらえるかもしれない
- 出席率１００％なのがなにげに嬉しかった
  - 主催者としては感無量です
- ノベルティ好評だった
  - アナゴPに感謝しかありません、本当にありがとうございました
- 主催として、参加者全員と絡む事が出来て良かった

# Problem
- まず関西で純関西勢スタッフを募る事が出来なかった (当たった人脈は全て日程合わず、ぼでーの人脈の限界)
  - 人の伝手等は@trebyさん等をもう少し頼っても良かったかもしれない
  - 圧倒的人手不足 @adachi-tsukasa さんに頼り過ぎ はむPさんをあたかもコアスタッフのように働かせてしまった
  - BGMコントロールと司会兼は明らかに頭おかしい
- 会場への行き方ページ作る詐欺
  - 行き方ページがあれば迷う人も居なかったかもしれない 次回は必ず作る
- マイクと音楽のMixing ( マイク or BGMの択一になってしまった )
  - 事前の会場での確認できちんと音出しして確認しておくべきだった
- アイディアソンの運び
  - やはり765/ミリオン島の人数を分けても良かった感じがある (一つの島3～4人ぐらいが妥当か？)
  - アイディアを出すための”きっかけ”は運営側でもう少し具体的に練って決めても良かったかもしれない
  - アイディアを纏めてもらう為のツール（ホワイトボードetc会場から借りた ) の用意
- LTのスライド主催者が作ってないなんてありえないよね
  - 本当に申し訳ない　ネタとして捉えてもらっていたが、今回本当に自分で反省している
- 飲食物もう少し多くても良かったかな？
  - みんな以外につまむ
- 今回のイベントの宣伝について
  - Twitterでの宣伝とかを皆に頼りすぎた感 (RTとかで楽させてもらってました。本当に申し訳ない)
  - dots. 等は最初から気を配れたので宣伝方について誰かに相談すればよかった
- ちひろさんカンパBOXの宣伝、アンケートの宣伝、Slackのチャンネル作成、カメラのNG等……細かいところを忘れていたりした
- 色々と余裕が無かったりした(ノベルティや事前のメッセージ送信など)
  - スタッフを募れなかったのもあるが、タスクをさばききれない場合は皆にカバーしてもらえる所はもう少し皆に頼っても良かった

# TRY
- 次回は生放送もやってみよう
- スタッフを頑張って募ろう
- アイディアソン→ハッカソンの一連の流れを組んでも良いかもしれない
- 宣伝にもう少し力を入れよう
- アイディアソンなら違う視点が入るのも面白いので絵師さんやSS書きさんにゲストとして来てもらうのもありかもしれない

**Comment by treby** [comment]
お疲れ様でした！

# Keep

- アイデアソンというイベント形式
  - この発想は私からは出てこなかった、のですごいと思います

# Problem

- (私の話として)もう少し、会自体に参加しても良かったかも
- 会をやること自体のハードルが上がった、今後どうしていくのか
  - という話は @gomao9 さんと飲みながら(正確には付き合ってもらいながら)してた。模索しながらですかねーというところに落ち着いた

# Try

- 気張らず、でもケジメつけながらやっていけると良いですね！
- せっかくなんで、参加された方に各々の感想をここに書いてもらってもよいのでは？

**Comment by hsugita** [comment]
> * せっかくなんで、参加された方に各々の感想をここに書いてもらってもよいのでは？

今回はそれほど大人数でもないので、皆さんに書いてもらっても良いと思います:+1:

**Comment by adachi-tsukasa** [comment]
# Keep
- IM@S Studyとして2回目、かつ関西で開催できたこと！
  - 12月の1回きりではないことの証明ができた
  - 大阪を皮切りに色んな場所で開催できる可能性が広がった
  - ぼでーさん良かったね！
- 良い盛り上がり方ができた
  - 1回目のニコ生配信、レポを見て雰囲気を掴んできてくださった方の期待を裏切らないミートアップになった
- 会場が良い
  - 広さ、設備、雰囲気ともに素敵でした  
- ノベルティ、ちひろさんBOXが最高
  - 前々からノベルティ、BOXのデザイン等は拝見していましたが、予想以上のクオリティでした！
  - クリエイターのお二人に感謝！
- エンジニア以外の方が居て良かった、エンジニア以外の目線があって良かった
  - エンジニア以外の目線って貴重だなと感じました 二次創作系のアイディアとかも出たので成果に影響を与えたはず

# Problem
- 人手不足だった
  - 参加人数とスタッフ数はある一定までは比例しない
  - はむさんに設営、買い出しの荷物持ち等々頼ってしまった
  - 音響兼設営であと1人欲しいところ
- 飲み物・お菓子をサーブするタイミングを見計らいにくかった
  - 気づいたらなくなってることが多かった
- お菓子のバリエーションが少なかった
  - ある程度具体的にどんなものを買うべきか決めておくべきだった
  - もも、ミックスナッツ、ドーナツ等々案外ネタに気づかれにくかった気がします
- 手にベタつく系食べ物出るのに、テーブル毎に拭くものがない
  - 大きいペーパー、ウェットティッシュ買ってそのままは良くない テーブル毎に置くべきだった
- イベント開始後にも関わらず備品が使用できる状態でないものがあった
  - 設営時に使用できるよう用意すべき　長船さんにウエットティッシュを開けてもらいました…すいません…
- 宣伝不足
  - イベントの旗振りしてから開催まで時間が短かったが故、宣伝にも手が回らなかったのかと思います
- 食事係なのに財布にあんまり入ってない（自分の問題）
  - 飲み物・お菓子・ピザ代ぐらい全て建て替えられる財布を用意すべきだった


# TRY
- 関西、関東同時開催！（いつかやってみたいです）
- 動画配信 生を見てもらうことでコミュニティの雰囲気も掴みやすいはず

**Comment by kaibasira** [comment]
> せっかくなんで、参加された方に各々の感想をここに書いてもらってもよいのでは？

そうしましょうか！
KPTでなくとも自由な感想を書く場として案内してみましょうか

**Comment by crssnky** [comment]
crssnkyあらためcroMisaです。お邪魔させていただきます。

# Keep
- アイデアソン
 - 初対面なので喋ることで人を覚えられる
 - みなさんの感覚,考え方,アイデアが知れる(Slackでもあんまり話せてない(?))
 - 歳も歴も関係ない"同僚"感があった
 - 別分野枠(今回ならアナゴP)
- LT
 - 勉強あり、笑いあり、ｷｭﾝｯ♥あり
 - なんだかんだ愛をContributeしていたLT

# Problem
- 実は事務所で分ける必要はない？
 - なんだかんだそこまで事務所の深い所のものは出てない
- ~~カラー名刺が切れた~~

# Try
- 外へ向けた成果発表(アイデアの掲示)
- 参加を促せるhackチームではなく、ハッカソン,アイデアソンの広告

**Comment by syoun** [comment]
# Keep

* アイデアソン
 * ハッカソンより敷居が低く、気軽に参加しやすかった
 * 実際に作るとなると出てこない・出てきても除外せざるを得なさそうな発想も自由に出せた
  * ゲーム系のアイデア（権利的に流石にやばそう）など
 * エンジニア以外の参加
 * 会場がおしゃれ
* LT
 * 愛が伝わった
 * 技術的な部分も興味深かった

# Problem

* 違うチームの方とあまり交流できなかった
 * LT前か後に少し歓談的な時間があってもよかったかもなと
* 会場がおしゃれ
 * コールとか入れて大丈夫…？みたいな謎の気後れ（問題という程ではないです）

# Try
* 宣伝

**Comment by hamup8** [comment]
お疲れ様でした！はむです。

# Keep
・アイデアソンという形式だったので皆さんとの会話・交流を多く取れた
・自分とは違う考え方、アプローチ、アイデアを知れた
・自分の考え×その他Pさんの考え→より面白いアイデア になったと思う
・別分野の視点があったのが良い(今回はアナゴP)
・担当の愛を叫ぶLTが最高だった、もっと見たい(?)
・会場がおしゃれ！
・ノベルティが素晴らしかった！
・受付や司会進行がスムーズだった
・カンパBoxなど小ネタにガチるところが素晴らしかった

# Problem
・事務所ごとに分けなくても良かったかも？
・他チームメンバーとの交流が少なかった
・担当アイドルが分かるものを余り身につけていなかった(自分の問題)
・LT資料を当日に作ってバタバタしてしまった(自分の問題)

# Try
・アイデアを実際にプロダクトとして形にする
・宣伝(関西勢の参加が少なかったので、入念な広告・宣伝が必要？)
・ニコ生配信(会場の雰囲気感を外に伝えるのは大事？まだ参加していない方のきっかけづくり)

**Comment by treby** [comment]
@kaibasira 
これはどこかで振り返りの機会設けますか？一回閉じる？

**Comment by kaibasira** [comment]
考えましたが、一度閉じます！すみません！
