### ISSUE TITLE
イベントをやる際の役割分担ガイドライン案

### ISSUE THREAD

**Issue by treby** [imas/hackathon#44]
# これはなに

`#imas_hack` を継続可能なコミュニティとするために、どういう役割分担があるとやりやすそうかをまとめます。今後何かイベントをやろうとした際に、ある程度のガイドラインがあると混乱がなくなるかな、と考えています。

[2月のアイデアソン](https://imas.connpass.com/event/50353/) でいえばぼでーさん、 [5月のLT大会](https://imas.connpass.com/event/54949/) でいえばごまおさん発案、のように基本は好きな人が好きなようにやれば良いのではと考えています。が、(私含め)みんなそんなにノウハウがないので、収拾がつかなくなるリスクと隣り合わせです。

会の収拾がつかなくなると対外的にみた時に混乱を招いちゃう(結果、 `#imas_hack` が継続可能なコミュニティにならない → アイマスにContributeできない) ことになります。それは不幸だよね、ということで書き出すだけ書き出しておきます。補足や意見など、フィードバック歓迎です。

## 準備

- 企画(何やるか決めたりいつやるか決めたり)
  - 日時・場所・人
- 財務
  - お金周り(カンパ周り)。余剰金はプールして分配する
  - 宵越しの金は持たねぇスタイルでやってきてたけど、何かやろうとする人にだけ負担が行き過ぎるのを(多少)緩和する
  - 飲食物にあてたり、ノベルティとかコミュニティのためのインフラ費用の補助にあてる

## 当日

ざっくり以下あたり(やるやら含め)あれば何とかなるのではないだろうか。

- 受付担当 …… 名札、設定していれば参加費。カンパ箱番。
- 司会担当 …… 司会
- (配信担当) …… いれば。生放送配信
- (懇親会担当) …… 飲食物手配
- (発表担当) …… 誘ってくるというのもあり

**Comment by treby** [comment]
@imas/staff 書いてみましたー。何かありましたらコメントください

**Comment by kaibasira** [comment]
> 準備

- 会場についての確認事項でこれは必須だろうな、というのを思いついたので挙げておきます
  - 電源 / 電源タップの必要・不必要
  - wi-fi情報
  - プロジェクターの有無
  - 飲食の可否 (適宜) - ゴミの処理
  - (BGMを流す場合) : 音響機器

**Comment by crssnky** [comment]
### 配信の手引き
IM@Studyの[Youtubeブランドアカウント](https://www.youtube.com/channel/UCqdwXGfv8G5ne-xbZFPZBUA/about)があるので、その配信方法を...
※2018.3 当時の方法なので、変更があった場合は編集してもらえると助かります

1. 自分のGoogleアカウントとIM@Studyのブランドアカウントを紐付ける(https://support.google.com/accounts/answer/7311601?hl=ja)
ブランドアカウントの管理人になるために、初回だけ行うやつ
ブランドアカウントの所有者(これは1人しかなれない)から、管理人(これは複数人可能)として招待してもらう
自分が招待されたor管理しているブランドアカウントは[こちら](https://myaccount.google.com/brandaccounts)で確認できる

2. 配信準備
Youtubeに入り、右上のアカウントアイコンからアカウントを切り替える
クリエイターツールのページへ進み、ライブストリーミングのイベントのページを開く
新しいイベントを作成する
タイトルや説明などを記述する
"共有する"に自分のTwitterアカウントなどを紐付けると開始と同時に発言してもらえる
https://twitter.com/croMisa/status/972397564619345921
種類は、Webカメラによる配信の場合はクイックを選択する(Hangouts on Airを利用)
「配信を開始」or「予定の作成」を押す(開始予定時刻による)

3. 配信
Hangouts on Airが起動し、カメラからの映像が映る
下に配信を開始するというボタンがあるので、これを押すとカメラの映像が配信される
それまではアカウントのカバーイラストが映る(イベント用のものがあれば差し替えよう)
画面左側には数種のツールバーがある
カメラによっては反転した映像が入力されることがある
配信開始前に、Handouts拡張機能(Chrome拡張とかではない)の「Hangouts Toolbox」を入れる
「Hangouts Toolbox」にはミラー機能があるので、有効化する

4. おまけ
YoutubeLiveは自動でアーカイブされる
「カード」機能はアンケだったりテロップだったり
「非公開」・「限定公開」設定でテスト配信すると良いかも

**Comment by treby** [comment]
2年経つし、こちらは閉じちゃっても大丈夫かな……
