### ISSUE TITLE
5/17 Meetup in Tokyo準備スレ

### ISSUE THREAD

**Issue by gomao9** [imas/hackathon#45]
5/17開催のMeetup準備情報をまとめていきます。
https://imas.connpass.com/event/54949/

**Comment by gomao9** [comment]
# タスクとか役割とか
## 前日まで
- 会場への行き方など案内メッセージ送る

## 当日
- 司会進行 gomao
- 発表タイムキーパー  
- 受付（配布物、カンパ管理）
- 配信 fusagiko
- 軽食飲み物用意 momen
- 懇親会モデレート(オプション)

**Comment by gomao9** [comment]
5/4(木) [LODGE](https://lodge.yahoo.co.jp/)にて打ち合わせします。
15:00開始。
出席者: gomao, treby, hamaco, momen

配信周りはfusagikoさんと別途個別に調整します。

**Comment by gomao9** [comment]
5/4(木) [LODGE](https://lodge.yahoo.co.jp/)にて打ち合わせします。
15:00開始。
出席者: gomao, treby, hamaco, momen

配信周りはfusagikoさんと別途個別に調整します。

**Comment by treby** [comment]
受付やります！

**Comment by treby** [comment]
[IMO]

- 参加人数はそれなりに増やしておいても良いと思う (45人くらいとか)
- 自己紹介は難しそうなので、交流する時間を設けることで補完したい
- 飲みながら聞きたい 🍻

**Comment by gomao9** [comment]
- 質疑の時間取りたい。やり方考える

**Comment by gomao9** [comment]
5/4打ち合わせのざっくりしたアウトライン的なもの

## 話したいこと
- 参加枠拡大
  - 5/2現在、30枠に対して42人申込み
  - キャパ的には50人ぐらいまで可能？
  - キャンセル率を読む
- 当日の流れ
  - 最初から飲む？
  - 交流時間をどこで取るか、交流の方法
  - 質疑応答の時間
- 会費の徴収
  - 軽食費用
  - 次回以降持越しプール金
  - カンパも含めて
- 参考
  - 12/17 ハッカソン準備情報集約スレ #5
  - アイマスハッカソン2016の振り返り #29
  - イベントをやる際の役割分担ガイドライン案 #44

## 役割・関連するタスク
- 司会進行 gomao
  - 全体の流れ
  - 会場について諸注意など
  - アイスブレーキングの方法
- 発表タイムキーパー
  - 発表順決める
  - 管理しやすいように一覧つくる
- 受付 treby
  - 配布物: ステッカー、クリアファイル
  - 参加費徴収・カンパ管理
  - 名札用意
- 配信 fusagiko
  - 配信媒体決める
  - (できるなら)枠を予約しておく
  - どこからどこまで配信する？(発表のみ or 交流している様子も含め、など)
- 軽食飲み物用意 momen
  - メニューは？
  - お酒・ソフトドリンク
- 懇親会アレンジ(オプション)
  - お店の当たりをつけとく
  - (必要なら)予約

**Comment by treby** [comment]
> 参加枠拡大
> 当日の流れ

まあ、参加したい人は参加できるくらいまでに広げて良いと思います。
その代わり自己紹介削って懇親会に回したり、質疑も後からとかにしておいた方が良いです。タイムコントロールがめちゃくちゃ難しくなるので。
飛び込みLTの余地を作りたかったら、予め発表者にリマインドしておくのも手です。でないと、本数もあるし極端に伸びる傾向になりそう。

> 会費の徴収

全員から取りたい場合は予めその意図(食事代にあてる)とか連絡したほうが良さげ。建物の下まで持ってきてもらうとかが良いかな……

**Comment by treby** [comment]
![img_20170510_122921](https://cloud.githubusercontent.com/assets/1079365/25882430/62a44436-357e-11e7-97fc-b5024cea7add.jpg)
![img_20170510_124218](https://cloud.githubusercontent.com/assets/1079365/25882438/6b64fe9e-357e-11e7-8730-6bc67653b52f.jpg)

**Comment by gomao9** [comment]
2017/05/10にConnpassで送ったメッセージ

```
こんにちは。
アイマスエンジニアMeetup in Tokyoの開催まで残すところ1週間となりました。
いくつかご案内がありますのでお知らせします。

- 参加枠について
- 自己紹介について
- 軽食の提供について
- カンパについて
- 会場への行き方

## 参加枠について
おかげさまで多数の参加申し込みを頂いているため、参加枠を30人から50人まで増枠いたしました。
05/10時点ですでに50人近いお申込みがあり、今後補欠枠が発生することも予想されます。
なるべく多くの方に参加いただくためにも、当日の都合がつかなくなった方は早めのキャンセルをお願いいたします。

## 自己紹介について
当初のタイムスケジュールでは自己紹介の時間を設ける予定でしたが、参加枠の拡大と開催時間を考慮し、自己紹介の時間は設けないことにしました。
代わりに懇親会の時間を長めに取る予定ですので、そちらでご交流を深めていただければと思います。
また、今回のミートアップに限りませんが、プロデューサー同士の交流が図れるよう、Slackグループも用意してございます。
事前にどんな人たちがいるのか、雰囲気を知っておきたい方、自己紹介をしておきたい方など、お気軽にご参加ください。
https://imas-hack.herokuapp.com/

## 軽食の提供について
懇親会にて、軽食と飲み物を提供する予定です。
アルコールとソフトドリンクのどちらもご用意する予定ですが、ソフトドリンクに関しましては十分な数がご用意できない可能性がございます。
ソフトドリンクを希望される方は、事前にご連絡くださいますと多めにご用意できるかもしれません。

## カンパについて
今回のミートアップでは会費は無料としておりますが、軽食・飲み物・ノベルティ類については運営スタッフの持ち出しにてまかなっております。
今後の安定したイベント運営のためにも、当日にカンパ頂けますと幸いです。

## 会場への行き方
会場となるクラウドワークス様があります、恵比寿ガーデンプレイスは少々分かりにくい立地となっています。
参考に、恵比寿駅からの行き方を案内した動画を貼っておきます。
https://www.youtube.com/watch?v=MPIj6qnrbCI

また、当日会場への行き方が分からなくなった場合には、Twitterの下記アカウント、もしくはimas-hackのSlackにてご連絡いただければご案内できると思います。
- @gomao9
- @momen_666
- @treby006
- @hamaco
- @fusagiko

それでは、当日お会いできますことを楽しみにしています。
```

**Comment by adachi-tsukasa** [comment]
## 飲み物・食べ物について
ミートアップ中に提供する飲み物・食べ物についてご確認いただきたく。
お金にまつわるところでもあるので、
ご確認いただいたらAddReaction/Commentしてもらえると安心します。

注文は前日でも間に合いそうですが、余裕をもって今日明日（〜5/14（日））を予定しています。

### 用意・提供時間
* 飲み物

開場時間30分前の18:30にカクヤスより6F、もしくはビル入口まで届けてもらおうと思っています。

会場後方に飲み物用の場所を用意し、参加者入場後、開催中は各自取りに来てもらう形をとります。
飲み物の場所には私が常駐し、可能であれば飲み物は手渡ししていこうと思っています。
ソフトドリンクはペットボトルのみの提供になるため、紙コップを合わせて提供します。

（19:30開始時には全員に飲み物が行き渡るよう、声掛け等あっても良いかもしれないです。）

* 食べ物

簡単なおつまみについてはカクヤスより飲み物とまとめて届けてもらいます。
開場前に各テーブルに適当数ばら撒いておきます。

ピザは20:30頃にドミノ・ピザ恵比寿店に取りにいきます。
歓談タイム開始21:00に各テーブルに1枚ずつ提供します。

* 流れ

**18:30** カクヤスより飲み物・簡単なおつまみ受け取り 後、会場後方に飲み物展開、おつまみ設置
**19:30** 乾杯
**20:30** ピザ屋にピザ回収に行く
**21:00** 各テーブルにピザ提供
**22:00** 片付け

### 注文予定の品々
**総計 31,919円**
#### 飲み物の部
From カクヤス

- アルコール（計78本 9,254円）
    - サントリー 金麦 350ml缶  350ML 2,767円/24本
    - サッポロ 麦とホップ The gold　350ML  2767円/24本
    - キリン 本搾り　グレープフルーツ 350ML 1270円/10本
    - キリン　氷結レモン 350ML 1270円/10本
    - サントリー ほろよい　もも 350ML 590円/5本
    - サントリー ほろよい 梅酒ソーダ350ML 590円/5本

- ソフトドリンク（計22本 4,031円）
    - コカコーラ 1.5L 1,544円/8本
    - サントリー なっちゃん オレンジ（果汁４０％）  1.5L 1,625円/8本
    - サントリー　烏龍茶  2L 862円/6本

 **飲み物合計 13,285円**

#### 食べ物の部
From カクヤス&ドミノ・ピザ

- おつまみ（5,674円）
    - 亀田製菓 亀田の柿の種 6袋詰 3,216円/12個
    - 亀田製菓 ハッピーターン  120G 2,448円/12個

- ピザ（計8枚 12,960円）
    - Lサイズ 12,960円/8枚

 **食べ物合計 18,634円**

**Comment by adachi-tsukasa** [comment]
### 懇親会候補地

1. [まる政 恵比寿店 （マルマサ） - 恵比寿/焼鳥 [食べログ]](https://tabelog.com/tokyo/A1303/A130302/13176349/)
席：43 LastOrder:26:00

2. [トリウオ 恵比寿店 （Toliuo） - 恵比寿/焼鳥 [食べログ]](https://tabelog.com/tokyo/A1303/A130302/13144856/)
席：カウンター:10 テーブル:16 LastOrder:25:00

3. [ワインの酒場。ディプント 恵比寿店 （Di PUNTO） - 恵比寿/ダイニングバー [食べログ]](https://tabelog.com/tokyo/A1303/A130302/13147313/) 
席：70 LastOrder:26:30

**Comment by takayamaki** [comment]
50人程度+スタッフにLサイズのピザ8枚だと微妙に足りないような気もしますがそこは懇親会でカヴァーでしょうかね？

**Comment by adachi-tsukasa** [comment]
@takayamaki そうですね、ピザはあくまで懇親会までのつなぎの要素が強いです。

**Comment by treby** [comment]
確認しました。ありがとうございます！残しておくと今後の参考になりそう。

食べ物

ピザもうちょっとあって良さそう。値段はドミノ・ピザの持ち帰りで2枚目半額織り込んでいますよね？
14枚で25kくらいなのでその温度感で。持ってくるのに台車とかあると捗りそうすね。きいてみよう。

理想はこんなもんらしい： https://sue445.github.io/pizza-beer/

<img width="473" alt="2017-05-14 20 52 49" src="https://cloud.githubusercontent.com/assets/1079365/26033441/7309f1f6-38e7-11e7-8b57-610d5e2e9009.png">

あと、つまみは甘いものあっても良いかも(おまかせで)。

飲み物

ボトル22本はちょっと多いかなーという印象ですがどうでしょう？勉強会からだしソフトドリンク派の人が多いのかな。まあ高いものでもないしある分には良いか。お酒交流会までに切れそうな気もしてるのでそのときは何か頑張りましょうｗ

とりあえず50kくらいは用意しておきます。
ってことは、次回からは一人1,000円くらいいただくようにするとバランスが良いかな。

**Comment by adachi-tsukasa** [comment]
@treby ご確認ありがとうございます！

ピザはおっしゃる通り、持ち込み割引考慮済みです。
折りたためる簡単な台車が手元にあるので、持っていこうと思ってました。

ちょっとソフトドリンク多めにして、感覚を確かめたい感あります。
今回の飲み物はこの個数でいきます！

>ピザもうちょっとあって良さそう。

>あと、つまみは甘いものあっても良いかも(おまかせで)。

この辺は正直予算だけがネックでした。
お金に関して甘えっぱなしで申し訳ないのですが、考慮いただけるのであれば…

 - ピザ
12,960円/8枚→（ざっくり）22,680円/14枚

- おつまみ
5,674円→8,500円〜9,500円
甘い系に関してはカクヤスでちょうど良いものがなかったので、
私が会場到着時までに適当に買ってきます。

- 総計
31,919円→43,500〜44,500円

とさせていただきたいです。

今回のようにビール＋つまみ＋ピザであれば、
1000円/人がぴったりで良いですね！

**Comment by treby** [comment]
領収書だけお願いします！

**Comment by adachi-tsukasa** [comment]
承知しました。それではこの内容で注文します！

**Comment by treby** [comment]
> 持ってくるのに台車とかあると捗りそうすね。きいてみよう。

ききました。
建物のレギュレーション上、飲食物は参加者持ち込みの体でないといけないので、建物内は台車運び込みNGと考えてください。それなので例えば、建物の下まで台車でそこから各位運び込みとかが良いかも。あくまでひっそり。

**Comment by treby** [comment]
カクヤスさんは公式OKなので、予め受け取ってもらうことも可能とのこと。
時間とか教えてもらえたら伝えておきます。宛先はクラウドワークス社の大場さん宛で

**Comment by adachi-tsukasa** [comment]
確認ありがとうございます。

> 建物の下まで台車でそこから各位運び込みとかが良いかも。あくまでひっそり。

ピザについてはこのやり方で考えてみます。
建物入り口まで持ち込んだら、助っ人（TODO:誰か決めておく）を呼んで複数人で会場まで運び込みます。

> 時間とか教えてもらえたら伝えておきます。宛先はクラウドワークス社の大場さん宛で

わかりました。18時半頃を予定していますが、確定次第もう一度お伝えします。

**Comment by adachi-tsukasa** [comment]
@treby カクヤスでもめんのカードが使えない問題…代引きは大丈夫ですか…
ドミノ・ピザは予約できました。

**Comment by treby** [comment]
@adachi-tsukasa はい

> 助っ人（TODO:誰か決めておく）

Slack の `#general` で募っておくとスムーズかも

**Comment by adachi-tsukasa** [comment]
@treby すみませぬ…注文完了しました。
時間指定は細かく設定できなかったので、17-18時の間に届くよう指定しています。

助っ人ははむPさん確保済みです。

**Comment by treby** [comment]
2人で大丈夫ですか？

**Comment by treby** [comment]
時間はお伝えしました

**Comment by adachi-tsukasa** [comment]
助っ人は多いに越したことないですかね、ちょっと募ってみます

**Comment by gomao9** [comment]
2017/05/16 にConnpassで送ったメッセージ
```
こんばんは。
アイマスエンジニアMeetup in Tokyoはいよいよ明日開催となります。
直前のお知らせをさせていただきます。

## 参加枠について
おかげさまで多数の参加申し込みを頂いており、すでにキャンセル待ちの方がいらっしゃいます。
なるべく多くの方に参加いただくためにも、都合がつかなくなった方は早めのキャンセルをお願いいたします。

## 会場への行き方（再掲）
会場となるクラウドワークス様があります、恵比寿ガーデンプレイスは少々分かりにくい立地となっています。
参考に、恵比寿駅からの行き方を案内した動画を貼っておきます。
https://www.youtube.com/watch?v=MPIj6qnrbCI

また、当日会場への行き方が分からなくなった場合には、Twitterの下記アカウント、もしくはimas-hackのSlackにてご連絡いただければご案内できると思います。

- @gomao9
- @momen_666
- @treby006
- @hamaco
- @fusagiko

## カンパについて（再掲）
今回のミートアップでは会費は無料としておりますが、軽食・飲み物・ノベルティ類については運営スタッフの持ち出しにてまかなっております。
今後の安定したイベント運営のためにも、当日にカンパ頂けますと幸いです。

## 映像配信について
事前のお知らせどおり、発表と会場の様子をニコニコ生放送で配信する予定です。
登壇者だけでなく、会場の様子を映す可能性もございますので、映り込みNGの方は、受付の際にその旨申し出ていただければと思います。

【中継】アイマスエンジニア MeetUp in Tokyo【 #imas_hack 】
http://live.nicovideo.jp/gate/lv298307428

## 当日のLT参加について
現在のスケジュールですと、発表時間にはまだ余裕がございます。
また、歓談タイムではごくゆるい感じのLT発表の時間を設ける予定です。
当日飛び込みでの参加も受け付けておりますので、事前準備なしでもカジュアルにトークしていただければと思います。

## 持ち物チェックリスト
最後に、下記のとおり持ち物チェックリストを作成しました。よろしければご活用ください。

- プロデューサー名刺(お持ちなら)
- サイリウム・ペンライト類(あると楽しいかも)
- アイドルを愛でる心


それでは、明日お会いできますことを楽しみにしています！
```

**Comment by treby** [comment]
## 今日の持ち物リスト

- gomao
  - ハッカソンシール
- hamaco
  - 名札ケース
- fusagiko
  - 配信道具一式
- momen
  - 紙コップとかお皿とか
  - おつまみ類
- treby
  - カンパ箱
  - クリアファイル

忘れたものとかあったら、可能な範囲で適当に調達していくんで教えてください

**Comment by treby** [comment]
イベントお疲れ様です。
振り返りは近いうち @gomao9 さんが企画するだろうこと見越しつつ取り急ぎ出納まとめておきます。

**支出の部**

お酒：18,869
お菓子： 3,173 + 1,004 = 4,177
ピザ13枚：22,680
(たぶん他にも)

計: 45,726円

**収入の部**

カンパ： 38,700
計: 38,700円

**Comment by treby** [comment]
- 参加登録者：51人
- 出席者：46人

大体90%の出席率

**Comment by takayamaki** [comment]
ニコ生中継のタイトルと説明文
> 【中継】アイマスエンジニア MeetUp in Tokyo【 #imas_hack 】
```
<b>アイドルを愛でる。アイマスに貢献<i>(Contribute)する。</i></b><br />
<font size="5">アイマスエンジニア MeetUp in Tokyo</font><br />
<br />
このイベントは、アイドルマスターのことを大好きなエンジニアを副業とするP達が、<br />
技術のこともそうでないこともひっくるめてアイマス、そしてアイドルへの思いの丈をお話する懇親会です。<br />
<br />
この生放送では、アイマスエンジニア MeetUp in Tokyoを最初から最後までまるっと生中継いたします！<br />
<br />
<br />
<font size="4">タイムテーブル</font><br />
19:30 開始・諸注意<br />
19:40 発表+質疑（順番は予定）<br />
　imas_cg集計(たくみP) 『シンデレラガールズ台詞判定の開発・運用・反響について』<br />
　megane42（津田沼P）『ロード画面が見たいだけの人生だった』<br />
　SARU『フレデリカがかわいいって話とARのお話（仮）』<br />
　takemikami『機械学習でのアイドル顔識別の話（仮）』<br />
　fusagiko『imastodon.netの話とメガネじゃないって話』<br />
21:00 歓談タイム・LT<br />
　gomao『ｱｲﾄﾞﾙ 宮尾美也』<br />
　hamaco『未定（仮）』<br />
<br />
アイマスエンジニア MeetUp in Tokyo<br />
https://imas.connpass.com/event/54949/<br />
<br />
github<br />
https://github.com/imas/hackathon
```

**Comment by adachi-tsukasa** [comment]
昨日はお疲れ様でした。

こちらも取り急ぎ…
飲み物・食べ物に関する支出ですが、trebyさんのご報告が全てとなります。
（領収書もtrebyさんに全て渡し済みです。）
また伝え漏れてしまいましたが、お菓子に計上されている¥1,004はお菓子ではなく、不足分の紙コップ、紙皿、ウェットティッシュ代になります。

**Comment by treby** [comment]
@adachi-tsukasa 更新しました！

**Comment by adachi-tsukasa** [comment]
@treby ありがとうございます！

**Comment by treby** [comment]
閉じますね
