### ISSUE TITLE
アイマスエンジニア Meetup in Tokyo 振り返り

### ISSUE THREAD

**Issue by gomao9** [imas/hackathon#49]
遅くなりましたが、5/17開催のアイマスエンジニアMeetup in Tokyoの振り返りをしましょう。
各自KPT形式で記載をお願いします！

(参考：準備スレ #45）

**Comment by gomao9** [comment]
## Keep
- 発案自体はカジュアルにやって、ちゃんと開催できたのは良かった
- ハッカソンの類だと参加しにくいような人も、今回は気軽に参加できたかな
- 当日LTに手を上げてくださった方が結構いたのは良かった

## Problem
- 軽い気持ちで公開したら予想以上に人が集まって、（運営としては）あんまりカジュアルじゃなくなった感
  - もちろん増枠したのは私の判断なので仕方ないところではある
- 当初は少人数だし軽食提供とか考えてなくて参加費無料で公開したけど、結果的に参加人数増やしたのでカンパに頼る形に
- 司会慣れしてなさ。もうちょっとちゃんと当日の流れをシミュレートしとくべきだった
- 歓談タイム、LTが始まったらちゃんと聞く雰囲気になって歓談できなくなった問題。そこらへんの塩梅難しいなって思いました
- 前日から日付が変わる頃に、補欠枠の人をどうするかとか考えてバタバタしてしまった。
  - 前日12時にリミットを設けてその時点の状況で判断するとか決めておけばよかったかもしれない

## Try
- （眠いので後で書く）

**Comment by treby** [comment]
## Keep

- 特定の個人に依存せず、イベントを開催できた(といっても、東京自体2回目だけどｗ)
  - これはIM@Study全体にいえることなのかもしれないけど、主体的に動いてくださる方が多くて助かるし健全な気がする。
  - 懇親会しかり、配信しかり
- 全部は把握していないけれど会が回るってすごいことだな、と
- 会を重ねて運営の練度はあがってきているのでは。
- ピザ問題はなかった：丁度良さげな枚数

## Problem

- 互いに話す時間があまり取れなかったかもとは
  - 飛び込みで話すにしても1分そこらで切った方が良いかも
  - この辺は最初からドラ出しておくべきだったね、と @hamaco さんと話したりしてた
- お金問題
  - 基本参加費徴収で回した方が良いかなー
- お酒問題：お酒なくなるの早かったですね。ソフドリ・お菓子は意外と残った
  - 懇親会時の机の配置(移動しづらかった)とかももしかしたらあるかも

## Try

- LTはドラでタイムコントロール
- IM@Studyに求めるものを @imas/staff で摺り合わせたい
  - 「アイドルを愛でる〜」はあるけど
  - 会を開催するというベースだとなかなかそこまで話がいかないし、普段の非同期なコミュニケーションもしかり
  - 期待される効果：気持ちの良いイベント開催

**Comment by takayamaki** [comment]
# Keep
- 当日進行上大きな問題は発生しなかった
- ピザは増やして正解だった
  - 平日夜だったこともあって二次会に行かずに帰った方も多かった
- 飛び込みLVが予想したより遥かに多くありがたかった

# Problem
- 配信機材を見直す
  - 配信機材が貧弱過ぎて当日たくみPに2台目をお借りすることになってしまった
  - 家で試した確認は配信のエンコードが出来ることだけで配信管理画面のことをすっかり忘れていた
  - 私物ノートPCを買い替える方向で検討中
- 会場入りした際にクラウドワークスの大場さんが「カクヤスの金額が事前に受けていた連絡と違った」と仰っていた
- 参加費問題
  - やはり参加費として全員から多少は頂いたほうがよさそう
  - 参加費4桁は敷居高く感じるので500円ずつくらい全体からもらって残りはカンパをお願いする？
- 「平日夜だからなー、ちょっと参加しづらいからニコ生かなー」という声が周囲でそこそこあった
  - 金夜か土夜にするとその辺も拾えるだろうけど規模が大変なことになりそう
- 発表・LTの時間管理があまり出来ていなかった
  - 結果的にはほぼ時間通り進んだとはいえ…
```
たくみP 24分
津田沼P 6分
SARUさん 5分
takemikamiさん 11分
imastodon.netの話 15分
メガネじゃないって話 15分
```

# Try
- LT時間管理をもうすこしきちんとやる
  - 3分前 or 5分前をフリップで提示
  - 時間になったらドラを鳴らす
- イベントごとに想定する対象層を設定してみる

**Comment by adachi-tsukasa** [comment]
# Keep
- またハッカソン、大阪MeetUpに引き続きイベントが開催できたこと
- 申し分のない盛り上がり
- 食べ物、飲み物で大きなトラブル（汚した、こぼしたなど）がなかったこと

# Problem
- ソフドリ、お菓子が多かった
  - 見積もり誤りでした…申し訳…
- 設営に時間がかかってしましった
  - 開場時間になっても設営が終わらなかった…
  - 席のレイアウトを決める時間が別途必要だった

# Try
- もっと気軽に飲み物・食べ物を手に取れるような仕組みづくり（会場レイアウト含めて）
- 食べ物・飲み物見積もり精度をあげたい

**Comment by hamaco** [comment]
# Keep
* 参加者結構いたし参加率もとても高くてよい感じ
* 場所・日時的に都合が合わない人達もニコ生もそれなりに見てくれてたのかなって

# Problem
* LTちょっと多すぎた感
    * 思ったより話したがりが多かったのと、皆ちゃんと話しを聞きすぎてるな

# Try
* ドラがあるなら次回は使っていきたい

**Comment by gomao9** [comment]
まとめ

# Keep

## 開催・運営のこと
- 発案自体はカジュアルにやって、ちゃんと開催できたのは良かった
- またハッカソン、大阪MeetUpに引き続きイベントが開催できたこと
- 当日進行上大きな問題は発生しなかった
- 申し分のない盛り上がり
- 特定の個人に依存せず、イベントを開催できた
  - これはIM@Study全体にいえることなのかもしれないけど、主体的に動いてくださる方が多くて助かるし健全な気がする。
- 全部は把握していないけれど会が回るってすごいことだな、と
- 会を重ねて運営の練度はあがってきているのでは。

## 参加者のこと
- 参加者結構いたし参加率もとても高くてよい感じ
- 当日LTに手を上げてくださった方が結構いたのは良かった
- 飛び込みLVが予想したより遥かに多くありがたかった
- ハッカソンの類だと参加しにくいような人も、今回は気軽に参加できたかな
- 場所・日時的に都合が合わない人達もニコ生もそれなりに見てくれてたのかなって

## 飲食周り
- ピザ問題はなかった：丁度良さげな枚数
- 食べ物、飲み物で大きなトラブル（汚した、こぼしたなど）がなかったこと

# Problem/Try

## 開催・運営のこと
### Problem
- 当初は少人数だし軽食提供とか考えてなくて参加費無料で公開したけど、結果的に参加人数増やしたのでカンパに頼る形に
- 基本参加費徴収で回した方が良いかなー

### Try
- やはり参加費として全員から多少は頂いたほうがよさそう
- 参加費4桁は敷居高く感じるので500円ずつくらい全体からもらって残りはカンパをお願いする？

## 発表LT時間管理まわり
### Problem
- 歓談タイム、LTが始まったらちゃんと聞く雰囲気になって歓談できなくなった問題。そこらへんの塩梅難しいなって思いました
- 互いに話す時間があまり取れなかったかもとは
- 発表・LTの時間管理があまり出来ていなかった
- 結果的にはほぼ時間通り進んだとはいえ…
- LTちょっと多すぎた感
- 思ったより話したがりが多かったのと、皆ちゃんと話しを聞きすぎてる感

### Try
- この辺は最初からドラ出しておくべきだったね、と @hamaco さんと話したりしてた
- 飛び込みで話すにしても1分そこらで切った方が良いかも
- LTはドラでタイムコントロール
- LT時間管理をもうすこしきちんとやる
  - 3分前 or 5分前をフリップで提示
  - 時間になったらドラを鳴らす
- ドラがあるなら次回は使っていきたい
- 交流もうちょっとやれる感じにしたい

## 飲食まわり
### Problem
- お酒問題：お酒なくなるの早かったですね。ソフドリ・お菓子は意外と残った
- ソフドリ、お菓子が多かった
- 気がついたらお酒がなかった
- 会場入りした際にクラウドワークスの大場さんが「カクヤスの金額が事前に受けていた連絡と違った」と仰っていた

## Try
- もっと気軽に飲み物・食べ物を手に取れるような仕組みづくり（会場レイアウト含めて）
- 食べ物・飲み物見積もり精度をあげたい

## 会場まわり
### Problem
- 設営に時間がかかってしましった
- 開場時間になっても設営が終わらなかった…
- 懇親会時の机の配置(移動しづらかった)とかももしかしたらあるかも
- 「平日夜だからなー、ちょっと参加しづらいからニコ生かなー」という声が周囲でそこそこあった
  - 金夜か土夜にするとその辺も拾えるだろうけど規模が大変なことになりそう

### Try
- 席のレイアウトを決める時間が別途必要だった

## IM@Studyそのものの運営につて
### Try
- IM@Studyに求めるものを @imas/staff で摺り合わせたい
  - 「アイドルを愛でる〜」はあるけど
  - 会を開催するというベースだとなかなかそこまで話がいかないし、普段の非同期なコミュニケーションもしかり
  - 期待される効果：気持ちの良いイベント開催
- イベントごとに想定する対象層を設定してみる

**Comment by gomao9** [comment]
振り返りできたのでクローズしますー
