### ISSUE TITLE
12/17 ハッカソン準備情報集約スレ

### ISSUE THREAD

**Issue by hsugita** [imas/hackathon#5]
### 目的
- @treby 氏の伝手でCW社に貸してもらえそうではありますが、どうしても都合がつかないことはあると思うので、会場選定に必要な情報を整理しておきます。
### 決めること
- ハッカソン会場に必要な条件
### 決めないこと
- 会場は決めない。あくまで必要条件を検討します。
### Close条件
- [ ] 第2回会議用アジェンダに会場についての項目を記載する

**Comment by hsugita** [comment]
#### 必要そうな要素
* 立地
  * 都内で不便すぎないところ
* 会場の広さ
  * 参加人数による。何人ぐらいを想定してますかね＞各位
* 会場借りる費用
  * 運営メンバーで割り勘してつらくない金額
  * 参加費徴収するなら多少高くても大丈夫？
  * 設備レンタル費用を計算に入れるのを忘れないようにしよう
* 会場設備
  * 映像流したりLT発表したりするためのプロジェクタ＆スクリーン、もしくは大きなディスプレイ
  * 電源（電源タップ含む）
  * ネットワーク関係(Wifiつかえるか)

**Comment by treby** [comment]
まとめ、ありがとうございます！

＞ 立地
都内agreeです。

＞会場の広さ
参加人数としては多くても50人くらい考えていました。

＞会場借りる費用
なんとかしたいですね。

＞会場設備
スクリーン、テーブル、椅子でしょうか
Nice to haveでwi-fi、マイク、電源などなど

会場に関しては、基本的には任せてもらっても大丈夫ですよ。
が、要件定義するのは大事ですよね :)

**Comment by treby** [comment]
具体的な日程候補が出てきたら、具体的な調整作業に移れそうな気がする。

**Comment by treby** [comment]
クラウドワークス様

> - 食事はビル側の制約があって飲み物はカクヤスのみ
> - 食べ物は隣の三越の惣菜だけ
> - 飾り付けは原状復旧してもらえるなら
> - ハッカソンで机にすわって電源も必要でみたいな感じだとMAX５０人ぐらいなきがするね

**Comment by treby** [comment]
FYI：クラウドワークス様でミートアップあるので、顔出されてみても良いかも
https://cw-meetup.doorkeeper.jp/events/52879

**Comment by treby** [comment]
数十人の着座で全然余裕あり。机出したらどんな感じでしょう。畳スペースっぽいのもあります。
当日はCIOの方(大場さん)に会場係していただけるらしい。

**Comment by hsugita** [comment]
そろそろ開催1ヶ月前なので、当日のタイムテーブル（スタッフ／参加者）確定させたり募集ページ作って募集開始したりしないとですね。今週末めどぐらいでやっちゃいたいなーという気がしますがいかがでしょうか。

とりあえず私は前回会議の記憶を呼び覚ましてきます。

**Comment by hsugita** [comment]
会場を使える時間は 10:00〜21:00 です。 (https://twitter.com/treby006/status/779175263942782976)

@treby 一応確認なのですが、会場をお借りできる時間が10:00からなので、10:00にスタッフが入って会場準備してから、10:30〜11:00ぐらいに参加者を入れて開始みたいな雰囲気で合ってますかね？

**Comment by treby** [comment]
できる方でビデオチャットとかで軽く擦り合わせるのも良いかも。

> 会場をお借りできる時間が10:00からなので、10:00にスタッフが入って会場準備してから、10:30〜11:00ぐらいに参加者を入れて開始みたいな雰囲気

そんな雰囲気です。

**Comment by hsugita** [comment]
ビデオチャットしますか。Twitterのほうで調整してみます。

@treby 

> - 食事はビル側の制約があって飲み物はカクヤスのみ
> - 食べ物は隣の三越の惣菜だけ

懇親会で出す飲食物はもちろん上記のとおりですが、参加者が持ち込むものも同様ですかね？

**Comment by hsugita** [comment]
今までの諸々を踏まえて再度タイムテーブル案を出してみます。

時刻|内容
:----:|-----
10:00 | 集合・準備
10:30 | 入場開始
11:00 | オープニング
11:10 | アイスブレーキング
11:30 | ハッカソン開始
17:00 | かためのLTタイム(成果発表含む)
17:50 | クロージング
18:00 | 希望者で懇親会(ゆるめのLTタイム含む)
20:00 | 解散・撤収作業

以下、気になることなど。

- かためのLTタイム長い？(短い？)
- 意外とハッカソンしてる時間短い。
- 撤収作業が30分で終わるなら20:30終了でも良さげ？

**Comment by treby** [comment]
上記、ごまおさん、ぼでーさんとお話し、connpassの方に追記しました。

**Comment by hsugita** [comment]
## 必要なもの
- [ ] 案内の用紙
- [ ] 受付の用紙
- [ ] 名札ケース(hamaco)
- [ ] 名札用の紙(ごまお)
- [ ] 名札書く用のマジック(ごまお)
- [ ] LT配信機材(やるなら)

## 人手がいること
- [ ] 受付
- [ ] 会場設営
- [ ] 軽食手配
- [ ] 懇親会
- [ ] 司会・オーガナイズ 
- [ ] 記録写真係
- [ ] LT配信係(やるなら)

**Comment by treby** [comment]
ついついSlackの#planningの方がラフだからそちらばかり書いちゃうけど、
ログを残す意味でこっちにも書いておこう。参加者に送る案内案。今日中に送ろう。

```
こんにちは

この度はアイマスハッカソンに応募いただき、ありがとうございます。
いよいよハッカソン当日まで一週間となりました。ハッカソン当日を楽しい一日とできるよう、いくつか案内をさせていただきます。

○ 自己紹介について

自己紹介のために、試験的にリポジトリに情報を集約する運用をしています。
https://github.com/imas/hackathon/tree/master/producers

参加方法についてはWikiにまとめていますので、是非ご協力ください。　
https://github.com/imas/hackathon/wiki/%E3%83%97%E3%83%AD%E3%83%87%E3%83%A5%E3%83%BC%E3%82%B5%E3%83%BC%E8%87%AA%E5%B7%B1%E7%B4%B9%E4%BB%8B%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

後述のSlackにも自己紹介用のチャンネルを設けておりますので、そちらでも構いません。

○ LTについて

今回のイベントは第一部をハッカソン、第二部を懇親会としようと考えています。
そして懇親会の余興として、LT大会を企画しています。

現時点で技術的なものが多い傾向にありますが、アイマスに関係していれば何でもOKです。
お酒が入る席でもありますので、この機会にアイドルへの愛を話してみませんか？


○ 当日までの(ゆるい)コミュニケーションについて

当日は懇親の機会を設けようと思いますが、同じプロデューサーさん同士、
それまでの時間を楽しく過ごせるようSlackを用意しています。

https://imas-hack.herokuapp.com/

カジュアルなコミュニケーションに抵抗がない方は是非ご登録ください。

それでは、当日お会い出来ますこと楽しみにしています。
```

**Comment by treby** [comment]
今日明日で打っておく

- 会場の行き方
- カンパ周り
- LTの時間(5分)
- 配信(ノウハウがない＆回線状況次第なのでお試し)

**Comment by kaibasira** [comment]
> 配信について
- 映像の配信はどうする？
  （ラップトップ添付のカメラだとやっぱり貧弱でスライドの文字は恐らく見えないだろう.....カメラを買う必要アリ？)
- 当日、どうやって音を拾うか
  (LT用マイクライン入力？(一応ミキサはある) それともスピーカーから拾う？)
- ネット回線がどこまで持つか...

配信自体は計画実行しましょう！

**Comment by gomao9** [comment]
参加者向けに送ったメールの内容ぺたり。
```
こんにちは。

ハッカソン当日まで残すところ3日となりました。
当日のスムーズな進行のために、いくつかお知らせをさせていただきます。

○会場への行き方
会場となるクラウドワークス様があります、恵比寿ガーデンプレイスは少々分かりにくい立地となっています。
参考に、恵比寿駅からの行き方を案内した動画を貼っておきます。
https://www.youtube.com/watch?v=MPIj6qnrbCI

また、当日会場への行き方が分からなくなった場合には、Twitterの下記アカウント、もしくはimas-hackのSlackにてご連絡いただければご案内できると思います。

- @treby006
- @hamaco
- @gomao9

○映像配信について
当初は会場の様子の映像配信は行わない予定でしたが、機材のめどが立ったため、成果物発表会とLT大会の様子は配信する予定です。
映像への映り込みNGの方は、当日受付にてお知らせ頂けますと幸いです。 (特にLT発表者の方)
直前の告知となりまして申し訳ありませんが、よろしくお願いいたします。

※配信予定のコミュニティ（ニコニコ生放送）
- プログラミング生放送（出張所） http://com.nicovideo.jp/community/co9320

○LT持ち時間について
現在、LT発表者は8名を予定しています。
一人あたりの持ち時間は5分程度を想定しています。多少オーバーしても全く問題ありませんが、大きく超えそうな場合は事前にひとこといだだけますとありがたいです。

○会場のプロジェクターへの接続について
会場のプロジェクター接続はHDMIのみとなっていますが、HDMI<->mini display portの変換コネクタは用意しています。
それ以外の接続が必要な方は、お手数ですが各自ご用意いただきますようお願いします。

○持ち物チェックリスト
最後に、下記のとおり持ち物チェックリストを作成しました。よろしければご活用ください。

- 自分のマシン
- ACアダプタ
- プロデューサー名刺(お持ちなら)
- サイリウム・ペンライト類(あると楽しいかも)
- アイドルを愛でる心

それでは、当日お会いできますことを楽しみにしています。
```

**Comment by treby** [comment]
こちら一旦closeします

**Comment by gomao9** [comment]
ハッカソン成果一覧です
https://docs.google.com/spreadsheets/d/1BISMYu1mslBkQswismKDW6SpLXCLu2WI3LUdWl0R89w/edit#gid=782430868

**Comment by gomao9** [comment]
当日の発表一覧です
```
5分
MH35  Taigaのインストールが終わらない！ はい  どちらも

5分
8184P アタポン形式イベポイント時間変換  はい  プロジェクター使用

5分
ぽっか  モバマスの通知をするかもしれないもの  はい  プロジェクター使用

10分
まつし  巨大茜ちゃん人形をカットイン(slコマンド)  はい  どちらも
(LT) 「アイマスマネジメント～ミリオン編(仮)」 by @filderschoiceMS / ミリオン

5分
てぃがー  デレ劇をコマ分割してくれるすごいやつ  はい  どちらも

5分
フサギコ  アイマス版slコマンド with Sixel graphic はい  どちらも

5分
treby このみさんにPull Request作ってもらった  はい  どちらも

10分
たくみP    「台詞を言ったシンデレラガールズのアイドルを判定するサービス」を制作した    はい    どちらも
(LT) たくみP LTのテーマ「Pixivにあるシンデレラガールズのイラストを集計してみた話」 はい  プロジェクター使用

15分
banjun  無限Live Photos はい  プロジェクター使用
(LT) 「AppleエンジニアにありすLive Photoを見せてきた話(仮)」 by banjun / シンデレラ

8分
「ミリオンライブ！キャスト投票キャンペーンの話」 by gomao / ミリオン

5分
「Primusというツールを作った話, 或いは命名特権の濫用について」 by papix / シンデレラ

5分
「million-timerで捗る?ミリP生活」 by kan fushihara / ミリオン

5分
「担当アイドルとデートしたい人生だった」 by bode / シンデレラ
```

**Comment by hsugita** [comment]
ハッカソン翌日にConnpassで送ったメッセージです。

 ```
アイマスハッカソン2016へご参加ありがとうございました！

昨日はアイマスハッカソン2016へご参加いただきまして、誠にありがとうございました。
おかげさまで多数の方にご来場いただきまして、大盛況でした。
成果物発表・LT大会では、技術的に本気な内容から、アイドルへの愛に溢れた発表まで盛り沢山で、個人的にも、とても楽しませて頂きました。

さて、今回のハッカソンに関しまして、アンケートのお願いをしております。（未定ですが）次回開催へ向けての参考にいたしますので、ぜひ熱いご意見・ご感想をお寄せください！
https://goo.gl/forms/s6yOyD8zBPVsKdRr2

また、Slackグループもございますので、ハッカソン関係なく、今後もエンジニアなプロデューサーさん同士で交流が持てればと思います。
https://imas-hack.herokuapp.com/

今後とも、プロデュース、ハックの両面から「アイドルを愛で」、「アイマスに貢献(Contribute)」していきましょう。
どうぞよろしくお願いいたします！
```
