### ISSUE TITLE
あいますえんじにあMeetup in 京都 ワードカード

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#63]
### アイディアソンのワードカードを投稿するためのissueです
- 第一部 15:20～16:00
- 第二部 16:40～17:30

**Comment by adachi-tsukasa** [comment]
| ワードカード1| ワードカード2  | ワードカード3 | 
| --------------- |:---------------:| -------------------- | 
| 電子マネー | 暗号技術 | 天気予報 | 
| 仮想通貨 | 顔認証 | 触感センサ | 
| ブロックチェーン | マイナンバー | プログラムレス | 
| スーパーコンピュータ | 3Dデータ | 4Kディスプレイ | 
| 量子コンピュータ | 3Dスキャナ | 音声合成 | 
| UE4 | Unity | C++ | 
| Perl | Java | Elixir | 
| Rust | Python | Ruby | 
| Lisp | D | C | 
| JavaScript | ViVoDa | CuCoPa | 
| PrincessFairyAngel | メンタルフィジカルインテリ | ジュエル | 
| 出身地 | 二次創作 | ライブ | 
| フェス | オーディション | 声優 | 
| タッチパネル | コミュ | 楽曲 | 
| フェス | オーディション | 声優 | 
| 歌詞 | ダンス | ラジオ | 
| トレード | アプリゲーム | 趣味 | 
| 作曲者 | 作詞者 | 編曲者 | 
| 機械学習 | DB | 継承 | 
| IoT | アプリ | ウェアラブルデバイス | 
| AR | VR | 経路探索 | 
| サーバー | Shell | BlueToothLowenergy | 
| AI | 回路 | スマートスピーカー | 
| クラウド | マルチエージェント | 電子ペーパー | 
| SL | CowSay | デスクトップキャラクター | 
| LivePhoto | USB TypeC | カーナビ | 
| ゲームエンジン | ツリー構造 | IPA試験 | 
| 機械語 | bot | コイル | 
| 無接点充電 | モーショントラッキング | スマートウォッチ | 
| 自動運転 | ドローン | ロボット | 
| アルゴリズム | アーキテクチャ | プロダクトデザイン | 
| リテラシー | - | - |

**Comment by adachi-tsukasa** [comment]
| ワードカード1| ワードカード2  | ワードカード3 | 
| --------------- |:---------------:| -------------------- | 
| 水着 | 夏の終わり | 秋の夜長 | 
| 蚊取線香 | プール | 海美 | 
| 山 | 花火 | 白いワンピース | 
| コミケ | 麦わら帽子 | 恋愛 | 
| ジューンブライド | アニバーサリー | 京都 | 
| 関西 | 肉 | ピザ | 
| 寿司 | カレーメシ | - |

**Comment by kaibasira** [comment]
こちら閉じます～
