### ISSUE TITLE
あいますえんじにあ Meetup in 京都の振り返り

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#66]
### これは何
- [201709/02 あいますえんじにあ Meetup in 京都](https://imas.connpass.com/event/64177/)の振り返りの為のissue

### ref
- 準備スレ #51 ワードカード #63 

### 何をすればいいの？
- KPT形式で今回を振り返ってみてください(スタッフは必須で)
  - Keep
  - Problem
  - Try
- 参加者の方には感想をKPTでもそうじゃなくても自由に書いてもらおう！ニコ生リスナーにも！

### このissueがcloseする条件
~~- ニコ生のアーカイブ動画を上げる~~
- [x] Slackのチャンネルをアーカイブする
- [x] 振り返りの日程を決める... **9/16(土) 21:00〜** ...Done
- [x] 振り返りの会議の議事録のmerge→[議事録](https://github.com/imas/hackathon/blob/master/plannings/20170916.md)
- [x] 書いてもらったKPTや感想を基に振り返る
- [x] (出来たら)当日の成果物を何らかの形で残す
- [x] 写真の共有
- ※closeしたらMilestoneのあいますえんじにあタグのcloseを確認すること

**Comment by kaibasira** [comment]
# Keep
- 出席率100%！！！人数もあるだろうけど何気にこれは嬉しい。是非維持したい……
- お菓子の持ち寄り良かったのでは？むしろお菓子過多まであった
  - 人によってはネタも出せていい話題づくりになったのでは
- ニコ生出来た
  - 前回肉上げでは出来なかった試み 今後もやりたい
- 意外に幕間が好評だった(本当にナイスでしたcromisaさん……)
  - Meetupやなんかのゆるい形式のイベントなら今後もアリか？
- それぞれが交流できる濃い空間を提供できたと思う
- スタッフの役割を明らかにしていたのである程度負担を分散出来たのではないか

# Problem
- ニコ生の放送事故
  - 多分PCのスペック不足(専用ツールを動かすマシンパワーが無かった)
  - 機材は足りている……ニコ生用のPCをどうするか……
  - 但しワイプとかを入れないなら公式生放送ツールで十分
- アイディアソン難しい
  - 時間配分難しい(40分って意外に短い？)
  - ワードカードからの連想難しい
  - アイディアを出してもらいやすくするための別なアプローチ？
  - 次回try
- 準備時間配分
  - 余裕を持ってスライドを作ろう
  - 余裕を持ってノベルティを作ろう
  - 余裕を持ってワードカードを（ｒｙ
- LTの順番発表など細かい点に意外と気が回らない
  - 何が必要になるかもう少し具体的なモノを入念に練って原稿を用意？

# Try
- 次回開催は某あつみちゃんPのお陰で大阪開催が決まってる
- もう少し人を集めたい
  - 宣伝をしっかりする？connpass以外も募集をかける？要作戦
- 純関西スタッフもう1人ぐらい……！
- 出来たらハッカソンもやりたい……アイディアソン→ハッカソン？
- ぼでーはもっとイベント中に皆と絡みたい（

**Comment by klcatha** [comment]
ニコ生で拝聴しましたのでリスナー目線で。

### keep
- ぼでーさんのコンテンツ性維持
- ニコ生
- 幕間のクイズ
- LT登壇者の担当を配慮したBGM
- リスナーへの呼びかけや配慮
    - リスナーに感想やアイディアを聞く流れができていた

### problem
- 機材トラブル
- スライドによっては文字が見づらい
- スライドしか映らなかったので会場の雰囲気がわかりにくい
   - 今回は会場の都合で仕方ないところではある
- 愛が重い（問題？

### try
- 開発したい
- もくもく会 → 発表会
- ぼでーさん以外の名前を覚えられる何か
- スライド以外の会場の様子を配信
- よりリスナーと絡むなにか
    - ニコ生でよくある選択肢が画面に出てきてクリックするようなやつとか
    - コメント集計

**Comment by katao** [comment]
私もニコ生参加だったので。

### keep
- 事前のtwitter等の告知
- ほぼonTimeでスタート
- 途中のレクリエーション
- ニコ生
    - コメントを拾ってくれていた。
- トラブルに対する対応
- LTの時間管理
- ぼでーさんのトークスキルの高さ

### problem
- 機材トラブル
    - 最初の音量調整・カメラ静止・最後のプロジェクター
- ニコ生のコメント数が少なかった
    - コメントしやすくするアプローチが何かできれば。。。
    - LTしているPの名前とLTタイトルを出してもらえたら嬉しい
- 絵を書いた発表はカメラ的に見づらい

### try
- 事前にテスト配信して機材確認
- 内部にニコ生コメント職人を設置
- ニコニコアンケート
- 最初に名詞交換
- 最後に集合写真

**Comment by crssnky** [comment]
レク係(?)のcroMisaです

### Keep
- アイデアソン、散らばったアイデアをまとめてスライドまでくださった！
- ニコ生で遠方の人も見れた(参加できた)
- お菓子がたくさん
- レクが無事できた

### Problem
- 僕の乗るバスいっつも渋滞遅延する...
- レクリエーションのスライドのチープさ
- ニコ生からだとスライドが見えない
- 名刺一枚も交換してない！

### Try
- アイデアソン(ハッカソンも?)を、まとめたIM@Studyページ(github.io？)を用意してまとめたい
- 撮影NGエリアとかいろいろ制約はあるだろうけども、Theta360で配信もあり？
- LTスライドは1台の動作確認済PCにまとめる
- 外からだと雰囲気とかモヤモヤで不透明？分かりやすい宣伝文句？
- 別分野(主に創作界隈)からの参加者
  - 「アイマスエンジニアMeetup」というタイトルが実は壁になっている？

**Comment by hamup8** [comment]
# Keep
- 会場設営・現状復帰スムーズ！
- お菓子たくさん！(各担当ネタも盛り込まれて面白かった。)
- レクリエーション面白かった！
- ぼでコンテンツ力
- ニコ生放送できた。
- スタッフの負担分散ができた。
- 多くの人と交流でき、全体的に良い雰囲気を作れた。

# Problem
- アイデアソン
  - 部ごとの時間が短いのもあり、盛り上がり始めた頃に終わってしまった。
  - ワードカードからの連想が意外と難しかった…。
- LT用機材
  - 機材トラブルでスライドが途切れ途切れになってしまった。
- スタッフとして余り動けてなかった…。
- 宣伝をもっと積極的に行うべきだった？

# try
- 360度カメラ配信面白そう…！
- LT用機材の動作確認をしておく、リカバリ策を準備しておく。
- 関西でもハッカソン形式のイベント開催する。
- LT発表する。

**Comment by adachi-tsukasa** [comment]
遅くなりましたー…
# Keep
 - 2回目の関西開催！お初の方も、そうでない方も来てくださるのは嬉しい。
 - ニコ生。要望もありましたしね。
 - 持ち寄りお菓子。担当、地域を感じたり話のネタにもなったりでとても良かった。
 - 開場前の余裕。到着〜用意完了までのおおまかな段取りを決めていて正解だった。
 - ぼでーさんに集中しないタスクの割り振り。

# Problem
 - 用意したお菓子類が余る→持ち寄りをもっと考えるべきだった。
 - 用意した飲み物が余る→LT中は食べ飲みより、集中して聞く雰囲気だった。
 - 各テーブルに拭くモノがない。→調整不足でした。
 - LT中の機材トラブル。→知見不足もあるはず。リカバリープランを考えておくこともできそう。
 - 必要な事柄が決まっていない、モノが足りないなどスタッフ力不足。

# Try
 - ニコ生視聴者の方ともアイディアソン。
 - 3回目の関西開催！

**Comment by urou** [comment]
受付担当していました。遅くなってすみません。

# **Keep**
 - 参加者さんからのお菓子の持ち寄り
 - ニコ生による配信

# **Problem**
- ピザについて5枚を購入したが多かった(参加者+スタッフ 計17名)ため、注文する枚数を減らしてもよいかもしれない。
- 参加費について765円は意味のある数字なので良いと思うが、お釣りの処理の面で受付に負担がかかるので次回以降はキリの良いとも思った。
- お釣りを用意していたが、多くの人がお釣り無しで払っていただけた。また、お釣りはカンパしておいてほしいという人もいた。


# **Try**
- 次回こそはLT参加？

**Comment by kaibasira** [comment]
全てのタスク終えたので閉じます ありがとうございました
