### ISSUE TITLE
ハッカソンのロゴ・ステッカーつくる

### ISSUE THREAD

**Issue by hsugita** [imas/hackathon#7]
- ハッカソンをイメージしたステッカーを作ります。
- 基本的に @hsugita のやりたいようにやるので他の人はあまりに気にしなくても良いです。
- なるべく経過は随時コメントしていくようにしたい。
- デザインとかで迷ったら相談するかも。

**Comment by hsugita** [comment]
[クローゼットP](https://twitter.com/closetz) と打ち合わせをしまして、ロゴ制作を正式に依頼しました。
9月中に第1稿を出していただける予定なので、いただき次第こちらでも共有するつもりです。

**Comment by hsugita** [comment]
クローゼットPよりデザイン案を2つ出して頂きました。

* [PlanA.pdf](https://github.com/imas/hackathon/files/505094/PlanA.pdf)
* [PlanB.pdf](https://github.com/imas/hackathon/files/505095/PlanB.pdf)

@treby @hamaco @knit-subaruP @katao 
内容を確認いただいて、主観的でも良いのでご意見をいただきたいです。（どっちのほうが好き、とかでも）

**Comment by hsugita** [comment]
* 個人的にはB案のほうが好み
* B案のほうがエンジニア向けのそれっぽいステッカーになる気がする（主観）
* 非エンジニアのプロデューサー向けアピールを考えるとどっちが良いだろう？（非エンジニア向けアピールを重点に置かなくても良い気はするけど）
* `アイマスハッカソン`とカタカナで入れるよりは、`#imas_hack`とハッシュタグを入れたい気がする

**Comment by treby** [comment]
B案良いと思います :) (そうか、メインロゴのようなものもあると捗るかも、と思いつつ、これは今後やる必要があったらやる感じで今回好き勝手やっちゃって良いかと！)

**Comment by hamaco** [comment]
私もB案好みなんですが、もう少しアイマス色強くてもいいのかも? と。(曖昧すぎる……)
でもそうすると貼り辛くなるのかなー。私貼る時あまり気にしない人なのでその辺がイマイチ分からないです>_<

あと、ステッカーについては基本エンジニアメインだと思うので非エンジニアあんまり考えなくてもいいのかなーって思います。

**Comment by hsugita** [comment]
@treby 
> メインロゴのようなものもあると捗るかも

欲しいですねー。Conpassグループのヘッダ画像とプロフィール画像あたりも設定したいですし。

**Comment by hsugita** [comment]
* `#imas_hack` ハッシュタグ入れたい
* アイマス分増やしたい

上記要望で修正依頼を出しました。

スケジュール的には、11月下旬ぐらいに入稿データをいただいて印刷発注かければ、アクシデントがあっても余裕で当日に間に合うなー、ぐらいの気持ちでおります。

**Comment by treby** [comment]
@hsugita 提案なのですが、シートを下記のこのりお分とまとめませんか？
https://github.com/imas/hackathon/issues/8#issuecomment-239778253

<img width="511" alt="2016-10-31 1 35 55" src="https://cloud.githubusercontent.com/assets/1079365/19838070/8ac1b094-9f0a-11e6-96bf-0a620243f706.png">

上記はこのりおイラストに適当にカットパスまで入れてみたものです。adprint様で134mmx194mmで19,000円という見積もりが出ました。印刷費は良い感じに分担する形で一枚のシートにまとめられるとよいかな、とふと思いました。

もちろん、クローゼットPさんの意向にもよりますのでご確認いただけますとmmいける場合はデータをお渡しします。

**Comment by treby** [comment]
まあ、適当にとか言いながら数時間かかっているわけですがw http://www.atelier-nodoka.net/2016/10/photoshop-illust-path/

**Comment by hsugita** [comment]
お返事遅くなりました。
クローゼットPに確認してみますね！
（こういうシールのシートって結構なお値段するんですね……）

**Comment by treby** [comment]
サイズとカット数によりますね

**Comment by hsugita** [comment]
クローゼットPより修正版デザイン頂きました。
[PlanC.pdf](https://github.com/imas/hackathon/files/589430/PlanC.pdf)
特に問題なければ入稿データを頂いてそのまま印刷発注しようかと思っております。
皆様確認よろしくお願いします 🙇   @imas/imas_hack

**Comment by hsugita** [comment]
@treby このりおイラストとステッカーを一緒にまとめられるかどうかはクローゼットPに確認中です！

という話のところで今更な話で申し訳ないのですが、イラストシールとステッカーは別シートのほうが後々便利のような気もしてきました。別シートなら、このりおシールはアイマスハッカソン関係ないところでも使えますし、ステッカーの方もミリオン分と切り離せたほうが良さげな気がします。
（一緒のシートで発注しても、必要になったら手作業で切り離せば良いと言えば良い気もしますが）

**Comment by treby** [comment]
デザイン良いと思います。PCに貼ると映えそうですね！

@hsugita ステッカー別々の件、承知しました！では、そちらで進めましょう！

**Comment by hsugita** [comment]
@imas/imas_hack
デザインで特に気になるところとかないかな？　特にツッコミない感じなので入稿データ頂いて発注しちゃいますねー

**Comment by gomao9** [comment]
無事届いたのでissue閉じます！
https://twitter.com/gomao9/status/806713895897268224
