### ISSUE TITLE
イベントのイラスト作成

### ISSUE THREAD

**Issue by treby** [imas/hackathon#8]
夏コミお疲れ様でした。
イベントのイラストについて、ふぶきさんとのやり取りが動き始めました。
11月上旬締め切りで動いていただけそうです。やり取りしながら作ろうというところで順次こちらに進捗あげていきます。
皆さんにご意見求めることもあると思うので、こちらの動向をwatchしていただけると助かります(ふぶきさんにスムーズにお伝えするためにも大体〜1日くらいの反応速度で対応いただけるとありがたいです！)。

**Comment by treby** [comment]
https://github.com/imas/hackathon/issues/1#issuecomment-230134947 とかhttps://github.com/imas/hackathon/blob/master/notes/treby/20160724.md#個人目標 とかのコンテキストです。

**Comment by treby** [comment]
ついでに[これ](https://twitter.com/treby006/status/754652848428724224)をシール化して配りたい(関係ないけど)。予算とかと要相談。

**Comment by treby** [comment]
シール業者候補：

- https://www.glavity.com/
- https://www.digitaprint.jp/
- http://www.adprint.jp/default.aspx

adprintさまでやれないか諸々企み中。
P名刺でお世話になっている[ラクスル](https://raksul.com/)さまは複数カットパス対応してなさげorz

**Comment by treby** [comment]
これもぼちぼち動かねば……！

**Comment by treby** [comment]
今月中に完成いける？

**Comment by treby** [comment]
ふぶきさんより、ラフ画をいただきました。ありがとうございます。
このみさんだし、こたつもありかな(最近寒いですし)、とか一瞬思いましたが、今回はオフィスのイメージで行ってみようかと。

- connpassのイベントページサイズ
![connpassのイベントページサイズ](https://cloud.githubusercontent.com/assets/1079365/20028471/fca6ce1e-a375-11e6-96bb-9c65ed08b867.jpg)
- 元サイズ
![元サイズ](https://cloud.githubusercontent.com/assets/1079365/20028472/fccc5e9a-a375-11e6-85ff-a2ffecdf973b.jpg)

@imas/imas_hack 
ご確認ください！

**Comment by hamaco** [comment]
オフィスっぽいのいいなーって思います！ ハッカソンですし机でPCの前って:+1:

**Comment by hsugita** [comment]
connpassのイベントページサイズも良い感じ！

**Comment by treby** [comment]
上記でお願いしました
ふと、アイマスハッカソンなのに趣味(ミリオン)に走りすぎたかな、と思ったけれどきっと皆さんが告知を頑張ってくれる、はず……！

**Comment by treby** [comment]
@imas/imas_hack ふぶきさんより線画をいただきました。完成は来週末(11/27くらい)とのことなので、来週まで素材はめこみでページ公開できる状態まで持っていき、素材が完成次第、公開という形にしちゃいましょう！

![ow6sy73h](https://cloud.githubusercontent.com/assets/1079365/20452898/7e0e1790-ae58-11e6-8157-96fe46392319.jpg)

**Comment by treby** [comment]
![rgdhhxxq](https://cloud.githubusercontent.com/assets/1079365/20610659/f89a75ae-b2df-11e6-93d5-98d4b7d14370.jpg)

![_660x270](https://cloud.githubusercontent.com/assets/1079365/20610652/e60a0a3a-b2df-11e6-8c16-ff41230bbde1.png)

色付きバージョン

**Comment by treby** [comment]
https://imas.connpass.com/event/40290/
公開までできたので閉じます！
