### ISSUE TITLE
アイマスハッカソン2017 振り返り

### ISSUE THREAD

**Issue by treby** [imas/hackathon#81]
振り返りを各自KPT形式でお願いします！

**Comment by treby** [comment]
## Keep

- ユニット分けて作業したの良かった
  - 本当にほとんど自分動かなくてよかったな、と
  - 皆様のおかげですmm
- 受付
  - ありがとうございました
- 配信
  - なんか分からんけどワイプとかすごい
- 懇親会
  - 立食形式にしたの良かったですね。話しやすい雰囲気いつもより出せた
  - 乾杯 → 30分歓談も良かったのではないか
  - 飲食の量、概ねバッチリでした
- LT大会
  - ドラの導入でタイムコントロールほぼ完璧でした

## Problem

- スタッフの役割分担が割と人に寄りすぎているので人を変えた時の再現性はそんな高くない
  - メンバーが揃わなかった時に会が回るかどうか
  - 50人規模くらいだったらなんとかなると思いますが
- 機転を利かせて入れていただきましたが、LTの時の休憩は勘定に入れるべきでした
  - 二時間ぶっ続けで話があるというのは疲れるな、と
- アイマス「ハッカソン」である意味は考えていかないといけないかな。
  - ハッカソンでやるならヨーイドンで競いたいという意見もある。

## Try

- LT時間の合間合間に休憩挟む
  - 次回にフィードバック
- ノウハウを明文化していきたい
- 大元にあったガチのその時間内に作業して作ったものを見せる会はやりたい
  - その場合キラーコンテンツである「LT大会」を切った方がやりやすいのかな、、、

**Comment by takayamaki** [comment]
# Keep
- 個人/チーム選択制
  - 個人的な予想よりもチームを組んでる人が多かった
- 懇親会
  - 立食形式もピザ類の量も良かった
- 受付
  - あまり見えてなかったけどスムーズだったように見えた
- 配信
  - 再起動こそあれど配信断念するほどのトラブルはなかった
  - HDMIキャプチャ見やすかった
- LT大会
  - ドラで時間管理完璧
# Problem
- 忘れ物
  - 音声用の赤白ケーブルを忘れて買いに行った
  - 養生テープ忘れてWebカメラが固定できなかった
- 発表者転換時の抜き差しでHDMIキャプチャがよく不調に陥った
  - そんな使い方想定していないのでは…？
  - HDMIスイッチャ挟めば行けたかな…？
# Try
- HDMIキャプチャの安定動作を模索する
- 機材構成のシンプル化
- 短時間だけでも配信を代わってもらえるようにする(お手洗いとかのため)

**Comment by kaibasira** [comment]
本当にお疲れ様でした！！

### Keep

- チーム制
  - 思ったよりチームを組んでいる所が多かった
  - チームでないにしろ、お互いに進捗を見せ合いながら……ってとこもあったので良い雰囲気だった
- お菓子や食事の量
  - ピザあまり気味だったけど今回ので丁度いい量だったのではないだろうか？
- 前回よりラフな感じあった( 個人的感想 )
- 前半アイディアソンを後ろで取ってるのは良さげだった
  - そこから交流が生まれた人もいるのではないだろうか
- スタッフが熟れて来ているので前回より会の運営もスムーズになったのではないだろうか
- YoutubeLive、色々と使い勝手が良いのでこのままYoutubeLiveで良い気がする
  - 専用のチャンネルも生まれた
  - アーカイブも自動なのでスムーズ
- 願ったり叶ったりのスポンサー様

### Problem

- 配信のテクニカルな部分をフサギコ( @takayamaki )さんに任せすぎる
  - 知見の乏しさ、赤白ケーブルすみません
- 例のアクシデントの為に、運営用に使うスライドなどはスタッフ間で共有出来たほうが良いのではないか
- せっかくのテーマ「Did you know？」、もう少し推していきたかった感

### Try

- 「アイマスそんなに知らないからなぁ」という壁を壊していきたい
  - 機会の損失をなくしていきたい 意外とクソリプ推奨？
- 2日間制のガチハッカソン？
- アイマスらしい食事提供

**Comment by hamaco** [comment]
## Keep

- 色々問題なく終われたと思う
	- 個人的にはとてもまったりやれた
- 数人ホワイトボードに集まってなんかやってるのなんとなく見ててよかった気がする
- ストロングゼロは時期的によかった
- 折角のでかいドラなのでLT以外でもテキトーに叩いたのはまあ面白かったのでは

## Problem

- 名札用の紙を忘れていた…
- ホワイトボード前で色々話してたやつは結局どうなったのかなという気持ち
- なんか今回全体的に静かだった気がする? Twitterとかも含めて
	- 気のせいかもしれないし、LT大会の時とごっちゃになってる気もするのでなんとも…

## Try

- 余裕があったら(できればあまりを次回以降も使い回せる)名札作りたいなー
- もうちょっとアイマス方面でネタ食べ物あると面白そう
- 今回は本業で死にかけてたのでクソリプ力出していけなかったので次回はもうちょいやっていき

**Comment by adachi-tsukasa** [comment]
## Keep

- 今回も大きなトラブルなく、無事終了できたこと。お疲れ様でした。
- ハッカソン中のお菓子スペース。適度にわちゃわちゃできた。後方にデプロイできる。
- 立食形式の飲み食べ展開。
- LTの時間管理。ダレることなく良いメリハリ。
- スポンサー様の存在。ありがとうございます。

## Problem

- ソフドリ不足。追加していただいたり…
- ピザ用員の招集不手際。
- ハッカソン中に曲のボリュームが上がったり下がったり激しい時があった。
- ビールこぼしちゃった…

## Try

- ピザをメインに何か別の食べ物を追加。あまり遊びすぎない程度にそれっぽい食事。
- 今までの飲み食べの実績をまとめ、いい感じに扱って次回楽したい。

**Comment by hamup8** [comment]
お疲れさまでした！

## Keep
- スタッフの役割分散 ⇒ 集中的に忙しい人を無くせた気がする
- チーム制
  - 思ったより機能していた
- LT大会
  - ドラ導入できちんと時間管理できた
  - 途中で休憩挟んだのは正解だった
- 配信
  - ワイプすごい
  - アーカイブ化が簡単なの強い
- 懇親会
  - ピザ、お酒の量が丁度良かった
  - 立食形式にしたおかげでワイワイできる雰囲気作れた

## Problem
- ソフドリ足りなかった(追加のリカバリー有難うございました…。)
- 自己紹介なかった分、ハッカソン中の交流が生まれにくかった感(懇親会、LT大会では良い雰囲気になってた)

## Try
- 今までのピザ・酒実績をまとめて良い感じに統計出しておく。次イベ時以降に目安を簡単に出せると嬉しい。
- これまでのノウハウを明文化してスタッフ内の属人化回避（基本的にまわるとは思っているけど先々考えると必要なのかなーと）。

**Comment by katao** [comment]
当日は参加できず申し訳ありませんでした。
アーカイブ放送を見ての感想のみとなりますが、ご容赦下さい。

## Keep
- アーカイブ動画がある
  - 参加できず、非常に残念だったのですが、後から見れるのは本当に助かりました。
  - 興味ある人に共有もしやすく、他の人を巻き込むツールとして使えた。
- スポンサー様がついた。
  - 個人的にめちゃくちゃ驚きました。なんかとても大きいイベントになっている感じがしました。
- LT時の周囲のガヤが楽しそうでよかった。
  - 技術系LTだとガヤが静かなことが多いのに、やじ・合いの手が盛り上げていた。
- ほとんどのLTスライドがちゃんと後からの人も観れるように上がっていた。

## Problem
- LTを技術枠とダイマ枠にわける(?)
- アーカイブ動画だと、懇親会の時間はぼっちかんが出てしまう。(仕方ないけど)
  - 「懇親会中です。」画像を写す(?)

## Try
- 副業の予定が入らないようにする。これに尽きる。本当に申し訳ありませんでした。

**Comment by hsugita** [comment]
### Keep
- 前回の経験を活かしてもくもく→懇親発表がスムーズに
- 撤収も先手先手でスムーズに行ったと思う
- 分担したことでそれぞれ最適化・効率化

### Problem
- 名札用の紙を忘れた
- 配布物が増えて、最初は受付があまりスムーズにできてなかった

### Try
- 今回はチーム制でかなりうまく回ったと思うので、属人化しないように次回は分担を少しシャッフル？

**Comment by treby** [comment]
https://github.com/imas/hackathon/pull/83
