### ISSUE TITLE
アイマスハッカソン2018 in 大阪 振り返り

### ISSUE THREAD

**Issue by adachi-tsukasa** [imas/hackathon#87]
各自KPT形式で振り返りお願いします。

**Comment by YutaGoto** [comment]
## Keep
- ハッカソン開始で参加者全員がアイディアソンコーナーに来て、全員自己紹介する流れになったのがよかった。いい感じのアイスブレイクになったと思う
- 緊急の付箋紙は名札やアイディアソンで使用できたのでよかった。
- 食べ物の量はちょうどよかった気がする。
- 記録用にも写真を多めに撮った。

## Problem
- 自分が運営を放っておいて開発に集中してたときがありました。（すみません）
- 締め切った後にLTや成果発表の希望者・チームがいた。
- 懇親会のときにお一人様になっている参加者がいた(ような気がした)

## Try
- LTや成果発表の受付締め切り前についての口頭のアナウンスがあったほうがよかった。
- 辺りを見回して声がけするようにする。


新幹線内で考えただけなので後ほど追加するかも

**Comment by adachi-tsukasa** [comment]
色々あったけど本当にお疲れ様でした…！！！

## Keep
- 今年も関西開催できたこと 皆様ありがとうございました！
- 受付スムーズでした
- 配信できたのびっくりしました
- LT前/中の食べ飲み量ちょうど良かったです
- 二次会のセッティングありがとうございました
- 金銭面管理いつもありがとうございます…

## Problem
- 全体見舞わせてない 不慣れ感
  - 司会をくろみささんに投げてたのでもっと色んな人に配慮できた
  - 常に妙にワタワタしてた 傍から見ると心配になる
- LT大会は何を発表して良いの？状態に一時なった
  - 成果発表は別枠ではなく、LT大会と一緒であるアナウンス不足
- 人数的に自己紹介タイムがあっても良かったのでは
  - 1分/1人ぐらいでサクサク自己紹介
  - 今回の参加者のほとんどがアイディアソンの場に行っていた

## Try
- 事前のハッカソンチームの結成サポート
  - 事前にチームを組んでおきたかった声を聞きました
  - 早めにチャンネルを作れば何かできそう
  - trebyさんのツール
- 成果発表はできなくても、作っていた内容を公開する
  - 「名前：作っていたもの」 で簡単なリストを作るとハッカソン参加した感でてきそう

**Comment by crssnky** [comment]
## Keep
- 参加者、増 or 継続参加
  - 初めての方にも楽しんでいただけた
- 関西開催
  - 地元スタッフも増えそう(?)
- 配信できた
  - YoutubeLiveが手軽だった(前回の京都では、エンコの関係とかで悩んでた場面も)
- スポンサー制度
- 歓談の時間

## Problem
- **遅刻**(もう東名阪は信用しない)
- 当日は配信準備やBOX探しなどで、一人(スタッフ同士)の時間に入っていた
- im@square立てたかった
- LT=愛を語る+成果発表 が伝わってなかった

## Try
- 次こそは参加者全員を受付で出迎え、交流を深めたい
- 結局カメラはスライドを映すだけなら、カメラを介さず入力すれば良かった
- im@square
- オープニング30分を守って、自己紹介タイムをする
  - スキル/アイデアを事前に共有できる何か
- スタッフらしさ、配慮

**Comment by hamup8** [comment]
本当にみなさんお疲れ様でした！

## Keep
- 飲食・お菓子の量が丁度良かった
- 司会進行、大きな問題もなくできていた(くろみささんお疲れ様でした！)
- アイデアソンのアテンドできた（早い段階で和気藹々といった感じでよかった。）
- 意識合わせ、懸念解消を事前にできた。  
（関西だとどうしても事前打ち合わせがフルリモートになるので継続していきたい。）
- 属人化回避の第一歩ができた（？）
- （愛を語る）LTできた

## Problem
- お酒の配達時間にそわそわした。  
（カクヤスを使うと配達時間が細かく選べないので、  
  冷蔵庫使用可の会場であれば2時間前くらいには搬入しとくといいかも。）
- LT募集の動きが思ったより参加者に伝わってなかった（im@squareの導入）
- （技術的な）LTできなかった


## Try
- 会中の参加者への配慮
- 誰が何をやっていたか不透明なので、アウトプットを簡単に纏められたらいいですね
- 参加者以外への発信  
（Twitterに会場の写真あげたり、配信の告知を打ったり…etc  
  今回は参加してみたいという声がTwitterでも多い気がしたので。）

**Comment by forno** [comment]
アイマスハッカソンお疲れ様でした．
参加者も反省残していい・・・のよね？

## Keep

- 食事をあらかた食べてからTLに入ったのが良かった．
  * LT始まる前に一枚だけ残ったピザをLT終わった後に食べてたりしていたので，今回のように時間分けてしまうのが吉っぽい?
- アイデアソンの場が始めに自己紹介の場として活用された．
- アイデアソンではまとめ役の人が現れ，しっかりとした進行が取れていた．
  * 特にタイムスケジュールをピシッと決めてくださった方々，ありがとうございます．
- 関西なので参加しようという気になれた．
  * 時期も学生にとっては春休みで参加しやすかった．
- 突発的チーム参加楽しかった．

## Problem

- LTの受付方法が不明瞭に感じられた．
  * 受付がSlack, 現場の二か所あり，情報が分散したことも原因かもしれない?
  * 説明を聞いている限りでは事前にはSlack, 会場が開いてからは現場受付という説明にも聞こえた．
- アイデアソンの結果，アイデアソン参加者が全員同じプロジェクト作成を始めた．
- LTに何を求めているのか，ハッカソンで何を開発してほしいのかが明確にはわかりづらかった．
- チーム開発で急に紙を必要としてしまった．
- 発表しなかった人もいたかも
- (私が)LTするネタをきちんと用意してなかった．

## Try

- どんな技術力を持った人がわかる自己紹介の場があるとうれしい
- 一通り全員が発表を行うように，チームを把握して発表をお願いする
  * 受け身な方にも成果発表してほしい
- アイデアソンの進行ガイドがあるとうれしい
  * 最後に好きなアイデアをひょいひょいとっていくタイムが明確にあるとよかったかな
- 突発チームが必要そうな，紙，太めのペン等を3チーム分くらい持ってもいいかもしれない．
  * ノートを用意して書き足してくようにして，アイデアいっぱいのノートをIM@Studyに作りたい(願望)

**Comment by urou** [comment]
皆様お疲れ様でした～

 ## Keep
- 関西で開催できたこと
- 受付の対応はスムーズにできたと思います。
- croMisaさんの司会の感じ(一つ一つのLT発表の後、一言だけではなくしっかりとコメントしてるなあと感心してみていました。)
- LTの様子を配信できたこと
- ハッカソン直前のリモートによるミーティング

 ## Problem
- カンパボックス(結果論ですが回収に行っとけばよかったです・・・)
- 全体の自己紹介の時間をとっても良かったかもしれない。
- LT申込締切後に何件か申し出があったのでLT申込方法の周知をもう少ししたほうがよかったかもしれない。
- 自分のLTの用意ができていなかった


## Try
- スタッフとして周辺への気配りを忘れずにする(浮いてる人がいるように見えた気がしたので。。。)
- 配信担当も兼ねられるようにYouTubeLiveでの配信方法について勉強
- どんなことをしているか昼下がりくらいでどんなものを作っているかヒアリングして最終のスライドでまとめるか、簡単に発表してもらったほうがいいかもしれない

**Comment by adachi-tsukasa** [comment]
振り返り完了しました。ありがとうございました。
