### ISSUE TITLE
IM@S Engineer Talks

### ISSUE THREAD

**Issue by treby** [imas/hackathon#91]
# 概要

- 日時: 2018/07/07 (Sat) 15:00〜21:00
- 場所: [Speee Launge](http://tech.speee.jp/entry/2017/05/26/101342) 六本木 / Max 100人
- Keynote 発表者
  - 外部招待: セキュリティエンジニア（志保P） ※このセッションは配信なしにするかも
  - @banjun
  - @mzp
- CFP (IM@Square 使う？)
- スタッフ
  - @treby (chief)
  - @hamaco 
  - @takayamaki 
  - @adachi-tsukasa 
  - @hamup8 
  - @YutaGoto 
- イラスト: No idea (もしどなたかあてがありましたら) -> fusagikoさんが頑張る

**Comment by treby** [comment]
イベントページ: https://imas.connpass.com/event/90996/

**Comment by adachi-tsukasa** [comment]
# 食べ飲みまとめ

## 食べ物の部@ピザハット赤坂店

ピザLサイズ（2種類）*20枚 = 37,020円（1,851円/枚)


## 飲み物の部@カクヤス

**ビール (340ml缶60本)**
2,905円/24缶ケース(48本)
115円/12本
2,905円 * 2  = 5,810円
115円 * 12 = 1,380円

**チューハイ(350ml缶30本)**
108円/1本
108 *30 = 3,240円

**ソフドリ(2Lペットボトル*2本 + 1.5Lペットペットボトル2本)**
171円/2本
171 * 2 = 342円
193円/2本
193 * 2 = 386円

飲み物合計：11,428円

計 48,448円

## その他

カクヤスは14-15時受け取り、ピザハットは15時半受け取りの注文にします。
（カクヤスが少し早いのは前回ギリギリになってしまったため、かつ1時間単位の指定しかできないため）

問題なさそうであれば、リアクションorコメントください！！！
明日3日（水)に注文予定です。

**Comment by treby** [comment]
お金周りを調整中なので、注文しばらくお待ちいただけると！

**Comment by adachi-tsukasa** [comment]
@treby 了解です！連絡待ってます！

**Comment by treby** [comment]
食べ物について、欲を言えばピザ以外攻めてみたい感じもある。
やはり、手頃なのないかな。

**Comment by treby** [comment]
知見がある(だろう)Hey社のイベント運営チームにヒアリングしてみよかな

**Comment by treby** [comment]
↑とかいかがでしょう？ @adachi-tsukasa

**Comment by adachi-tsukasa** [comment]
@treby お金の余裕があるかわからなかったand人数多いから間違いない方が良いかな=ピザと考えていました。UberEatsとかも考えたんですけど、50人over向けじゃないんですよね。
ヒアリング！もししていただけるのであれば、お願いしたいす！！

**Comment by adachi-tsukasa** [comment]
金曜中に食べ飲みの注文できれば問題ないので、まだ時間ありますー。

**Comment by hamaco** [comment]
よく見かけるのだと :sushi: とか、ファミレスとかのパーティーセットみたいなのとか?

**Comment by hamaco** [comment]
https://techlog.voyagegroup.com/entry/2016/12/05/235631

**Comment by adachi-tsukasa** [comment]
ピザ以外の食べ物注文done!
ピザは先日の試算20枚から10枚に変更になります。
きっと @hamup8 が今日明日注文してくれるはずです。

予算も50k以内大丈夫そうです！（食べ物だけで約42kになる見込み）

**Comment by hamup8** [comment]
ピザ注文done!
10枚で18,445円になりました。
配達時刻は15:15〜15:45の間になるそうです！

**Comment by adachi-tsukasa** [comment]
## 懇親会会場候補
 - [トゥードッグスタップルーム Twodogs Taproom(イタリアン・フレンチ)＜ネット予約可＞ | ホットペッパーグルメ](https://www.hotpepper.jp/strJ001042166/)
 - [BrewDog Roppongi | アジア圏初のBrewDogオフィシャルバー](http://brewdogbar.jp/) 
 - [Hobgoblin Pubs | Tokyo](http://hobgoblin.jp/)
