### ISSUE TITLE
imas engineer 合同本企画

### ISSUE THREAD

**Issue by YutaGoto** [imas/hackathon#92]
## 概要

アイマスエンジニアによる合同本。技術本。

im@studyのSlackの `#imasbook` で話し合い始めました。

- 寄稿者: 未定(issueにスタンプで反応した人が寄稿する？)  ❤️  `:heart:`
- 管理者: 未定()
- 管理の方法: imasのpublic repository もしくは だれかのprivate repository で管理する
- 書式: わかんない
- 締切: 技術書典5 もしくは 冬コミ に間に合うくらい

## 決めること

- [x] 技術と言っても幅広いから書くテーマを決めるかどうか
- [x] 最低最高寄稿人数を決めるかどうか
- [x] 管理の方法をどうするか
- [ ] 書式をどうするか
  - tex
  - md
  - word
  - InDesign
  - ...

**Comment by kiridaruma** [comment]
合同本企画のためのリポジトリが立ったので、以降はそちらで

https://github.com/imas/imasbook
